
#include <stdio.h>
#include "lazy_glpk.h"

/* C does not support bool, let's do it with macros */
#define bool int
#define true 1
#define false 0

int load_glpk_symbols() {
    int res;
    bool try_another;
    try_another = true;

    if (lt_dlinit () != 0) return SYMBOL_LOAD_FAIL;

    try_another = !(__glpk_handle = lt_dlopenext("libglpk"));
    if (try_another) try_another = !(__glpk_handle = lt_dlopenext("glpk"));
    if (try_another) return SYMBOL_LOAD_FAIL;

    res = SYMBOL_LOAD_SUCCESS;

    if (!(__symbolic_glp_add_arc = lt_dlsym(__glpk_handle, "glp_add_arc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_add_cols = lt_dlsym(__glpk_handle, "glp_add_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_add_rows = lt_dlsym(__glpk_handle, "glp_add_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_add_vertices = lt_dlsym(__glpk_handle, "glp_add_vertices"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_adv_basis = lt_dlsym(__glpk_handle, "glp_adv_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_analyze_bound = lt_dlsym(__glpk_handle, "glp_analyze_bound"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_analyze_coef = lt_dlsym(__glpk_handle, "glp_analyze_coef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_asnprob_hall = lt_dlsym(__glpk_handle, "glp_asnprob_hall"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_asnprob_lp = lt_dlsym(__glpk_handle, "glp_asnprob_lp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_asnprob_okalg = lt_dlsym(__glpk_handle, "glp_asnprob_okalg"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_assert_ = lt_dlsym(__glpk_handle, "glp_assert_"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_bf_exists = lt_dlsym(__glpk_handle, "glp_bf_exists"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_bf_updated = lt_dlsym(__glpk_handle, "glp_bf_updated"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_btran = lt_dlsym(__glpk_handle, "glp_btran"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_calloc = lt_dlsym(__glpk_handle, "glp_calloc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_check_asnprob = lt_dlsym(__glpk_handle, "glp_check_asnprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_check_dup = lt_dlsym(__glpk_handle, "glp_check_dup"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_close_tee = lt_dlsym(__glpk_handle, "glp_close_tee"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_copy_prob = lt_dlsym(__glpk_handle, "glp_copy_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_cpx_basis = lt_dlsym(__glpk_handle, "glp_cpx_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_create_graph = lt_dlsym(__glpk_handle, "glp_create_graph"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_create_index = lt_dlsym(__glpk_handle, "glp_create_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_create_prob = lt_dlsym(__glpk_handle, "glp_create_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_create_v_index = lt_dlsym(__glpk_handle, "glp_create_v_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_del_arc = lt_dlsym(__glpk_handle, "glp_del_arc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_del_cols = lt_dlsym(__glpk_handle, "glp_del_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_delete_graph = lt_dlsym(__glpk_handle, "glp_delete_graph"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_delete_index = lt_dlsym(__glpk_handle, "glp_delete_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_delete_prob = lt_dlsym(__glpk_handle, "glp_delete_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_delete_v_index = lt_dlsym(__glpk_handle, "glp_delete_v_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_del_rows = lt_dlsym(__glpk_handle, "glp_del_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_del_vertices = lt_dlsym(__glpk_handle, "glp_del_vertices"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_difftime = lt_dlsym(__glpk_handle, "glp_difftime"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_dual_rtest = lt_dlsym(__glpk_handle, "glp_dual_rtest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_erase_graph = lt_dlsym(__glpk_handle, "glp_erase_graph"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_erase_prob = lt_dlsym(__glpk_handle, "glp_erase_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_error_ = lt_dlsym(__glpk_handle, "glp_error_"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_error_hook = lt_dlsym(__glpk_handle, "glp_error_hook"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_eval_tab_col = lt_dlsym(__glpk_handle, "glp_eval_tab_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_eval_tab_row = lt_dlsym(__glpk_handle, "glp_eval_tab_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_exact = lt_dlsym(__glpk_handle, "glp_exact"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_factorize = lt_dlsym(__glpk_handle, "glp_factorize"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_find_col = lt_dlsym(__glpk_handle, "glp_find_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_find_row = lt_dlsym(__glpk_handle, "glp_find_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_find_vertex = lt_dlsym(__glpk_handle, "glp_find_vertex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_free = lt_dlsym(__glpk_handle, "glp_free"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_free_env = lt_dlsym(__glpk_handle, "glp_free_env"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ftran = lt_dlsym(__glpk_handle, "glp_ftran"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_bfcp = lt_dlsym(__glpk_handle, "glp_get_bfcp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_bhead = lt_dlsym(__glpk_handle, "glp_get_bhead"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_bind = lt_dlsym(__glpk_handle, "glp_get_col_bind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_dual = lt_dlsym(__glpk_handle, "glp_get_col_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_kind = lt_dlsym(__glpk_handle, "glp_get_col_kind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_lb = lt_dlsym(__glpk_handle, "glp_get_col_lb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_name = lt_dlsym(__glpk_handle, "glp_get_col_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_prim = lt_dlsym(__glpk_handle, "glp_get_col_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_stat = lt_dlsym(__glpk_handle, "glp_get_col_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_type = lt_dlsym(__glpk_handle, "glp_get_col_type"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_col_ub = lt_dlsym(__glpk_handle, "glp_get_col_ub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_dual_stat = lt_dlsym(__glpk_handle, "glp_get_dual_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_mat_col = lt_dlsym(__glpk_handle, "glp_get_mat_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_mat_row = lt_dlsym(__glpk_handle, "glp_get_mat_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_num_bin = lt_dlsym(__glpk_handle, "glp_get_num_bin"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_num_cols = lt_dlsym(__glpk_handle, "glp_get_num_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_num_int = lt_dlsym(__glpk_handle, "glp_get_num_int"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_num_nz = lt_dlsym(__glpk_handle, "glp_get_num_nz"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_num_rows = lt_dlsym(__glpk_handle, "glp_get_num_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_obj_coef = lt_dlsym(__glpk_handle, "glp_get_obj_coef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_obj_dir = lt_dlsym(__glpk_handle, "glp_get_obj_dir"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_obj_name = lt_dlsym(__glpk_handle, "glp_get_obj_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_obj_val = lt_dlsym(__glpk_handle, "glp_get_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_prim_stat = lt_dlsym(__glpk_handle, "glp_get_prim_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_prob_name = lt_dlsym(__glpk_handle, "glp_get_prob_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_rii = lt_dlsym(__glpk_handle, "glp_get_rii"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_bind = lt_dlsym(__glpk_handle, "glp_get_row_bind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_dual = lt_dlsym(__glpk_handle, "glp_get_row_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_lb = lt_dlsym(__glpk_handle, "glp_get_row_lb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_name = lt_dlsym(__glpk_handle, "glp_get_row_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_prim = lt_dlsym(__glpk_handle, "glp_get_row_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_stat = lt_dlsym(__glpk_handle, "glp_get_row_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_type = lt_dlsym(__glpk_handle, "glp_get_row_type"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_row_ub = lt_dlsym(__glpk_handle, "glp_get_row_ub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_sjj = lt_dlsym(__glpk_handle, "glp_get_sjj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_status = lt_dlsym(__glpk_handle, "glp_get_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_get_unbnd_ray = lt_dlsym(__glpk_handle, "glp_get_unbnd_ray"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_gridgen = lt_dlsym(__glpk_handle, "glp_gridgen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_cpxcp = lt_dlsym(__glpk_handle, "glp_init_cpxcp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_env = lt_dlsym(__glpk_handle, "glp_init_env"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_iocp = lt_dlsym(__glpk_handle, "glp_init_iocp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_iptcp = lt_dlsym(__glpk_handle, "glp_init_iptcp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_mpscp = lt_dlsym(__glpk_handle, "glp_init_mpscp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_init_smcp = lt_dlsym(__glpk_handle, "glp_init_smcp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_interior = lt_dlsym(__glpk_handle, "glp_interior"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_intopt = lt_dlsym(__glpk_handle, "glp_intopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_add_row = lt_dlsym(__glpk_handle, "glp_ios_add_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_best_node = lt_dlsym(__glpk_handle, "glp_ios_best_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_branch_upon = lt_dlsym(__glpk_handle, "glp_ios_branch_upon"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_can_branch = lt_dlsym(__glpk_handle, "glp_ios_can_branch"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_clear_pool = lt_dlsym(__glpk_handle, "glp_ios_clear_pool"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_curr_node = lt_dlsym(__glpk_handle, "glp_ios_curr_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_del_row = lt_dlsym(__glpk_handle, "glp_ios_del_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_get_prob = lt_dlsym(__glpk_handle, "glp_ios_get_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_heur_sol = lt_dlsym(__glpk_handle, "glp_ios_heur_sol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_mip_gap = lt_dlsym(__glpk_handle, "glp_ios_mip_gap"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_next_node = lt_dlsym(__glpk_handle, "glp_ios_next_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_node_bound = lt_dlsym(__glpk_handle, "glp_ios_node_bound"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_node_data = lt_dlsym(__glpk_handle, "glp_ios_node_data"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_node_level = lt_dlsym(__glpk_handle, "glp_ios_node_level"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_pool_size = lt_dlsym(__glpk_handle, "glp_ios_pool_size"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_prev_node = lt_dlsym(__glpk_handle, "glp_ios_prev_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_reason = lt_dlsym(__glpk_handle, "glp_ios_reason"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_row_attr = lt_dlsym(__glpk_handle, "glp_ios_row_attr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_select_node = lt_dlsym(__glpk_handle, "glp_ios_select_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_terminate = lt_dlsym(__glpk_handle, "glp_ios_terminate"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_tree_size = lt_dlsym(__glpk_handle, "glp_ios_tree_size"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ios_up_node = lt_dlsym(__glpk_handle, "glp_ios_up_node"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_col_dual = lt_dlsym(__glpk_handle, "glp_ipt_col_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_col_prim = lt_dlsym(__glpk_handle, "glp_ipt_col_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_obj_val = lt_dlsym(__glpk_handle, "glp_ipt_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_row_dual = lt_dlsym(__glpk_handle, "glp_ipt_row_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_row_prim = lt_dlsym(__glpk_handle, "glp_ipt_row_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_ipt_status = lt_dlsym(__glpk_handle, "glp_ipt_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_load_matrix = lt_dlsym(__glpk_handle, "glp_load_matrix"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_add_cols = lt_dlsym(__glpk_handle, "_glp_lpx_add_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_add_rows = lt_dlsym(__glpk_handle, "_glp_lpx_add_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_adv_basis = lt_dlsym(__glpk_handle, "_glp_lpx_adv_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_check_int = lt_dlsym(__glpk_handle, "_glp_lpx_check_int"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_check_kkt = lt_dlsym(__glpk_handle, "_glp_lpx_check_kkt"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_cpx_basis = lt_dlsym(__glpk_handle, "_glp_lpx_cpx_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_create_index = lt_dlsym(__glpk_handle, "_glp_lpx_create_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_create_prob = lt_dlsym(__glpk_handle, "_glp_lpx_create_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_del_cols = lt_dlsym(__glpk_handle, "_glp_lpx_del_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_delete_index = lt_dlsym(__glpk_handle, "_glp_lpx_delete_index"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_delete_prob = lt_dlsym(__glpk_handle, "_glp_lpx_delete_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_del_rows = lt_dlsym(__glpk_handle, "_glp_lpx_del_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_dual_ratio_test = lt_dlsym(__glpk_handle, "_glp_lpx_dual_ratio_test"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_eval_tab_col = lt_dlsym(__glpk_handle, "_glp_lpx_eval_tab_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_eval_tab_row = lt_dlsym(__glpk_handle, "_glp_lpx_eval_tab_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_exact = lt_dlsym(__glpk_handle, "_glp_lpx_exact"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_find_col = lt_dlsym(__glpk_handle, "_glp_lpx_find_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_find_row = lt_dlsym(__glpk_handle, "_glp_lpx_find_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_class = lt_dlsym(__glpk_handle, "_glp_lpx_get_class"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_bnds = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_dual = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_info = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_info"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_kind = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_kind"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_lb = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_lb"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_name = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_prim = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_stat = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_type = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_type"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_col_ub = lt_dlsym(__glpk_handle, "_glp_lpx_get_col_ub"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_dual_stat = lt_dlsym(__glpk_handle, "_glp_lpx_get_dual_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_int_parm = lt_dlsym(__glpk_handle, "_glp_lpx_get_int_parm"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_mat_col = lt_dlsym(__glpk_handle, "_glp_lpx_get_mat_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_mat_row = lt_dlsym(__glpk_handle, "_glp_lpx_get_mat_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_num_bin = lt_dlsym(__glpk_handle, "_glp_lpx_get_num_bin"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_num_cols = lt_dlsym(__glpk_handle, "_glp_lpx_get_num_cols"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_num_int = lt_dlsym(__glpk_handle, "_glp_lpx_get_num_int"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_num_nz = lt_dlsym(__glpk_handle, "_glp_lpx_get_num_nz"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_num_rows = lt_dlsym(__glpk_handle, "_glp_lpx_get_num_rows"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_obj_coef = lt_dlsym(__glpk_handle, "_glp_lpx_get_obj_coef"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_obj_dir = lt_dlsym(__glpk_handle, "_glp_lpx_get_obj_dir"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_obj_name = lt_dlsym(__glpk_handle, "_glp_lpx_get_obj_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_obj_val = lt_dlsym(__glpk_handle, "_glp_lpx_get_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_prim_stat = lt_dlsym(__glpk_handle, "_glp_lpx_get_prim_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_prob_name = lt_dlsym(__glpk_handle, "_glp_lpx_get_prob_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_ray_info = lt_dlsym(__glpk_handle, "_glp_lpx_get_ray_info"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_real_parm = lt_dlsym(__glpk_handle, "_glp_lpx_get_real_parm"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_bnds = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_dual = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_info = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_info"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_lb = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_lb"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_name = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_prim = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_stat = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_type = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_type"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_row_ub = lt_dlsym(__glpk_handle, "_glp_lpx_get_row_ub"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_get_status = lt_dlsym(__glpk_handle, "_glp_lpx_get_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_integer = lt_dlsym(__glpk_handle, "_glp_lpx_integer"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_interior = lt_dlsym(__glpk_handle, "_glp_lpx_interior"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_intopt = lt_dlsym(__glpk_handle, "_glp_lpx_intopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_col_dual = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_col_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_col_prim = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_col_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_obj_val = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_row_dual = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_row_dual"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_row_prim = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_row_prim"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_ipt_status = lt_dlsym(__glpk_handle, "_glp_lpx_ipt_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_is_b_avail = lt_dlsym(__glpk_handle, "_glp_lpx_is_b_avail"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_load_matrix = lt_dlsym(__glpk_handle, "_glp_lpx_load_matrix"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_main = lt_dlsym(__glpk_handle, "_glp_lpx_main"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_mip_col_val = lt_dlsym(__glpk_handle, "_glp_lpx_mip_col_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_mip_obj_val = lt_dlsym(__glpk_handle, "_glp_lpx_mip_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_mip_row_val = lt_dlsym(__glpk_handle, "_glp_lpx_mip_row_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_mip_status = lt_dlsym(__glpk_handle, "_glp_lpx_mip_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_prim_ratio_test = lt_dlsym(__glpk_handle, "_glp_lpx_prim_ratio_test"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_print_ips = lt_dlsym(__glpk_handle, "_glp_lpx_print_ips"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_print_mip = lt_dlsym(__glpk_handle, "_glp_lpx_print_mip"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_print_prob = lt_dlsym(__glpk_handle, "_glp_lpx_print_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_print_sens_bnds = lt_dlsym(__glpk_handle, "_glp_lpx_print_sens_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_print_sol = lt_dlsym(__glpk_handle, "_glp_lpx_print_sol"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_read_bas = lt_dlsym(__glpk_handle, "_glp_lpx_read_bas"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_read_cpxlp = lt_dlsym(__glpk_handle, "_glp_lpx_read_cpxlp"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_read_freemps = lt_dlsym(__glpk_handle, "_glp_lpx_read_freemps"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_read_model = lt_dlsym(__glpk_handle, "_glp_lpx_read_model"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_read_mps = lt_dlsym(__glpk_handle, "_glp_lpx_read_mps"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_reset_parms = lt_dlsym(__glpk_handle, "_glp_lpx_reset_parms"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_scale_prob = lt_dlsym(__glpk_handle, "_glp_lpx_scale_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_class = lt_dlsym(__glpk_handle, "_glp_lpx_set_class"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_col_bnds = lt_dlsym(__glpk_handle, "_glp_lpx_set_col_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_col_kind = lt_dlsym(__glpk_handle, "_glp_lpx_set_col_kind"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_col_name = lt_dlsym(__glpk_handle, "_glp_lpx_set_col_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_col_stat = lt_dlsym(__glpk_handle, "_glp_lpx_set_col_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_int_parm = lt_dlsym(__glpk_handle, "_glp_lpx_set_int_parm"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_mat_col = lt_dlsym(__glpk_handle, "_glp_lpx_set_mat_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_mat_row = lt_dlsym(__glpk_handle, "_glp_lpx_set_mat_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_obj_coef = lt_dlsym(__glpk_handle, "_glp_lpx_set_obj_coef"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_obj_dir = lt_dlsym(__glpk_handle, "_glp_lpx_set_obj_dir"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_obj_name = lt_dlsym(__glpk_handle, "_glp_lpx_set_obj_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_prob_name = lt_dlsym(__glpk_handle, "_glp_lpx_set_prob_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_real_parm = lt_dlsym(__glpk_handle, "_glp_lpx_set_real_parm"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_row_bnds = lt_dlsym(__glpk_handle, "_glp_lpx_set_row_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_row_name = lt_dlsym(__glpk_handle, "_glp_lpx_set_row_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_set_row_stat = lt_dlsym(__glpk_handle, "_glp_lpx_set_row_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_simplex = lt_dlsym(__glpk_handle, "_glp_lpx_simplex"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_std_basis = lt_dlsym(__glpk_handle, "_glp_lpx_std_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_transform_col = lt_dlsym(__glpk_handle, "_glp_lpx_transform_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_transform_row = lt_dlsym(__glpk_handle, "_glp_lpx_transform_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_unscale_prob = lt_dlsym(__glpk_handle, "_glp_lpx_unscale_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_warm_up = lt_dlsym(__glpk_handle, "_glp_lpx_warm_up"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_write_bas = lt_dlsym(__glpk_handle, "_glp_lpx_write_bas"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_write_cpxlp = lt_dlsym(__glpk_handle, "_glp_lpx_write_cpxlp"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_write_freemps = lt_dlsym(__glpk_handle, "_glp_lpx_write_freemps"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_write_mps = lt_dlsym(__glpk_handle, "_glp_lpx_write_mps"))) res = SYMBOL_MISSING;
    if (!(__symbolic__glp_lpx_write_pb = lt_dlsym(__glpk_handle, "_glp_lpx_write_pb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_main = lt_dlsym(__glpk_handle, "glp_main"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_malloc = lt_dlsym(__glpk_handle, "glp_malloc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_maxflow_ffalg = lt_dlsym(__glpk_handle, "glp_maxflow_ffalg"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_maxflow_lp = lt_dlsym(__glpk_handle, "glp_maxflow_lp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mem_limit = lt_dlsym(__glpk_handle, "glp_mem_limit"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mem_usage = lt_dlsym(__glpk_handle, "glp_mem_usage"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mincost_lp = lt_dlsym(__glpk_handle, "glp_mincost_lp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mincost_okalg = lt_dlsym(__glpk_handle, "glp_mincost_okalg"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mip_col_val = lt_dlsym(__glpk_handle, "glp_mip_col_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mip_obj_val = lt_dlsym(__glpk_handle, "glp_mip_obj_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mip_row_val = lt_dlsym(__glpk_handle, "glp_mip_row_val"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mip_status = lt_dlsym(__glpk_handle, "glp_mip_status"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_alloc_wksp = lt_dlsym(__glpk_handle, "glp_mpl_alloc_wksp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_build_prob = lt_dlsym(__glpk_handle, "glp_mpl_build_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_free_wksp = lt_dlsym(__glpk_handle, "glp_mpl_free_wksp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_generate = lt_dlsym(__glpk_handle, "glp_mpl_generate"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_postsolve = lt_dlsym(__glpk_handle, "glp_mpl_postsolve"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_read_data = lt_dlsym(__glpk_handle, "glp_mpl_read_data"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_mpl_read_model = lt_dlsym(__glpk_handle, "glp_mpl_read_model"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_netgen = lt_dlsym(__glpk_handle, "glp_netgen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_open_tee = lt_dlsym(__glpk_handle, "glp_open_tee"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_prim_rtest = lt_dlsym(__glpk_handle, "glp_prim_rtest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_printf = lt_dlsym(__glpk_handle, "glp_printf"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_print_ipt = lt_dlsym(__glpk_handle, "glp_print_ipt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_print_mip = lt_dlsym(__glpk_handle, "glp_print_mip"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_print_ranges = lt_dlsym(__glpk_handle, "glp_print_ranges"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_print_sol = lt_dlsym(__glpk_handle, "glp_print_sol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_asnprob = lt_dlsym(__glpk_handle, "glp_read_asnprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_ccdata = lt_dlsym(__glpk_handle, "glp_read_ccdata"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_graph = lt_dlsym(__glpk_handle, "glp_read_graph"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_ipt = lt_dlsym(__glpk_handle, "glp_read_ipt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_lp = lt_dlsym(__glpk_handle, "glp_read_lp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_maxflow = lt_dlsym(__glpk_handle, "glp_read_maxflow"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_mincost = lt_dlsym(__glpk_handle, "glp_read_mincost"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_mip = lt_dlsym(__glpk_handle, "glp_read_mip"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_mps = lt_dlsym(__glpk_handle, "glp_read_mps"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_prob = lt_dlsym(__glpk_handle, "glp_read_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_read_sol = lt_dlsym(__glpk_handle, "glp_read_sol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_rmfgen = lt_dlsym(__glpk_handle, "glp_rmfgen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_scale_prob = lt_dlsym(__glpk_handle, "glp_scale_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_close_file = lt_dlsym(__glpk_handle, "glp_sdf_close_file"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_error = lt_dlsym(__glpk_handle, "glp_sdf_error"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_line = lt_dlsym(__glpk_handle, "glp_sdf_line"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_open_file = lt_dlsym(__glpk_handle, "glp_sdf_open_file"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_read_int = lt_dlsym(__glpk_handle, "glp_sdf_read_int"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_read_item = lt_dlsym(__glpk_handle, "glp_sdf_read_item"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_read_num = lt_dlsym(__glpk_handle, "glp_sdf_read_num"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_read_text = lt_dlsym(__glpk_handle, "glp_sdf_read_text"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_set_jump = lt_dlsym(__glpk_handle, "glp_sdf_set_jump"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sdf_warning = lt_dlsym(__glpk_handle, "glp_sdf_warning"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_bfcp = lt_dlsym(__glpk_handle, "glp_set_bfcp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_col_bnds = lt_dlsym(__glpk_handle, "glp_set_col_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_col_kind = lt_dlsym(__glpk_handle, "glp_set_col_kind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_col_name = lt_dlsym(__glpk_handle, "glp_set_col_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_col_stat = lt_dlsym(__glpk_handle, "glp_set_col_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_graph_name = lt_dlsym(__glpk_handle, "glp_set_graph_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_mat_col = lt_dlsym(__glpk_handle, "glp_set_mat_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_mat_row = lt_dlsym(__glpk_handle, "glp_set_mat_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_obj_coef = lt_dlsym(__glpk_handle, "glp_set_obj_coef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_obj_dir = lt_dlsym(__glpk_handle, "glp_set_obj_dir"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_obj_name = lt_dlsym(__glpk_handle, "glp_set_obj_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_prob_name = lt_dlsym(__glpk_handle, "glp_set_prob_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_rii = lt_dlsym(__glpk_handle, "glp_set_rii"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_row_bnds = lt_dlsym(__glpk_handle, "glp_set_row_bnds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_row_name = lt_dlsym(__glpk_handle, "glp_set_row_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_row_stat = lt_dlsym(__glpk_handle, "glp_set_row_stat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_sjj = lt_dlsym(__glpk_handle, "glp_set_sjj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_set_vertex_name = lt_dlsym(__glpk_handle, "glp_set_vertex_name"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_simplex = lt_dlsym(__glpk_handle, "glp_simplex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_sort_matrix = lt_dlsym(__glpk_handle, "glp_sort_matrix"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_std_basis = lt_dlsym(__glpk_handle, "glp_std_basis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_strong_comp = lt_dlsym(__glpk_handle, "glp_strong_comp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_term_hook = lt_dlsym(__glpk_handle, "glp_term_hook"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_term_out = lt_dlsym(__glpk_handle, "glp_term_out"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_time = lt_dlsym(__glpk_handle, "glp_time"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_top_sort = lt_dlsym(__glpk_handle, "glp_top_sort"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_transform_col = lt_dlsym(__glpk_handle, "glp_transform_col"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_transform_row = lt_dlsym(__glpk_handle, "glp_transform_row"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_unscale_prob = lt_dlsym(__glpk_handle, "glp_unscale_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_version = lt_dlsym(__glpk_handle, "glp_version"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_vprintf = lt_dlsym(__glpk_handle, "glp_vprintf"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_warm_up = lt_dlsym(__glpk_handle, "glp_warm_up"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_wclique_exact = lt_dlsym(__glpk_handle, "glp_wclique_exact"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_weak_comp = lt_dlsym(__glpk_handle, "glp_weak_comp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_asnprob = lt_dlsym(__glpk_handle, "glp_write_asnprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_ccdata = lt_dlsym(__glpk_handle, "glp_write_ccdata"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_graph = lt_dlsym(__glpk_handle, "glp_write_graph"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_ipt = lt_dlsym(__glpk_handle, "glp_write_ipt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_lp = lt_dlsym(__glpk_handle, "glp_write_lp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_maxflow = lt_dlsym(__glpk_handle, "glp_write_maxflow"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_mincost = lt_dlsym(__glpk_handle, "glp_write_mincost"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_mip = lt_dlsym(__glpk_handle, "glp_write_mip"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_mps = lt_dlsym(__glpk_handle, "glp_write_mps"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_prob = lt_dlsym(__glpk_handle, "glp_write_prob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_glp_write_sol = lt_dlsym(__glpk_handle, "glp_write_sol"))) res = SYMBOL_MISSING;

    return res;
}

void print_glpk_missing_symbols() {

    if (!__symbolic_glp_add_arc) printf("glp_add_arc\n");
    if (!__symbolic_glp_add_cols) printf("glp_add_cols\n");
    if (!__symbolic_glp_add_rows) printf("glp_add_rows\n");
    if (!__symbolic_glp_add_vertices) printf("glp_add_vertices\n");
    if (!__symbolic_glp_adv_basis) printf("glp_adv_basis\n");
    if (!__symbolic_glp_analyze_bound) printf("glp_analyze_bound\n");
    if (!__symbolic_glp_analyze_coef) printf("glp_analyze_coef\n");
    if (!__symbolic_glp_asnprob_hall) printf("glp_asnprob_hall\n");
    if (!__symbolic_glp_asnprob_lp) printf("glp_asnprob_lp\n");
    if (!__symbolic_glp_asnprob_okalg) printf("glp_asnprob_okalg\n");
    if (!__symbolic_glp_assert_) printf("glp_assert_\n");
    if (!__symbolic_glp_bf_exists) printf("glp_bf_exists\n");
    if (!__symbolic_glp_bf_updated) printf("glp_bf_updated\n");
    if (!__symbolic_glp_btran) printf("glp_btran\n");
    if (!__symbolic_glp_calloc) printf("glp_calloc\n");
    if (!__symbolic_glp_check_asnprob) printf("glp_check_asnprob\n");
    if (!__symbolic_glp_check_dup) printf("glp_check_dup\n");
    if (!__symbolic_glp_close_tee) printf("glp_close_tee\n");
    if (!__symbolic_glp_copy_prob) printf("glp_copy_prob\n");
    if (!__symbolic_glp_cpx_basis) printf("glp_cpx_basis\n");
    if (!__symbolic_glp_create_graph) printf("glp_create_graph\n");
    if (!__symbolic_glp_create_index) printf("glp_create_index\n");
    if (!__symbolic_glp_create_prob) printf("glp_create_prob\n");
    if (!__symbolic_glp_create_v_index) printf("glp_create_v_index\n");
    if (!__symbolic_glp_del_arc) printf("glp_del_arc\n");
    if (!__symbolic_glp_del_cols) printf("glp_del_cols\n");
    if (!__symbolic_glp_delete_graph) printf("glp_delete_graph\n");
    if (!__symbolic_glp_delete_index) printf("glp_delete_index\n");
    if (!__symbolic_glp_delete_prob) printf("glp_delete_prob\n");
    if (!__symbolic_glp_delete_v_index) printf("glp_delete_v_index\n");
    if (!__symbolic_glp_del_rows) printf("glp_del_rows\n");
    if (!__symbolic_glp_del_vertices) printf("glp_del_vertices\n");
    if (!__symbolic_glp_difftime) printf("glp_difftime\n");
    if (!__symbolic_glp_dual_rtest) printf("glp_dual_rtest\n");
    if (!__symbolic_glp_erase_graph) printf("glp_erase_graph\n");
    if (!__symbolic_glp_erase_prob) printf("glp_erase_prob\n");
    if (!__symbolic_glp_error_) printf("glp_error_\n");
    if (!__symbolic_glp_error_hook) printf("glp_error_hook\n");
    if (!__symbolic_glp_eval_tab_col) printf("glp_eval_tab_col\n");
    if (!__symbolic_glp_eval_tab_row) printf("glp_eval_tab_row\n");
    if (!__symbolic_glp_exact) printf("glp_exact\n");
    if (!__symbolic_glp_factorize) printf("glp_factorize\n");
    if (!__symbolic_glp_find_col) printf("glp_find_col\n");
    if (!__symbolic_glp_find_row) printf("glp_find_row\n");
    if (!__symbolic_glp_find_vertex) printf("glp_find_vertex\n");
    if (!__symbolic_glp_free) printf("glp_free\n");
    if (!__symbolic_glp_free_env) printf("glp_free_env\n");
    if (!__symbolic_glp_ftran) printf("glp_ftran\n");
    if (!__symbolic_glp_get_bfcp) printf("glp_get_bfcp\n");
    if (!__symbolic_glp_get_bhead) printf("glp_get_bhead\n");
    if (!__symbolic_glp_get_col_bind) printf("glp_get_col_bind\n");
    if (!__symbolic_glp_get_col_dual) printf("glp_get_col_dual\n");
    if (!__symbolic_glp_get_col_kind) printf("glp_get_col_kind\n");
    if (!__symbolic_glp_get_col_lb) printf("glp_get_col_lb\n");
    if (!__symbolic_glp_get_col_name) printf("glp_get_col_name\n");
    if (!__symbolic_glp_get_col_prim) printf("glp_get_col_prim\n");
    if (!__symbolic_glp_get_col_stat) printf("glp_get_col_stat\n");
    if (!__symbolic_glp_get_col_type) printf("glp_get_col_type\n");
    if (!__symbolic_glp_get_col_ub) printf("glp_get_col_ub\n");
    if (!__symbolic_glp_get_dual_stat) printf("glp_get_dual_stat\n");
    if (!__symbolic_glp_get_mat_col) printf("glp_get_mat_col\n");
    if (!__symbolic_glp_get_mat_row) printf("glp_get_mat_row\n");
    if (!__symbolic_glp_get_num_bin) printf("glp_get_num_bin\n");
    if (!__symbolic_glp_get_num_cols) printf("glp_get_num_cols\n");
    if (!__symbolic_glp_get_num_int) printf("glp_get_num_int\n");
    if (!__symbolic_glp_get_num_nz) printf("glp_get_num_nz\n");
    if (!__symbolic_glp_get_num_rows) printf("glp_get_num_rows\n");
    if (!__symbolic_glp_get_obj_coef) printf("glp_get_obj_coef\n");
    if (!__symbolic_glp_get_obj_dir) printf("glp_get_obj_dir\n");
    if (!__symbolic_glp_get_obj_name) printf("glp_get_obj_name\n");
    if (!__symbolic_glp_get_obj_val) printf("glp_get_obj_val\n");
    if (!__symbolic_glp_get_prim_stat) printf("glp_get_prim_stat\n");
    if (!__symbolic_glp_get_prob_name) printf("glp_get_prob_name\n");
    if (!__symbolic_glp_get_rii) printf("glp_get_rii\n");
    if (!__symbolic_glp_get_row_bind) printf("glp_get_row_bind\n");
    if (!__symbolic_glp_get_row_dual) printf("glp_get_row_dual\n");
    if (!__symbolic_glp_get_row_lb) printf("glp_get_row_lb\n");
    if (!__symbolic_glp_get_row_name) printf("glp_get_row_name\n");
    if (!__symbolic_glp_get_row_prim) printf("glp_get_row_prim\n");
    if (!__symbolic_glp_get_row_stat) printf("glp_get_row_stat\n");
    if (!__symbolic_glp_get_row_type) printf("glp_get_row_type\n");
    if (!__symbolic_glp_get_row_ub) printf("glp_get_row_ub\n");
    if (!__symbolic_glp_get_sjj) printf("glp_get_sjj\n");
    if (!__symbolic_glp_get_status) printf("glp_get_status\n");
    if (!__symbolic_glp_get_unbnd_ray) printf("glp_get_unbnd_ray\n");
    if (!__symbolic_glp_gridgen) printf("glp_gridgen\n");
    if (!__symbolic_glp_init_cpxcp) printf("glp_init_cpxcp\n");
    if (!__symbolic_glp_init_env) printf("glp_init_env\n");
    if (!__symbolic_glp_init_iocp) printf("glp_init_iocp\n");
    if (!__symbolic_glp_init_iptcp) printf("glp_init_iptcp\n");
    if (!__symbolic_glp_init_mpscp) printf("glp_init_mpscp\n");
    if (!__symbolic_glp_init_smcp) printf("glp_init_smcp\n");
    if (!__symbolic_glp_interior) printf("glp_interior\n");
    if (!__symbolic_glp_intopt) printf("glp_intopt\n");
    if (!__symbolic_glp_ios_add_row) printf("glp_ios_add_row\n");
    if (!__symbolic_glp_ios_best_node) printf("glp_ios_best_node\n");
    if (!__symbolic_glp_ios_branch_upon) printf("glp_ios_branch_upon\n");
    if (!__symbolic_glp_ios_can_branch) printf("glp_ios_can_branch\n");
    if (!__symbolic_glp_ios_clear_pool) printf("glp_ios_clear_pool\n");
    if (!__symbolic_glp_ios_curr_node) printf("glp_ios_curr_node\n");
    if (!__symbolic_glp_ios_del_row) printf("glp_ios_del_row\n");
    if (!__symbolic_glp_ios_get_prob) printf("glp_ios_get_prob\n");
    if (!__symbolic_glp_ios_heur_sol) printf("glp_ios_heur_sol\n");
    if (!__symbolic_glp_ios_mip_gap) printf("glp_ios_mip_gap\n");
    if (!__symbolic_glp_ios_next_node) printf("glp_ios_next_node\n");
    if (!__symbolic_glp_ios_node_bound) printf("glp_ios_node_bound\n");
    if (!__symbolic_glp_ios_node_data) printf("glp_ios_node_data\n");
    if (!__symbolic_glp_ios_node_level) printf("glp_ios_node_level\n");
    if (!__symbolic_glp_ios_pool_size) printf("glp_ios_pool_size\n");
    if (!__symbolic_glp_ios_prev_node) printf("glp_ios_prev_node\n");
    if (!__symbolic_glp_ios_reason) printf("glp_ios_reason\n");
    if (!__symbolic_glp_ios_row_attr) printf("glp_ios_row_attr\n");
    if (!__symbolic_glp_ios_select_node) printf("glp_ios_select_node\n");
    if (!__symbolic_glp_ios_terminate) printf("glp_ios_terminate\n");
    if (!__symbolic_glp_ios_tree_size) printf("glp_ios_tree_size\n");
    if (!__symbolic_glp_ios_up_node) printf("glp_ios_up_node\n");
    if (!__symbolic_glp_ipt_col_dual) printf("glp_ipt_col_dual\n");
    if (!__symbolic_glp_ipt_col_prim) printf("glp_ipt_col_prim\n");
    if (!__symbolic_glp_ipt_obj_val) printf("glp_ipt_obj_val\n");
    if (!__symbolic_glp_ipt_row_dual) printf("glp_ipt_row_dual\n");
    if (!__symbolic_glp_ipt_row_prim) printf("glp_ipt_row_prim\n");
    if (!__symbolic_glp_ipt_status) printf("glp_ipt_status\n");
    if (!__symbolic_glp_load_matrix) printf("glp_load_matrix\n");
    if (!__symbolic__glp_lpx_add_cols) printf("_glp_lpx_add_cols\n");
    if (!__symbolic__glp_lpx_add_rows) printf("_glp_lpx_add_rows\n");
    if (!__symbolic__glp_lpx_adv_basis) printf("_glp_lpx_adv_basis\n");
    if (!__symbolic__glp_lpx_check_int) printf("_glp_lpx_check_int\n");
    if (!__symbolic__glp_lpx_check_kkt) printf("_glp_lpx_check_kkt\n");
    if (!__symbolic__glp_lpx_cpx_basis) printf("_glp_lpx_cpx_basis\n");
    if (!__symbolic__glp_lpx_create_index) printf("_glp_lpx_create_index\n");
    if (!__symbolic__glp_lpx_create_prob) printf("_glp_lpx_create_prob\n");
    if (!__symbolic__glp_lpx_del_cols) printf("_glp_lpx_del_cols\n");
    if (!__symbolic__glp_lpx_delete_index) printf("_glp_lpx_delete_index\n");
    if (!__symbolic__glp_lpx_delete_prob) printf("_glp_lpx_delete_prob\n");
    if (!__symbolic__glp_lpx_del_rows) printf("_glp_lpx_del_rows\n");
    if (!__symbolic__glp_lpx_dual_ratio_test) printf("_glp_lpx_dual_ratio_test\n");
    if (!__symbolic__glp_lpx_eval_tab_col) printf("_glp_lpx_eval_tab_col\n");
    if (!__symbolic__glp_lpx_eval_tab_row) printf("_glp_lpx_eval_tab_row\n");
    if (!__symbolic__glp_lpx_exact) printf("_glp_lpx_exact\n");
    if (!__symbolic__glp_lpx_find_col) printf("_glp_lpx_find_col\n");
    if (!__symbolic__glp_lpx_find_row) printf("_glp_lpx_find_row\n");
    if (!__symbolic__glp_lpx_get_class) printf("_glp_lpx_get_class\n");
    if (!__symbolic__glp_lpx_get_col_bnds) printf("_glp_lpx_get_col_bnds\n");
    if (!__symbolic__glp_lpx_get_col_dual) printf("_glp_lpx_get_col_dual\n");
    if (!__symbolic__glp_lpx_get_col_info) printf("_glp_lpx_get_col_info\n");
    if (!__symbolic__glp_lpx_get_col_kind) printf("_glp_lpx_get_col_kind\n");
    if (!__symbolic__glp_lpx_get_col_lb) printf("_glp_lpx_get_col_lb\n");
    if (!__symbolic__glp_lpx_get_col_name) printf("_glp_lpx_get_col_name\n");
    if (!__symbolic__glp_lpx_get_col_prim) printf("_glp_lpx_get_col_prim\n");
    if (!__symbolic__glp_lpx_get_col_stat) printf("_glp_lpx_get_col_stat\n");
    if (!__symbolic__glp_lpx_get_col_type) printf("_glp_lpx_get_col_type\n");
    if (!__symbolic__glp_lpx_get_col_ub) printf("_glp_lpx_get_col_ub\n");
    if (!__symbolic__glp_lpx_get_dual_stat) printf("_glp_lpx_get_dual_stat\n");
    if (!__symbolic__glp_lpx_get_int_parm) printf("_glp_lpx_get_int_parm\n");
    if (!__symbolic__glp_lpx_get_mat_col) printf("_glp_lpx_get_mat_col\n");
    if (!__symbolic__glp_lpx_get_mat_row) printf("_glp_lpx_get_mat_row\n");
    if (!__symbolic__glp_lpx_get_num_bin) printf("_glp_lpx_get_num_bin\n");
    if (!__symbolic__glp_lpx_get_num_cols) printf("_glp_lpx_get_num_cols\n");
    if (!__symbolic__glp_lpx_get_num_int) printf("_glp_lpx_get_num_int\n");
    if (!__symbolic__glp_lpx_get_num_nz) printf("_glp_lpx_get_num_nz\n");
    if (!__symbolic__glp_lpx_get_num_rows) printf("_glp_lpx_get_num_rows\n");
    if (!__symbolic__glp_lpx_get_obj_coef) printf("_glp_lpx_get_obj_coef\n");
    if (!__symbolic__glp_lpx_get_obj_dir) printf("_glp_lpx_get_obj_dir\n");
    if (!__symbolic__glp_lpx_get_obj_name) printf("_glp_lpx_get_obj_name\n");
    if (!__symbolic__glp_lpx_get_obj_val) printf("_glp_lpx_get_obj_val\n");
    if (!__symbolic__glp_lpx_get_prim_stat) printf("_glp_lpx_get_prim_stat\n");
    if (!__symbolic__glp_lpx_get_prob_name) printf("_glp_lpx_get_prob_name\n");
    if (!__symbolic__glp_lpx_get_ray_info) printf("_glp_lpx_get_ray_info\n");
    if (!__symbolic__glp_lpx_get_real_parm) printf("_glp_lpx_get_real_parm\n");
    if (!__symbolic__glp_lpx_get_row_bnds) printf("_glp_lpx_get_row_bnds\n");
    if (!__symbolic__glp_lpx_get_row_dual) printf("_glp_lpx_get_row_dual\n");
    if (!__symbolic__glp_lpx_get_row_info) printf("_glp_lpx_get_row_info\n");
    if (!__symbolic__glp_lpx_get_row_lb) printf("_glp_lpx_get_row_lb\n");
    if (!__symbolic__glp_lpx_get_row_name) printf("_glp_lpx_get_row_name\n");
    if (!__symbolic__glp_lpx_get_row_prim) printf("_glp_lpx_get_row_prim\n");
    if (!__symbolic__glp_lpx_get_row_stat) printf("_glp_lpx_get_row_stat\n");
    if (!__symbolic__glp_lpx_get_row_type) printf("_glp_lpx_get_row_type\n");
    if (!__symbolic__glp_lpx_get_row_ub) printf("_glp_lpx_get_row_ub\n");
    if (!__symbolic__glp_lpx_get_status) printf("_glp_lpx_get_status\n");
    if (!__symbolic__glp_lpx_integer) printf("_glp_lpx_integer\n");
    if (!__symbolic__glp_lpx_interior) printf("_glp_lpx_interior\n");
    if (!__symbolic__glp_lpx_intopt) printf("_glp_lpx_intopt\n");
    if (!__symbolic__glp_lpx_ipt_col_dual) printf("_glp_lpx_ipt_col_dual\n");
    if (!__symbolic__glp_lpx_ipt_col_prim) printf("_glp_lpx_ipt_col_prim\n");
    if (!__symbolic__glp_lpx_ipt_obj_val) printf("_glp_lpx_ipt_obj_val\n");
    if (!__symbolic__glp_lpx_ipt_row_dual) printf("_glp_lpx_ipt_row_dual\n");
    if (!__symbolic__glp_lpx_ipt_row_prim) printf("_glp_lpx_ipt_row_prim\n");
    if (!__symbolic__glp_lpx_ipt_status) printf("_glp_lpx_ipt_status\n");
    if (!__symbolic__glp_lpx_is_b_avail) printf("_glp_lpx_is_b_avail\n");
    if (!__symbolic__glp_lpx_load_matrix) printf("_glp_lpx_load_matrix\n");
    if (!__symbolic__glp_lpx_main) printf("_glp_lpx_main\n");
    if (!__symbolic__glp_lpx_mip_col_val) printf("_glp_lpx_mip_col_val\n");
    if (!__symbolic__glp_lpx_mip_obj_val) printf("_glp_lpx_mip_obj_val\n");
    if (!__symbolic__glp_lpx_mip_row_val) printf("_glp_lpx_mip_row_val\n");
    if (!__symbolic__glp_lpx_mip_status) printf("_glp_lpx_mip_status\n");
    if (!__symbolic__glp_lpx_prim_ratio_test) printf("_glp_lpx_prim_ratio_test\n");
    if (!__symbolic__glp_lpx_print_ips) printf("_glp_lpx_print_ips\n");
    if (!__symbolic__glp_lpx_print_mip) printf("_glp_lpx_print_mip\n");
    if (!__symbolic__glp_lpx_print_prob) printf("_glp_lpx_print_prob\n");
    if (!__symbolic__glp_lpx_print_sens_bnds) printf("_glp_lpx_print_sens_bnds\n");
    if (!__symbolic__glp_lpx_print_sol) printf("_glp_lpx_print_sol\n");
    if (!__symbolic__glp_lpx_read_bas) printf("_glp_lpx_read_bas\n");
    if (!__symbolic__glp_lpx_read_cpxlp) printf("_glp_lpx_read_cpxlp\n");
    if (!__symbolic__glp_lpx_read_freemps) printf("_glp_lpx_read_freemps\n");
    if (!__symbolic__glp_lpx_read_model) printf("_glp_lpx_read_model\n");
    if (!__symbolic__glp_lpx_read_mps) printf("_glp_lpx_read_mps\n");
    if (!__symbolic__glp_lpx_reset_parms) printf("_glp_lpx_reset_parms\n");
    if (!__symbolic__glp_lpx_scale_prob) printf("_glp_lpx_scale_prob\n");
    if (!__symbolic__glp_lpx_set_class) printf("_glp_lpx_set_class\n");
    if (!__symbolic__glp_lpx_set_col_bnds) printf("_glp_lpx_set_col_bnds\n");
    if (!__symbolic__glp_lpx_set_col_kind) printf("_glp_lpx_set_col_kind\n");
    if (!__symbolic__glp_lpx_set_col_name) printf("_glp_lpx_set_col_name\n");
    if (!__symbolic__glp_lpx_set_col_stat) printf("_glp_lpx_set_col_stat\n");
    if (!__symbolic__glp_lpx_set_int_parm) printf("_glp_lpx_set_int_parm\n");
    if (!__symbolic__glp_lpx_set_mat_col) printf("_glp_lpx_set_mat_col\n");
    if (!__symbolic__glp_lpx_set_mat_row) printf("_glp_lpx_set_mat_row\n");
    if (!__symbolic__glp_lpx_set_obj_coef) printf("_glp_lpx_set_obj_coef\n");
    if (!__symbolic__glp_lpx_set_obj_dir) printf("_glp_lpx_set_obj_dir\n");
    if (!__symbolic__glp_lpx_set_obj_name) printf("_glp_lpx_set_obj_name\n");
    if (!__symbolic__glp_lpx_set_prob_name) printf("_glp_lpx_set_prob_name\n");
    if (!__symbolic__glp_lpx_set_real_parm) printf("_glp_lpx_set_real_parm\n");
    if (!__symbolic__glp_lpx_set_row_bnds) printf("_glp_lpx_set_row_bnds\n");
    if (!__symbolic__glp_lpx_set_row_name) printf("_glp_lpx_set_row_name\n");
    if (!__symbolic__glp_lpx_set_row_stat) printf("_glp_lpx_set_row_stat\n");
    if (!__symbolic__glp_lpx_simplex) printf("_glp_lpx_simplex\n");
    if (!__symbolic__glp_lpx_std_basis) printf("_glp_lpx_std_basis\n");
    if (!__symbolic__glp_lpx_transform_col) printf("_glp_lpx_transform_col\n");
    if (!__symbolic__glp_lpx_transform_row) printf("_glp_lpx_transform_row\n");
    if (!__symbolic__glp_lpx_unscale_prob) printf("_glp_lpx_unscale_prob\n");
    if (!__symbolic__glp_lpx_warm_up) printf("_glp_lpx_warm_up\n");
    if (!__symbolic__glp_lpx_write_bas) printf("_glp_lpx_write_bas\n");
    if (!__symbolic__glp_lpx_write_cpxlp) printf("_glp_lpx_write_cpxlp\n");
    if (!__symbolic__glp_lpx_write_freemps) printf("_glp_lpx_write_freemps\n");
    if (!__symbolic__glp_lpx_write_mps) printf("_glp_lpx_write_mps\n");
    if (!__symbolic__glp_lpx_write_pb) printf("_glp_lpx_write_pb\n");
    if (!__symbolic_glp_main) printf("glp_main\n");
    if (!__symbolic_glp_malloc) printf("glp_malloc\n");
    if (!__symbolic_glp_maxflow_ffalg) printf("glp_maxflow_ffalg\n");
    if (!__symbolic_glp_maxflow_lp) printf("glp_maxflow_lp\n");
    if (!__symbolic_glp_mem_limit) printf("glp_mem_limit\n");
    if (!__symbolic_glp_mem_usage) printf("glp_mem_usage\n");
    if (!__symbolic_glp_mincost_lp) printf("glp_mincost_lp\n");
    if (!__symbolic_glp_mincost_okalg) printf("glp_mincost_okalg\n");
    if (!__symbolic_glp_mip_col_val) printf("glp_mip_col_val\n");
    if (!__symbolic_glp_mip_obj_val) printf("glp_mip_obj_val\n");
    if (!__symbolic_glp_mip_row_val) printf("glp_mip_row_val\n");
    if (!__symbolic_glp_mip_status) printf("glp_mip_status\n");
    if (!__symbolic_glp_mpl_alloc_wksp) printf("glp_mpl_alloc_wksp\n");
    if (!__symbolic_glp_mpl_build_prob) printf("glp_mpl_build_prob\n");
    if (!__symbolic_glp_mpl_free_wksp) printf("glp_mpl_free_wksp\n");
    if (!__symbolic_glp_mpl_generate) printf("glp_mpl_generate\n");
    if (!__symbolic_glp_mpl_postsolve) printf("glp_mpl_postsolve\n");
    if (!__symbolic_glp_mpl_read_data) printf("glp_mpl_read_data\n");
    if (!__symbolic_glp_mpl_read_model) printf("glp_mpl_read_model\n");
    if (!__symbolic_glp_netgen) printf("glp_netgen\n");
    if (!__symbolic_glp_open_tee) printf("glp_open_tee\n");
    if (!__symbolic_glp_prim_rtest) printf("glp_prim_rtest\n");
    if (!__symbolic_glp_printf) printf("glp_printf\n");
    if (!__symbolic_glp_print_ipt) printf("glp_print_ipt\n");
    if (!__symbolic_glp_print_mip) printf("glp_print_mip\n");
    if (!__symbolic_glp_print_ranges) printf("glp_print_ranges\n");
    if (!__symbolic_glp_print_sol) printf("glp_print_sol\n");
    if (!__symbolic_glp_read_asnprob) printf("glp_read_asnprob\n");
    if (!__symbolic_glp_read_ccdata) printf("glp_read_ccdata\n");
    if (!__symbolic_glp_read_graph) printf("glp_read_graph\n");
    if (!__symbolic_glp_read_ipt) printf("glp_read_ipt\n");
    if (!__symbolic_glp_read_lp) printf("glp_read_lp\n");
    if (!__symbolic_glp_read_maxflow) printf("glp_read_maxflow\n");
    if (!__symbolic_glp_read_mincost) printf("glp_read_mincost\n");
    if (!__symbolic_glp_read_mip) printf("glp_read_mip\n");
    if (!__symbolic_glp_read_mps) printf("glp_read_mps\n");
    if (!__symbolic_glp_read_prob) printf("glp_read_prob\n");
    if (!__symbolic_glp_read_sol) printf("glp_read_sol\n");
    if (!__symbolic_glp_rmfgen) printf("glp_rmfgen\n");
    if (!__symbolic_glp_scale_prob) printf("glp_scale_prob\n");
    if (!__symbolic_glp_sdf_close_file) printf("glp_sdf_close_file\n");
    if (!__symbolic_glp_sdf_error) printf("glp_sdf_error\n");
    if (!__symbolic_glp_sdf_line) printf("glp_sdf_line\n");
    if (!__symbolic_glp_sdf_open_file) printf("glp_sdf_open_file\n");
    if (!__symbolic_glp_sdf_read_int) printf("glp_sdf_read_int\n");
    if (!__symbolic_glp_sdf_read_item) printf("glp_sdf_read_item\n");
    if (!__symbolic_glp_sdf_read_num) printf("glp_sdf_read_num\n");
    if (!__symbolic_glp_sdf_read_text) printf("glp_sdf_read_text\n");
    if (!__symbolic_glp_sdf_set_jump) printf("glp_sdf_set_jump\n");
    if (!__symbolic_glp_sdf_warning) printf("glp_sdf_warning\n");
    if (!__symbolic_glp_set_bfcp) printf("glp_set_bfcp\n");
    if (!__symbolic_glp_set_col_bnds) printf("glp_set_col_bnds\n");
    if (!__symbolic_glp_set_col_kind) printf("glp_set_col_kind\n");
    if (!__symbolic_glp_set_col_name) printf("glp_set_col_name\n");
    if (!__symbolic_glp_set_col_stat) printf("glp_set_col_stat\n");
    if (!__symbolic_glp_set_graph_name) printf("glp_set_graph_name\n");
    if (!__symbolic_glp_set_mat_col) printf("glp_set_mat_col\n");
    if (!__symbolic_glp_set_mat_row) printf("glp_set_mat_row\n");
    if (!__symbolic_glp_set_obj_coef) printf("glp_set_obj_coef\n");
    if (!__symbolic_glp_set_obj_dir) printf("glp_set_obj_dir\n");
    if (!__symbolic_glp_set_obj_name) printf("glp_set_obj_name\n");
    if (!__symbolic_glp_set_prob_name) printf("glp_set_prob_name\n");
    if (!__symbolic_glp_set_rii) printf("glp_set_rii\n");
    if (!__symbolic_glp_set_row_bnds) printf("glp_set_row_bnds\n");
    if (!__symbolic_glp_set_row_name) printf("glp_set_row_name\n");
    if (!__symbolic_glp_set_row_stat) printf("glp_set_row_stat\n");
    if (!__symbolic_glp_set_sjj) printf("glp_set_sjj\n");
    if (!__symbolic_glp_set_vertex_name) printf("glp_set_vertex_name\n");
    if (!__symbolic_glp_simplex) printf("glp_simplex\n");
    if (!__symbolic_glp_sort_matrix) printf("glp_sort_matrix\n");
    if (!__symbolic_glp_std_basis) printf("glp_std_basis\n");
    if (!__symbolic_glp_strong_comp) printf("glp_strong_comp\n");
    if (!__symbolic_glp_term_hook) printf("glp_term_hook\n");
    if (!__symbolic_glp_term_out) printf("glp_term_out\n");
    if (!__symbolic_glp_time) printf("glp_time\n");
    if (!__symbolic_glp_top_sort) printf("glp_top_sort\n");
    if (!__symbolic_glp_transform_col) printf("glp_transform_col\n");
    if (!__symbolic_glp_transform_row) printf("glp_transform_row\n");
    if (!__symbolic_glp_unscale_prob) printf("glp_unscale_prob\n");
    if (!__symbolic_glp_version) printf("glp_version\n");
    if (!__symbolic_glp_vprintf) printf("glp_vprintf\n");
    if (!__symbolic_glp_warm_up) printf("glp_warm_up\n");
    if (!__symbolic_glp_wclique_exact) printf("glp_wclique_exact\n");
    if (!__symbolic_glp_weak_comp) printf("glp_weak_comp\n");
    if (!__symbolic_glp_write_asnprob) printf("glp_write_asnprob\n");
    if (!__symbolic_glp_write_ccdata) printf("glp_write_ccdata\n");
    if (!__symbolic_glp_write_graph) printf("glp_write_graph\n");
    if (!__symbolic_glp_write_ipt) printf("glp_write_ipt\n");
    if (!__symbolic_glp_write_lp) printf("glp_write_lp\n");
    if (!__symbolic_glp_write_maxflow) printf("glp_write_maxflow\n");
    if (!__symbolic_glp_write_mincost) printf("glp_write_mincost\n");
    if (!__symbolic_glp_write_mip) printf("glp_write_mip\n");
    if (!__symbolic_glp_write_mps) printf("glp_write_mps\n");
    if (!__symbolic_glp_write_prob) printf("glp_write_prob\n");
    if (!__symbolic_glp_write_sol) printf("glp_write_sol\n");

}

int unload_glpk_symbols() {
    /* unload library */
    if (lt_dlclose (__glpk_handle) != 0) return SYMBOL_UNLOAD_FAIL;

    /* exit */
    if (lt_dlexit() != 0) return SYMBOL_UNLOAD_FAIL;

    return SYMBOL_UNLOAD_SUCCESS;
}

