
#include <stdio.h>
#include "lazy_cplex.h"

/* C does not support bool, let's do it with macros */
#define bool int
#define true 1
#define false 0

int load_cplex_symbols() {
    int res;
    bool try_another;
    try_another = true;

    if (lt_dlinit () != 0) return SYMBOL_LOAD_FAIL;

    try_another = !(__cplex_handle = lt_dlopenext("libcplex"));
    if (try_another) try_another = !(__cplex_handle = lt_dlopenext("cplex"));
    if (try_another) return SYMBOL_LOAD_FAIL;

    res = SYMBOL_LOAD_SUCCESS;

    if (!(__symbolic_CPXcreateprob = lt_dlsym(__cplex_handle, "CPXcreateprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcloneprob = lt_dlsym(__cplex_handle, "CPXcloneprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopylpwnames = lt_dlsym(__cplex_handle, "CPXcopylpwnames"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopylp = lt_dlsym(__cplex_handle, "CPXcopylp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyobjname = lt_dlsym(__cplex_handle, "CPXcopyobjname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopybase = lt_dlsym(__cplex_handle, "CPXcopybase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcleanup = lt_dlsym(__cplex_handle, "CPXcleanup"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopystart = lt_dlsym(__cplex_handle, "CPXcopystart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfreeprob = lt_dlsym(__cplex_handle, "CPXfreeprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopynettolp = lt_dlsym(__cplex_handle, "CPXcopynettolp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETextract = lt_dlsym(__cplex_handle, "CPXNETextract"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXlpopt = lt_dlsym(__cplex_handle, "CPXlpopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXconcurrentlpopt = lt_dlsym(__cplex_handle, "CPXconcurrentlpopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXconcurrentmipopt = lt_dlsym(__cplex_handle, "CPXconcurrentmipopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXprimopt = lt_dlsym(__cplex_handle, "CPXprimopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdualopt = lt_dlsym(__cplex_handle, "CPXdualopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXhybnetopt = lt_dlsym(__cplex_handle, "CPXhybnetopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsiftopt = lt_dlsym(__cplex_handle, "CPXsiftopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpratio = lt_dlsym(__cplex_handle, "CPXpratio"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdratio = lt_dlsym(__cplex_handle, "CPXdratio"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpivot = lt_dlsym(__cplex_handle, "CPXpivot"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetphase2 = lt_dlsym(__cplex_handle, "CPXsetphase2"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckpfeas = lt_dlsym(__cplex_handle, "CPXcheckpfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckdfeas = lt_dlsym(__cplex_handle, "CPXcheckdfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchecksoln = lt_dlsym(__cplex_handle, "CPXchecksoln"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsolution = lt_dlsym(__cplex_handle, "CPXsolution"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsolninfo = lt_dlsym(__cplex_handle, "CPXsolninfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetstat = lt_dlsym(__cplex_handle, "CPXgetstat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetstatstring = lt_dlsym(__cplex_handle, "CPXgetstatstring"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmethod = lt_dlsym(__cplex_handle, "CPXgetmethod"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetobjval = lt_dlsym(__cplex_handle, "CPXgetobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetx = lt_dlsym(__cplex_handle, "CPXgetx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetax = lt_dlsym(__cplex_handle, "CPXgetax"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetpi = lt_dlsym(__cplex_handle, "CPXgetpi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetslack = lt_dlsym(__cplex_handle, "CPXgetslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrowinfeas = lt_dlsym(__cplex_handle, "CPXgetrowinfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcolinfeas = lt_dlsym(__cplex_handle, "CPXgetcolinfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdj = lt_dlsym(__cplex_handle, "CPXgetdj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetgrad = lt_dlsym(__cplex_handle, "CPXgetgrad"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetijdiv = lt_dlsym(__cplex_handle, "CPXgetijdiv"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbase = lt_dlsym(__cplex_handle, "CPXgetbase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetitcnt = lt_dlsym(__cplex_handle, "CPXgetitcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetphase1cnt = lt_dlsym(__cplex_handle, "CPXgetphase1cnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsiftitcnt = lt_dlsym(__cplex_handle, "CPXgetsiftitcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsiftphase1cnt = lt_dlsym(__cplex_handle, "CPXgetsiftphase1cnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbaritcnt = lt_dlsym(__cplex_handle, "CPXgetbaritcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcrossppushcnt = lt_dlsym(__cplex_handle, "CPXgetcrossppushcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcrosspexchcnt = lt_dlsym(__cplex_handle, "CPXgetcrosspexchcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcrossdpushcnt = lt_dlsym(__cplex_handle, "CPXgetcrossdpushcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcrossdexchcnt = lt_dlsym(__cplex_handle, "CPXgetcrossdexchcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetpsbcnt = lt_dlsym(__cplex_handle, "CPXgetpsbcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdsbcnt = lt_dlsym(__cplex_handle, "CPXgetdsbcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdblquality = lt_dlsym(__cplex_handle, "CPXgetdblquality"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpooldblquality = lt_dlsym(__cplex_handle, "CPXgetsolnpooldblquality"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetintquality = lt_dlsym(__cplex_handle, "CPXgetintquality"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolintquality = lt_dlsym(__cplex_handle, "CPXgetsolnpoolintquality"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrhssa = lt_dlsym(__cplex_handle, "CPXrhssa"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXboundsa = lt_dlsym(__cplex_handle, "CPXboundsa"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXobjsa = lt_dlsym(__cplex_handle, "CPXobjsa"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXErangesa = lt_dlsym(__cplex_handle, "CPXErangesa"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrefineconflict = lt_dlsym(__cplex_handle, "CPXrefineconflict"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetconflict = lt_dlsym(__cplex_handle, "CPXgetconflict"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrefineconflictext = lt_dlsym(__cplex_handle, "CPXrefineconflictext"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetconflictext = lt_dlsym(__cplex_handle, "CPXgetconflictext"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXclpwrite = lt_dlsym(__cplex_handle, "CPXclpwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrobustopt = lt_dlsym(__cplex_handle, "CPXrobustopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfeasopt = lt_dlsym(__cplex_handle, "CPXfeasopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEfeasopt = lt_dlsym(__cplex_handle, "CPXEfeasopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfeasoptext = lt_dlsym(__cplex_handle, "CPXfeasoptext"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXnewrows = lt_dlsym(__cplex_handle, "CPXnewrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddrows = lt_dlsym(__cplex_handle, "CPXaddrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXnewcols = lt_dlsym(__cplex_handle, "CPXnewcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddcols = lt_dlsym(__cplex_handle, "CPXaddcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelrows = lt_dlsym(__cplex_handle, "CPXdelrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetrows = lt_dlsym(__cplex_handle, "CPXdelsetrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelcols = lt_dlsym(__cplex_handle, "CPXdelcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetcols = lt_dlsym(__cplex_handle, "CPXdelsetcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgname = lt_dlsym(__cplex_handle, "CPXchgname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgrowname = lt_dlsym(__cplex_handle, "CPXchgrowname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgcolname = lt_dlsym(__cplex_handle, "CPXchgcolname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelnames = lt_dlsym(__cplex_handle, "CPXdelnames"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgprobname = lt_dlsym(__cplex_handle, "CPXchgprobname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgcoef = lt_dlsym(__cplex_handle, "CPXchgcoef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgcoeflist = lt_dlsym(__cplex_handle, "CPXchgcoeflist"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgbds = lt_dlsym(__cplex_handle, "CPXchgbds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgobj = lt_dlsym(__cplex_handle, "CPXchgobj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgrhs = lt_dlsym(__cplex_handle, "CPXchgrhs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgrngval = lt_dlsym(__cplex_handle, "CPXchgrngval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgsense = lt_dlsym(__cplex_handle, "CPXchgsense"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgobjsen = lt_dlsym(__cplex_handle, "CPXchgobjsen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgprobtype = lt_dlsym(__cplex_handle, "CPXchgprobtype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgprobtypesolnpool = lt_dlsym(__cplex_handle, "CPXchgprobtypesolnpool"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcompletelp = lt_dlsym(__cplex_handle, "CPXcompletelp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpreaddrows = lt_dlsym(__cplex_handle, "CPXpreaddrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXprechgobj = lt_dlsym(__cplex_handle, "CPXprechgobj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumcols = lt_dlsym(__cplex_handle, "CPXgetnumcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumrows = lt_dlsym(__cplex_handle, "CPXgetnumrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumnz = lt_dlsym(__cplex_handle, "CPXgetnumnz"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetobjsen = lt_dlsym(__cplex_handle, "CPXgetobjsen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetobj = lt_dlsym(__cplex_handle, "CPXgetobj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrhs = lt_dlsym(__cplex_handle, "CPXgetrhs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsense = lt_dlsym(__cplex_handle, "CPXgetsense"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcols = lt_dlsym(__cplex_handle, "CPXgetcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrows = lt_dlsym(__cplex_handle, "CPXgetrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetlb = lt_dlsym(__cplex_handle, "CPXgetlb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetub = lt_dlsym(__cplex_handle, "CPXgetub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrngval = lt_dlsym(__cplex_handle, "CPXgetrngval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetprobname = lt_dlsym(__cplex_handle, "CPXgetprobname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetobjname = lt_dlsym(__cplex_handle, "CPXgetobjname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcolname = lt_dlsym(__cplex_handle, "CPXgetcolname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrowname = lt_dlsym(__cplex_handle, "CPXgetrowname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcoef = lt_dlsym(__cplex_handle, "CPXgetcoef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetrowindex = lt_dlsym(__cplex_handle, "CPXgetrowindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcolindex = lt_dlsym(__cplex_handle, "CPXgetcolindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetprobtype = lt_dlsym(__cplex_handle, "CPXgetprobtype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopyprob = lt_dlsym(__cplex_handle, "CPXreadcopyprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopybase = lt_dlsym(__cplex_handle, "CPXreadcopybase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopysol = lt_dlsym(__cplex_handle, "CPXreadcopysol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXwriteprob = lt_dlsym(__cplex_handle, "CPXwriteprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmbasewrite = lt_dlsym(__cplex_handle, "CPXmbasewrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsolwrite = lt_dlsym(__cplex_handle, "CPXsolwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsolwritesolnpool = lt_dlsym(__cplex_handle, "CPXsolwritesolnpool"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsolwritesolnpoolall = lt_dlsym(__cplex_handle, "CPXsolwritesolnpoolall"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXembwrite = lt_dlsym(__cplex_handle, "CPXembwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdperwrite = lt_dlsym(__cplex_handle, "CPXdperwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpperwrite = lt_dlsym(__cplex_handle, "CPXpperwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpreslvwrite = lt_dlsym(__cplex_handle, "CPXpreslvwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdualwrite = lt_dlsym(__cplex_handle, "CPXdualwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetdefaults = lt_dlsym(__cplex_handle, "CPXsetdefaults"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetintparam = lt_dlsym(__cplex_handle, "CPXsetintparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetdblparam = lt_dlsym(__cplex_handle, "CPXsetdblparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetstrparam = lt_dlsym(__cplex_handle, "CPXsetstrparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetintparam = lt_dlsym(__cplex_handle, "CPXgetintparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdblparam = lt_dlsym(__cplex_handle, "CPXgetdblparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetstrparam = lt_dlsym(__cplex_handle, "CPXgetstrparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXinfointparam = lt_dlsym(__cplex_handle, "CPXinfointparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXinfodblparam = lt_dlsym(__cplex_handle, "CPXinfodblparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXinfostrparam = lt_dlsym(__cplex_handle, "CPXinfostrparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetparamname = lt_dlsym(__cplex_handle, "CPXgetparamname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetparamnum = lt_dlsym(__cplex_handle, "CPXgetparamnum"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetparamtype = lt_dlsym(__cplex_handle, "CPXgetparamtype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopyparam = lt_dlsym(__cplex_handle, "CPXreadcopyparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXwriteparam = lt_dlsym(__cplex_handle, "CPXwriteparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetchgparam = lt_dlsym(__cplex_handle, "CPXgetchgparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXtuneparam = lt_dlsym(__cplex_handle, "CPXtuneparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXtuneparamprobset = lt_dlsym(__cplex_handle, "CPXtuneparamprobset"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXversion = lt_dlsym(__cplex_handle, "CPXversion"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXopenCPLEX = lt_dlsym(__cplex_handle, "CPXopenCPLEX"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXopenCPLEXruntime = lt_dlsym(__cplex_handle, "CPXopenCPLEXruntime"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcloseCPLEX = lt_dlsym(__cplex_handle, "CPXcloseCPLEX"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXparenv = lt_dlsym(__cplex_handle, "CPXparenv"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfreeparenv = lt_dlsym(__cplex_handle, "CPXfreeparenv"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopylp = lt_dlsym(__cplex_handle, "CPXcheckcopylp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopylpwnames = lt_dlsym(__cplex_handle, "CPXcheckcopylpwnames"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckaddcols = lt_dlsym(__cplex_handle, "CPXcheckaddcols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckaddrows = lt_dlsym(__cplex_handle, "CPXcheckaddrows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckchgcoeflist = lt_dlsym(__cplex_handle, "CPXcheckchgcoeflist"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckvals = lt_dlsym(__cplex_handle, "CPXcheckvals"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetchannels = lt_dlsym(__cplex_handle, "CPXgetchannels"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetlogfile = lt_dlsym(__cplex_handle, "CPXsetlogfile"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetlogfile = lt_dlsym(__cplex_handle, "CPXgetlogfile"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmsg = lt_dlsym(__cplex_handle, "CPXmsg"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmsgstr = lt_dlsym(__cplex_handle, "CPXmsgstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXflushchannel = lt_dlsym(__cplex_handle, "CPXflushchannel"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXflushstdchannels = lt_dlsym(__cplex_handle, "CPXflushstdchannels"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddchannel = lt_dlsym(__cplex_handle, "CPXaddchannel"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddfpdest = lt_dlsym(__cplex_handle, "CPXaddfpdest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelfpdest = lt_dlsym(__cplex_handle, "CPXdelfpdest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddfuncdest = lt_dlsym(__cplex_handle, "CPXaddfuncdest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelfuncdest = lt_dlsym(__cplex_handle, "CPXdelfuncdest"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelchannel = lt_dlsym(__cplex_handle, "CPXdelchannel"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdisconnectchannel = lt_dlsym(__cplex_handle, "CPXdisconnectchannel"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgeterrorstring = lt_dlsym(__cplex_handle, "CPXgeterrorstring"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetlpcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetlpcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetnetcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetnetcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsettuningcallbackfunc = lt_dlsym(__cplex_handle, "CPXsettuningcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackinfo = lt_dlsym(__cplex_handle, "CPXgetcallbackinfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetlpcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetlpcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnetcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetnetcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgettuningcallbackfunc = lt_dlsym(__cplex_handle, "CPXgettuningcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetprofcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetprofcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfopen = lt_dlsym(__cplex_handle, "CPXfopen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfclose = lt_dlsym(__cplex_handle, "CPXfclose"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfputs = lt_dlsym(__cplex_handle, "CPXfputs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmalloc = lt_dlsym(__cplex_handle, "CPXmalloc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrealloc = lt_dlsym(__cplex_handle, "CPXrealloc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmemcpy = lt_dlsym(__cplex_handle, "CPXmemcpy"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfree = lt_dlsym(__cplex_handle, "CPXfree"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXstrlen = lt_dlsym(__cplex_handle, "CPXstrlen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXstrcpy = lt_dlsym(__cplex_handle, "CPXstrcpy"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXputenv = lt_dlsym(__cplex_handle, "CPXputenv"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEisort = lt_dlsym(__cplex_handle, "CPXEisort"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEinsort = lt_dlsym(__cplex_handle, "CPXEinsort"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetThreadNumber = lt_dlsym(__cplex_handle, "CPXEgetThreadNumber"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetmaxthreads = lt_dlsym(__cplex_handle, "CPXEgetmaxthreads"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEsetJNI = lt_dlsym(__cplex_handle, "CPXEsetJNI"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetJNI = lt_dlsym(__cplex_handle, "CPXEgetJNI"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEsetnamefunctions = lt_dlsym(__cplex_handle, "CPXEsetnamefunctions"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEsetnamedef = lt_dlsym(__cplex_handle, "CPXEsetnamedef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEdelnames = lt_dlsym(__cplex_handle, "CPXEdelnames"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetCache = lt_dlsym(__cplex_handle, "CPXEgetCache"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEcacheNewCols = lt_dlsym(__cplex_handle, "CPXEcacheNewCols"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEcacheNewRows = lt_dlsym(__cplex_handle, "CPXEcacheNewRows"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEcacheNewNZsByNZ = lt_dlsym(__cplex_handle, "CPXEcacheNewNZsByNZ"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetorigcolind = lt_dlsym(__cplex_handle, "CPXEgetorigcolind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetorigrowind = lt_dlsym(__cplex_handle, "CPXEgetorigrowind"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetbigreal = lt_dlsym(__cplex_handle, "CPXEgetbigreal"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEispromotion = lt_dlsym(__cplex_handle, "CPXEispromotion"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetnumrownz = lt_dlsym(__cplex_handle, "CPXEgetnumrownz"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEcangetbase = lt_dlsym(__cplex_handle, "CPXEcangetbase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEwriteparam = lt_dlsym(__cplex_handle, "CPXEwriteparam"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetterminate = lt_dlsym(__cplex_handle, "CPXsetterminate"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEsetterminatefunc = lt_dlsym(__cplex_handle, "CPXEsetterminatefunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEnsAddNames = lt_dlsym(__cplex_handle, "CPXEnsAddNames"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbhead = lt_dlsym(__cplex_handle, "CPXgetbhead"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbinvcol = lt_dlsym(__cplex_handle, "CPXbinvcol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbinvrow = lt_dlsym(__cplex_handle, "CPXbinvrow"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbinvacol = lt_dlsym(__cplex_handle, "CPXbinvacol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbinvarow = lt_dlsym(__cplex_handle, "CPXbinvarow"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXftran = lt_dlsym(__cplex_handle, "CPXftran"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbtran = lt_dlsym(__cplex_handle, "CPXbtran"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetijrow = lt_dlsym(__cplex_handle, "CPXgetijrow"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetray = lt_dlsym(__cplex_handle, "CPXgetray"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetweight = lt_dlsym(__cplex_handle, "CPXgetweight"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmdleave = lt_dlsym(__cplex_handle, "CPXmdleave"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXstrongbranch = lt_dlsym(__cplex_handle, "CPXstrongbranch"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdualfarkas = lt_dlsym(__cplex_handle, "CPXdualfarkas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetobjoffset = lt_dlsym(__cplex_handle, "CPXgetobjoffset"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopypartialbase = lt_dlsym(__cplex_handle, "CPXcopypartialbase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbasednorms = lt_dlsym(__cplex_handle, "CPXgetbasednorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopybasednorms = lt_dlsym(__cplex_handle, "CPXcopybasednorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdnorms = lt_dlsym(__cplex_handle, "CPXgetdnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopydnorms = lt_dlsym(__cplex_handle, "CPXcopydnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXkilldnorms = lt_dlsym(__cplex_handle, "CPXkilldnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetpnorms = lt_dlsym(__cplex_handle, "CPXgetpnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopypnorms = lt_dlsym(__cplex_handle, "CPXcopypnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXkillpnorms = lt_dlsym(__cplex_handle, "CPXkillpnorms"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpivotin = lt_dlsym(__cplex_handle, "CPXpivotin"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpivotout = lt_dlsym(__cplex_handle, "CPXpivotout"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXunscaleprob = lt_dlsym(__cplex_handle, "CPXunscaleprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXtightenbds = lt_dlsym(__cplex_handle, "CPXtightenbds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpresolve = lt_dlsym(__cplex_handle, "CPXpresolve"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbasicpresolve = lt_dlsym(__cplex_handle, "CPXbasicpresolve"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXslackfromx = lt_dlsym(__cplex_handle, "CPXslackfromx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdjfrompi = lt_dlsym(__cplex_handle, "CPXdjfrompi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXqpdjfrompi = lt_dlsym(__cplex_handle, "CPXqpdjfrompi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfreepresolve = lt_dlsym(__cplex_handle, "CPXfreepresolve"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetredlp = lt_dlsym(__cplex_handle, "CPXgetredlp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcrushx = lt_dlsym(__cplex_handle, "CPXcrushx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXuncrushx = lt_dlsym(__cplex_handle, "CPXuncrushx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcrushpi = lt_dlsym(__cplex_handle, "CPXcrushpi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXuncrushpi = lt_dlsym(__cplex_handle, "CPXuncrushpi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXqpuncrushpi = lt_dlsym(__cplex_handle, "CPXqpuncrushpi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcrushform = lt_dlsym(__cplex_handle, "CPXcrushform"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXuncrushform = lt_dlsym(__cplex_handle, "CPXuncrushform"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetprestat = lt_dlsym(__cplex_handle, "CPXgetprestat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyprotected = lt_dlsym(__cplex_handle, "CPXcopyprotected"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetprotected = lt_dlsym(__cplex_handle, "CPXgetprotected"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaggregatevars = lt_dlsym(__cplex_handle, "CPXEaggregatevars"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgettime = lt_dlsym(__cplex_handle, "CPXgettime"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXlpwrite = lt_dlsym(__cplex_handle, "CPXlpwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXlprewrite = lt_dlsym(__cplex_handle, "CPXlprewrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmpswrite = lt_dlsym(__cplex_handle, "CPXmpswrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmpsrewrite = lt_dlsym(__cplex_handle, "CPXmpsrewrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsavwrite = lt_dlsym(__cplex_handle, "CPXsavwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopyvec = lt_dlsym(__cplex_handle, "CPXreadcopyvec"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXvecwrite = lt_dlsym(__cplex_handle, "CPXvecwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbinsolwrite = lt_dlsym(__cplex_handle, "CPXbinsolwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXtxtsolwrite = lt_dlsym(__cplex_handle, "CPXtxtsolwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXwritesol = lt_dlsym(__cplex_handle, "CPXwritesol"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetiis = lt_dlsym(__cplex_handle, "CPXgetiis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfindiis = lt_dlsym(__cplex_handle, "CPXfindiis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdisplayiis = lt_dlsym(__cplex_handle, "CPXdisplayiis"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXiiswrite = lt_dlsym(__cplex_handle, "CPXiiswrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXhybbaropt = lt_dlsym(__cplex_handle, "CPXhybbaropt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbaropt = lt_dlsym(__cplex_handle, "CPXbaropt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgeneric_lock = lt_dlsym(__cplex_handle, "CPXEgeneric_lock"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgeneric_unlock = lt_dlsym(__cplex_handle, "CPXEgeneric_unlock"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetorderhookfunc = lt_dlsym(__cplex_handle, "CPXsetorderhookfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetorderhookfunc = lt_dlsym(__cplex_handle, "CPXgetorderhookfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyctype = lt_dlsym(__cplex_handle, "CPXcopyctype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyorder = lt_dlsym(__cplex_handle, "CPXcopyorder"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopysos = lt_dlsym(__cplex_handle, "CPXcopysos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopymipstart = lt_dlsym(__cplex_handle, "CPXcopymipstart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgmipstart = lt_dlsym(__cplex_handle, "CPXchgmipstart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgmipstarts = lt_dlsym(__cplex_handle, "CPXchgmipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddmipstarts = lt_dlsym(__cplex_handle, "CPXaddmipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelmipstarts = lt_dlsym(__cplex_handle, "CPXdelmipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetmipstarts = lt_dlsym(__cplex_handle, "CPXdelsetmipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrefinemipstartconflict = lt_dlsym(__cplex_handle, "CPXrefinemipstartconflict"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXrefinemipstartconflictext = lt_dlsym(__cplex_handle, "CPXrefinemipstartconflictext"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmipopt = lt_dlsym(__cplex_handle, "CPXmipopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipitcnt = lt_dlsym(__cplex_handle, "CPXgetmipitcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbestobjval = lt_dlsym(__cplex_handle, "CPXgetbestobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmiprelgap = lt_dlsym(__cplex_handle, "CPXgetmiprelgap"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcutoff = lt_dlsym(__cplex_handle, "CPXgetcutoff"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnodecnt = lt_dlsym(__cplex_handle, "CPXgetnodecnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnodeleftcnt = lt_dlsym(__cplex_handle, "CPXgetnodeleftcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnodeint = lt_dlsym(__cplex_handle, "CPXgetnodeint"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumcuts = lt_dlsym(__cplex_handle, "CPXgetnumcuts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnummipstarts = lt_dlsym(__cplex_handle, "CPXgetnummipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipstart = lt_dlsym(__cplex_handle, "CPXgetmipstart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipstarts = lt_dlsym(__cplex_handle, "CPXgetmipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipstartname = lt_dlsym(__cplex_handle, "CPXgetmipstartname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipstartindex = lt_dlsym(__cplex_handle, "CPXgetmipstartindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolmipstart = lt_dlsym(__cplex_handle, "CPXgetsolnpoolmipstart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolnummipstarts = lt_dlsym(__cplex_handle, "CPXgetsolnpoolnummipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsubstat = lt_dlsym(__cplex_handle, "CPXgetsubstat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsubmethod = lt_dlsym(__cplex_handle, "CPXgetsubmethod"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgctype = lt_dlsym(__cplex_handle, "CPXchgctype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddsos = lt_dlsym(__cplex_handle, "CPXaddsos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetsos = lt_dlsym(__cplex_handle, "CPXdelsetsos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetctype = lt_dlsym(__cplex_handle, "CPXgetctype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumsos = lt_dlsym(__cplex_handle, "CPXgetnumsos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsos = lt_dlsym(__cplex_handle, "CPXgetsos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsosname = lt_dlsym(__cplex_handle, "CPXgetsosname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsosindex = lt_dlsym(__cplex_handle, "CPXgetsosindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsosinfeas = lt_dlsym(__cplex_handle, "CPXgetsosinfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumindconstrs = lt_dlsym(__cplex_handle, "CPXgetnumindconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetindconstr = lt_dlsym(__cplex_handle, "CPXgetindconstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetindicator = lt_dlsym(__cplex_handle, "CPXEgetindicator"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetindconstrindex = lt_dlsym(__cplex_handle, "CPXgetindconstrindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetindconstrname = lt_dlsym(__cplex_handle, "CPXgetindconstrname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetindconstrslack = lt_dlsym(__cplex_handle, "CPXgetindconstrslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXindconstrslackfromx = lt_dlsym(__cplex_handle, "CPXindconstrslackfromx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetindconstrinfeas = lt_dlsym(__cplex_handle, "CPXgetindconstrinfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelindconstrs = lt_dlsym(__cplex_handle, "CPXdelindconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumint = lt_dlsym(__cplex_handle, "CPXgetnumint"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumbin = lt_dlsym(__cplex_handle, "CPXgetnumbin"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumsemicont = lt_dlsym(__cplex_handle, "CPXgetnumsemicont"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumsemiint = lt_dlsym(__cplex_handle, "CPXgetnumsemiint"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetorder = lt_dlsym(__cplex_handle, "CPXgetorder"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXpopulate = lt_dlsym(__cplex_handle, "CPXpopulate"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolnumfilters = lt_dlsym(__cplex_handle, "CPXgetsolnpoolnumfilters"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddsolnpooldivfilter = lt_dlsym(__cplex_handle, "CPXaddsolnpooldivfilter"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddsolnpoolrngfilter = lt_dlsym(__cplex_handle, "CPXaddsolnpoolrngfilter"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolfiltertype = lt_dlsym(__cplex_handle, "CPXgetsolnpoolfiltertype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpooldivfilter = lt_dlsym(__cplex_handle, "CPXgetsolnpooldivfilter"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolfilter = lt_dlsym(__cplex_handle, "CPXgetsolnpoolfilter"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolrngfilter = lt_dlsym(__cplex_handle, "CPXgetsolnpoolrngfilter"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolfiltername = lt_dlsym(__cplex_handle, "CPXgetsolnpoolfiltername"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolfilterindex = lt_dlsym(__cplex_handle, "CPXgetsolnpoolfilterindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsolnpoolfilters = lt_dlsym(__cplex_handle, "CPXdelsolnpoolfilters"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetsolnpoolfilters = lt_dlsym(__cplex_handle, "CPXdelsetsolnpoolfilters"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolnumsolns = lt_dlsym(__cplex_handle, "CPXgetsolnpoolnumsolns"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolnumreplaced = lt_dlsym(__cplex_handle, "CPXgetsolnpoolnumreplaced"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolmeanobjval = lt_dlsym(__cplex_handle, "CPXgetsolnpoolmeanobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolobjval = lt_dlsym(__cplex_handle, "CPXgetsolnpoolobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolx = lt_dlsym(__cplex_handle, "CPXgetsolnpoolx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolslack = lt_dlsym(__cplex_handle, "CPXgetsolnpoolslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolqconstrslack = lt_dlsym(__cplex_handle, "CPXgetsolnpoolqconstrslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolsolnname = lt_dlsym(__cplex_handle, "CPXgetsolnpoolsolnname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolnpoolsolnindex = lt_dlsym(__cplex_handle, "CPXgetsolnpoolsolnindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsolnpoolsolns = lt_dlsym(__cplex_handle, "CPXdelsolnpoolsolns"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelsetsolnpoolsolns = lt_dlsym(__cplex_handle, "CPXdelsetsolnpoolsolns"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopyorder = lt_dlsym(__cplex_handle, "CPXreadcopyorder"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopysolnpoolfilters = lt_dlsym(__cplex_handle, "CPXreadcopysolnpoolfilters"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopymipstart = lt_dlsym(__cplex_handle, "CPXreadcopymipstart"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXreadcopymipstarts = lt_dlsym(__cplex_handle, "CPXreadcopymipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXordwrite = lt_dlsym(__cplex_handle, "CPXordwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmstwrite = lt_dlsym(__cplex_handle, "CPXmstwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXwritemipstarts = lt_dlsym(__cplex_handle, "CPXwritemipstarts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmstwritesolnpool = lt_dlsym(__cplex_handle, "CPXmstwritesolnpool"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXmstwritesolnpoolall = lt_dlsym(__cplex_handle, "CPXmstwritesolnpoolall"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfltwrite = lt_dlsym(__cplex_handle, "CPXfltwrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopyctype = lt_dlsym(__cplex_handle, "CPXcheckcopyctype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopysos = lt_dlsym(__cplex_handle, "CPXcheckcopysos"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEchgsosname = lt_dlsym(__cplex_handle, "CPXEchgsosname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetinfocallbackfunc = lt_dlsym(__cplex_handle, "CPXsetinfocallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetinfocallbackfunc = lt_dlsym(__cplex_handle, "CPXgetinfocallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetmipcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetmipcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetmipcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetmipcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetbranchcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetbranchcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetbranchnosolncallbackfunc = lt_dlsym(__cplex_handle, "CPXsetbranchnosolncallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetcutcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetcutcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetnodecallbackfunc = lt_dlsym(__cplex_handle, "CPXsetnodecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetheuristiccallbackfunc = lt_dlsym(__cplex_handle, "CPXsetheuristiccallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetincumbentcallbackfunc = lt_dlsym(__cplex_handle, "CPXsetincumbentcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetsolvecallbackfunc = lt_dlsym(__cplex_handle, "CPXsetsolvecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXsetdeletenodecallbackfunc = lt_dlsym(__cplex_handle, "CPXsetdeletenodecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbranchcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetbranchcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetbranchnosolncallbackfunc = lt_dlsym(__cplex_handle, "CPXgetbranchnosolncallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcutcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetcutcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnodecallbackfunc = lt_dlsym(__cplex_handle, "CPXgetnodecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetheuristiccallbackfunc = lt_dlsym(__cplex_handle, "CPXgetheuristiccallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetincumbentcallbackfunc = lt_dlsym(__cplex_handle, "CPXgetincumbentcallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetsolvecallbackfunc = lt_dlsym(__cplex_handle, "CPXgetsolvecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetdeletenodecallbackfunc = lt_dlsym(__cplex_handle, "CPXgetdeletenodecallbackfunc"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodelp = lt_dlsym(__cplex_handle, "CPXgetcallbacknodelp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodeinfo = lt_dlsym(__cplex_handle, "CPXgetcallbacknodeinfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackseqinfo = lt_dlsym(__cplex_handle, "CPXgetcallbackseqinfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacksosinfo = lt_dlsym(__cplex_handle, "CPXgetcallbacksosinfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackindicatorinfo = lt_dlsym(__cplex_handle, "CPXgetcallbackindicatorinfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcutcallbackadd = lt_dlsym(__cplex_handle, "CPXcutcallbackadd"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcutcallbackaddlocal = lt_dlsym(__cplex_handle, "CPXcutcallbackaddlocal"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbranchcallbackbranchbds = lt_dlsym(__cplex_handle, "CPXbranchcallbackbranchbds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbranchcallbackbranchgeneral = lt_dlsym(__cplex_handle, "CPXbranchcallbackbranchgeneral"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXbranchcallbackbranchconstraints = lt_dlsym(__cplex_handle, "CPXbranchcallbackbranchconstraints"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodex = lt_dlsym(__cplex_handle, "CPXgetcallbacknodex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodeobjval = lt_dlsym(__cplex_handle, "CPXgetcallbacknodeobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackctype = lt_dlsym(__cplex_handle, "CPXgetcallbackctype"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackorder = lt_dlsym(__cplex_handle, "CPXgetcallbackorder"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackpseudocosts = lt_dlsym(__cplex_handle, "CPXgetcallbackpseudocosts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackincumbent = lt_dlsym(__cplex_handle, "CPXgetcallbackincumbent"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodeintfeas = lt_dlsym(__cplex_handle, "CPXgetcallbacknodeintfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackgloballb = lt_dlsym(__cplex_handle, "CPXgetcallbackgloballb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackglobalub = lt_dlsym(__cplex_handle, "CPXgetcallbackglobalub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodelb = lt_dlsym(__cplex_handle, "CPXgetcallbacknodelb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodeub = lt_dlsym(__cplex_handle, "CPXgetcallbacknodeub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacklp = lt_dlsym(__cplex_handle, "CPXgetcallbacklp"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbacknodestat = lt_dlsym(__cplex_handle, "CPXgetcallbacknodestat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetcallbackbranchconstraints = lt_dlsym(__cplex_handle, "CPXgetcallbackbranchconstraints"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddusercuts = lt_dlsym(__cplex_handle, "CPXaddusercuts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddlazyconstraints = lt_dlsym(__cplex_handle, "CPXaddlazyconstraints"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfreeusercuts = lt_dlsym(__cplex_handle, "CPXfreeusercuts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXfreelazyconstraints = lt_dlsym(__cplex_handle, "CPXfreelazyconstraints"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetusercuts = lt_dlsym(__cplex_handle, "CPXEgetusercuts"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetusercutname = lt_dlsym(__cplex_handle, "CPXEgetusercutname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetlazyconstraints = lt_dlsym(__cplex_handle, "CPXEgetlazyconstraints"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetlazyconstraintname = lt_dlsym(__cplex_handle, "CPXEgetlazyconstraintname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXordread = lt_dlsym(__cplex_handle, "CPXordread"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddindconstr = lt_dlsym(__cplex_handle, "CPXaddindconstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetnumgconstrs = lt_dlsym(__cplex_handle, "CPXEgetnumgconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEdelgconstrs = lt_dlsym(__cplex_handle, "CPXEdelgconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddindconstr = lt_dlsym(__cplex_handle, "CPXEaddindconstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddminexpr = lt_dlsym(__cplex_handle, "CPXEaddminexpr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddmaxexpr = lt_dlsym(__cplex_handle, "CPXEaddmaxexpr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddpwl = lt_dlsym(__cplex_handle, "CPXEaddpwl"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddabs = lt_dlsym(__cplex_handle, "CPXEaddabs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvar = lt_dlsym(__cplex_handle, "CPXEaddsetvar"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEchgsetvar = lt_dlsym(__cplex_handle, "CPXEchgsetvar"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEgetsetvarvalues = lt_dlsym(__cplex_handle, "CPXEgetsetvarvalues"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarmember = lt_dlsym(__cplex_handle, "CPXEaddsetvarmember"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarcard = lt_dlsym(__cplex_handle, "CPXEaddsetvarcard"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarsum = lt_dlsym(__cplex_handle, "CPXEaddsetvarsum"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarmin = lt_dlsym(__cplex_handle, "CPXEaddsetvarmin"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarmax = lt_dlsym(__cplex_handle, "CPXEaddsetvarmax"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarsubset = lt_dlsym(__cplex_handle, "CPXEaddsetvarsubset"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvardomain = lt_dlsym(__cplex_handle, "CPXEaddsetvardomain"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarunion = lt_dlsym(__cplex_handle, "CPXEaddsetvarunion"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarintersection = lt_dlsym(__cplex_handle, "CPXEaddsetvarintersection"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarnullintersect = lt_dlsym(__cplex_handle, "CPXEaddsetvarnullintersect"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarintersect = lt_dlsym(__cplex_handle, "CPXEaddsetvarintersect"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvareq = lt_dlsym(__cplex_handle, "CPXEaddsetvareq"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarneq = lt_dlsym(__cplex_handle, "CPXEaddsetvarneq"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEaddsetvarneqcst = lt_dlsym(__cplex_handle, "CPXEaddsetvarneqcst"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETcreateprob = lt_dlsym(__cplex_handle, "CPXNETcreateprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETfreeprob = lt_dlsym(__cplex_handle, "CPXNETfreeprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETcopynet = lt_dlsym(__cplex_handle, "CPXNETcopynet"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETcopybase = lt_dlsym(__cplex_handle, "CPXNETcopybase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETaddnodes = lt_dlsym(__cplex_handle, "CPXNETaddnodes"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETaddarcs = lt_dlsym(__cplex_handle, "CPXNETaddarcs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETdelnodes = lt_dlsym(__cplex_handle, "CPXNETdelnodes"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETdelarcs = lt_dlsym(__cplex_handle, "CPXNETdelarcs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETdelset = lt_dlsym(__cplex_handle, "CPXNETdelset"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETprimopt = lt_dlsym(__cplex_handle, "CPXNETprimopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetstat = lt_dlsym(__cplex_handle, "CPXNETgetstat"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetobjval = lt_dlsym(__cplex_handle, "CPXNETgetobjval"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetx = lt_dlsym(__cplex_handle, "CPXNETgetx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetpi = lt_dlsym(__cplex_handle, "CPXNETgetpi"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetslack = lt_dlsym(__cplex_handle, "CPXNETgetslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetdj = lt_dlsym(__cplex_handle, "CPXNETgetdj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetitcnt = lt_dlsym(__cplex_handle, "CPXNETgetitcnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetphase1cnt = lt_dlsym(__cplex_handle, "CPXNETgetphase1cnt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetbase = lt_dlsym(__cplex_handle, "CPXNETgetbase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETsolution = lt_dlsym(__cplex_handle, "CPXNETsolution"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETsolninfo = lt_dlsym(__cplex_handle, "CPXNETsolninfo"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgname = lt_dlsym(__cplex_handle, "CPXNETchgname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgarcname = lt_dlsym(__cplex_handle, "CPXNETchgarcname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgnodename = lt_dlsym(__cplex_handle, "CPXNETchgnodename"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgobjsen = lt_dlsym(__cplex_handle, "CPXNETchgobjsen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgbds = lt_dlsym(__cplex_handle, "CPXNETchgbds"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgarcnodes = lt_dlsym(__cplex_handle, "CPXNETchgarcnodes"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgobj = lt_dlsym(__cplex_handle, "CPXNETchgobj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETchgsupply = lt_dlsym(__cplex_handle, "CPXNETchgsupply"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetobjsen = lt_dlsym(__cplex_handle, "CPXNETgetobjsen"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetsupply = lt_dlsym(__cplex_handle, "CPXNETgetsupply"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetprobname = lt_dlsym(__cplex_handle, "CPXNETgetprobname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetnodename = lt_dlsym(__cplex_handle, "CPXNETgetnodename"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetarcname = lt_dlsym(__cplex_handle, "CPXNETgetarcname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetlb = lt_dlsym(__cplex_handle, "CPXNETgetlb"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetub = lt_dlsym(__cplex_handle, "CPXNETgetub"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetobj = lt_dlsym(__cplex_handle, "CPXNETgetobj"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetarcnodes = lt_dlsym(__cplex_handle, "CPXNETgetarcnodes"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetnodearcs = lt_dlsym(__cplex_handle, "CPXNETgetnodearcs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetnumnodes = lt_dlsym(__cplex_handle, "CPXNETgetnumnodes"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetnumarcs = lt_dlsym(__cplex_handle, "CPXNETgetnumarcs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetnodeindex = lt_dlsym(__cplex_handle, "CPXNETgetnodeindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETgetarcindex = lt_dlsym(__cplex_handle, "CPXNETgetarcindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETreadcopyprob = lt_dlsym(__cplex_handle, "CPXNETreadcopyprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETreadcopybase = lt_dlsym(__cplex_handle, "CPXNETreadcopybase"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETwriteprob = lt_dlsym(__cplex_handle, "CPXNETwriteprob"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETbasewrite = lt_dlsym(__cplex_handle, "CPXNETbasewrite"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXNETcheckcopynet = lt_dlsym(__cplex_handle, "CPXNETcheckcopynet"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyquad = lt_dlsym(__cplex_handle, "CPXcopyquad"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcopyqpsep = lt_dlsym(__cplex_handle, "CPXcopyqpsep"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXchgqpcoef = lt_dlsym(__cplex_handle, "CPXchgqpcoef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumqpnz = lt_dlsym(__cplex_handle, "CPXgetnumqpnz"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumquad = lt_dlsym(__cplex_handle, "CPXgetnumquad"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqpcoef = lt_dlsym(__cplex_handle, "CPXgetqpcoef"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetquad = lt_dlsym(__cplex_handle, "CPXgetquad"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXqpindefcertificate = lt_dlsym(__cplex_handle, "CPXqpindefcertificate"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopyqpsep = lt_dlsym(__cplex_handle, "CPXcheckcopyqpsep"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXcheckcopyquad = lt_dlsym(__cplex_handle, "CPXcheckcopyquad"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXqpopt = lt_dlsym(__cplex_handle, "CPXqpopt"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXaddqconstr = lt_dlsym(__cplex_handle, "CPXaddqconstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXdelqconstrs = lt_dlsym(__cplex_handle, "CPXdelqconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetnumqconstrs = lt_dlsym(__cplex_handle, "CPXgetnumqconstrs"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqconstrindex = lt_dlsym(__cplex_handle, "CPXgetqconstrindex"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqconstr = lt_dlsym(__cplex_handle, "CPXgetqconstr"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqconstrname = lt_dlsym(__cplex_handle, "CPXgetqconstrname"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqconstrslack = lt_dlsym(__cplex_handle, "CPXgetqconstrslack"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXqconstrslackfromx = lt_dlsym(__cplex_handle, "CPXqconstrslackfromx"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetqconstrinfeas = lt_dlsym(__cplex_handle, "CPXgetqconstrinfeas"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXgetxqxax = lt_dlsym(__cplex_handle, "CPXgetxqxax"))) res = SYMBOL_MISSING;
    if (!(__symbolic_CPXEchgqcname = lt_dlsym(__cplex_handle, "CPXEchgqcname"))) res = SYMBOL_MISSING;

    return res;
}

void print_cplex_missing_symbols() {

    if (!__symbolic_CPXcreateprob) printf("CPXcreateprob\n");
    if (!__symbolic_CPXcloneprob) printf("CPXcloneprob\n");
    if (!__symbolic_CPXcopylpwnames) printf("CPXcopylpwnames\n");
    if (!__symbolic_CPXcopylp) printf("CPXcopylp\n");
    if (!__symbolic_CPXcopyobjname) printf("CPXcopyobjname\n");
    if (!__symbolic_CPXcopybase) printf("CPXcopybase\n");
    if (!__symbolic_CPXcleanup) printf("CPXcleanup\n");
    if (!__symbolic_CPXcopystart) printf("CPXcopystart\n");
    if (!__symbolic_CPXfreeprob) printf("CPXfreeprob\n");
    if (!__symbolic_CPXcopynettolp) printf("CPXcopynettolp\n");
    if (!__symbolic_CPXNETextract) printf("CPXNETextract\n");
    if (!__symbolic_CPXlpopt) printf("CPXlpopt\n");
    if (!__symbolic_CPXconcurrentlpopt) printf("CPXconcurrentlpopt\n");
    if (!__symbolic_CPXconcurrentmipopt) printf("CPXconcurrentmipopt\n");
    if (!__symbolic_CPXprimopt) printf("CPXprimopt\n");
    if (!__symbolic_CPXdualopt) printf("CPXdualopt\n");
    if (!__symbolic_CPXhybnetopt) printf("CPXhybnetopt\n");
    if (!__symbolic_CPXsiftopt) printf("CPXsiftopt\n");
    if (!__symbolic_CPXpratio) printf("CPXpratio\n");
    if (!__symbolic_CPXdratio) printf("CPXdratio\n");
    if (!__symbolic_CPXpivot) printf("CPXpivot\n");
    if (!__symbolic_CPXsetphase2) printf("CPXsetphase2\n");
    if (!__symbolic_CPXcheckpfeas) printf("CPXcheckpfeas\n");
    if (!__symbolic_CPXcheckdfeas) printf("CPXcheckdfeas\n");
    if (!__symbolic_CPXchecksoln) printf("CPXchecksoln\n");
    if (!__symbolic_CPXsolution) printf("CPXsolution\n");
    if (!__symbolic_CPXsolninfo) printf("CPXsolninfo\n");
    if (!__symbolic_CPXgetstat) printf("CPXgetstat\n");
    if (!__symbolic_CPXgetstatstring) printf("CPXgetstatstring\n");
    if (!__symbolic_CPXgetmethod) printf("CPXgetmethod\n");
    if (!__symbolic_CPXgetobjval) printf("CPXgetobjval\n");
    if (!__symbolic_CPXgetx) printf("CPXgetx\n");
    if (!__symbolic_CPXgetax) printf("CPXgetax\n");
    if (!__symbolic_CPXgetpi) printf("CPXgetpi\n");
    if (!__symbolic_CPXgetslack) printf("CPXgetslack\n");
    if (!__symbolic_CPXgetrowinfeas) printf("CPXgetrowinfeas\n");
    if (!__symbolic_CPXgetcolinfeas) printf("CPXgetcolinfeas\n");
    if (!__symbolic_CPXgetdj) printf("CPXgetdj\n");
    if (!__symbolic_CPXgetgrad) printf("CPXgetgrad\n");
    if (!__symbolic_CPXgetijdiv) printf("CPXgetijdiv\n");
    if (!__symbolic_CPXgetbase) printf("CPXgetbase\n");
    if (!__symbolic_CPXgetitcnt) printf("CPXgetitcnt\n");
    if (!__symbolic_CPXgetphase1cnt) printf("CPXgetphase1cnt\n");
    if (!__symbolic_CPXgetsiftitcnt) printf("CPXgetsiftitcnt\n");
    if (!__symbolic_CPXgetsiftphase1cnt) printf("CPXgetsiftphase1cnt\n");
    if (!__symbolic_CPXgetbaritcnt) printf("CPXgetbaritcnt\n");
    if (!__symbolic_CPXgetcrossppushcnt) printf("CPXgetcrossppushcnt\n");
    if (!__symbolic_CPXgetcrosspexchcnt) printf("CPXgetcrosspexchcnt\n");
    if (!__symbolic_CPXgetcrossdpushcnt) printf("CPXgetcrossdpushcnt\n");
    if (!__symbolic_CPXgetcrossdexchcnt) printf("CPXgetcrossdexchcnt\n");
    if (!__symbolic_CPXgetpsbcnt) printf("CPXgetpsbcnt\n");
    if (!__symbolic_CPXgetdsbcnt) printf("CPXgetdsbcnt\n");
    if (!__symbolic_CPXgetdblquality) printf("CPXgetdblquality\n");
    if (!__symbolic_CPXgetsolnpooldblquality) printf("CPXgetsolnpooldblquality\n");
    if (!__symbolic_CPXgetintquality) printf("CPXgetintquality\n");
    if (!__symbolic_CPXgetsolnpoolintquality) printf("CPXgetsolnpoolintquality\n");
    if (!__symbolic_CPXrhssa) printf("CPXrhssa\n");
    if (!__symbolic_CPXboundsa) printf("CPXboundsa\n");
    if (!__symbolic_CPXobjsa) printf("CPXobjsa\n");
    if (!__symbolic_CPXErangesa) printf("CPXErangesa\n");
    if (!__symbolic_CPXrefineconflict) printf("CPXrefineconflict\n");
    if (!__symbolic_CPXgetconflict) printf("CPXgetconflict\n");
    if (!__symbolic_CPXrefineconflictext) printf("CPXrefineconflictext\n");
    if (!__symbolic_CPXgetconflictext) printf("CPXgetconflictext\n");
    if (!__symbolic_CPXclpwrite) printf("CPXclpwrite\n");
    if (!__symbolic_CPXrobustopt) printf("CPXrobustopt\n");
    if (!__symbolic_CPXfeasopt) printf("CPXfeasopt\n");
    if (!__symbolic_CPXEfeasopt) printf("CPXEfeasopt\n");
    if (!__symbolic_CPXfeasoptext) printf("CPXfeasoptext\n");
    if (!__symbolic_CPXnewrows) printf("CPXnewrows\n");
    if (!__symbolic_CPXaddrows) printf("CPXaddrows\n");
    if (!__symbolic_CPXnewcols) printf("CPXnewcols\n");
    if (!__symbolic_CPXaddcols) printf("CPXaddcols\n");
    if (!__symbolic_CPXdelrows) printf("CPXdelrows\n");
    if (!__symbolic_CPXdelsetrows) printf("CPXdelsetrows\n");
    if (!__symbolic_CPXdelcols) printf("CPXdelcols\n");
    if (!__symbolic_CPXdelsetcols) printf("CPXdelsetcols\n");
    if (!__symbolic_CPXchgname) printf("CPXchgname\n");
    if (!__symbolic_CPXchgrowname) printf("CPXchgrowname\n");
    if (!__symbolic_CPXchgcolname) printf("CPXchgcolname\n");
    if (!__symbolic_CPXdelnames) printf("CPXdelnames\n");
    if (!__symbolic_CPXchgprobname) printf("CPXchgprobname\n");
    if (!__symbolic_CPXchgcoef) printf("CPXchgcoef\n");
    if (!__symbolic_CPXchgcoeflist) printf("CPXchgcoeflist\n");
    if (!__symbolic_CPXchgbds) printf("CPXchgbds\n");
    if (!__symbolic_CPXchgobj) printf("CPXchgobj\n");
    if (!__symbolic_CPXchgrhs) printf("CPXchgrhs\n");
    if (!__symbolic_CPXchgrngval) printf("CPXchgrngval\n");
    if (!__symbolic_CPXchgsense) printf("CPXchgsense\n");
    if (!__symbolic_CPXchgobjsen) printf("CPXchgobjsen\n");
    if (!__symbolic_CPXchgprobtype) printf("CPXchgprobtype\n");
    if (!__symbolic_CPXchgprobtypesolnpool) printf("CPXchgprobtypesolnpool\n");
    if (!__symbolic_CPXcompletelp) printf("CPXcompletelp\n");
    if (!__symbolic_CPXpreaddrows) printf("CPXpreaddrows\n");
    if (!__symbolic_CPXprechgobj) printf("CPXprechgobj\n");
    if (!__symbolic_CPXgetnumcols) printf("CPXgetnumcols\n");
    if (!__symbolic_CPXgetnumrows) printf("CPXgetnumrows\n");
    if (!__symbolic_CPXgetnumnz) printf("CPXgetnumnz\n");
    if (!__symbolic_CPXgetobjsen) printf("CPXgetobjsen\n");
    if (!__symbolic_CPXgetobj) printf("CPXgetobj\n");
    if (!__symbolic_CPXgetrhs) printf("CPXgetrhs\n");
    if (!__symbolic_CPXgetsense) printf("CPXgetsense\n");
    if (!__symbolic_CPXgetcols) printf("CPXgetcols\n");
    if (!__symbolic_CPXgetrows) printf("CPXgetrows\n");
    if (!__symbolic_CPXgetlb) printf("CPXgetlb\n");
    if (!__symbolic_CPXgetub) printf("CPXgetub\n");
    if (!__symbolic_CPXgetrngval) printf("CPXgetrngval\n");
    if (!__symbolic_CPXgetprobname) printf("CPXgetprobname\n");
    if (!__symbolic_CPXgetobjname) printf("CPXgetobjname\n");
    if (!__symbolic_CPXgetcolname) printf("CPXgetcolname\n");
    if (!__symbolic_CPXgetrowname) printf("CPXgetrowname\n");
    if (!__symbolic_CPXgetcoef) printf("CPXgetcoef\n");
    if (!__symbolic_CPXgetrowindex) printf("CPXgetrowindex\n");
    if (!__symbolic_CPXgetcolindex) printf("CPXgetcolindex\n");
    if (!__symbolic_CPXgetprobtype) printf("CPXgetprobtype\n");
    if (!__symbolic_CPXreadcopyprob) printf("CPXreadcopyprob\n");
    if (!__symbolic_CPXreadcopybase) printf("CPXreadcopybase\n");
    if (!__symbolic_CPXreadcopysol) printf("CPXreadcopysol\n");
    if (!__symbolic_CPXwriteprob) printf("CPXwriteprob\n");
    if (!__symbolic_CPXmbasewrite) printf("CPXmbasewrite\n");
    if (!__symbolic_CPXsolwrite) printf("CPXsolwrite\n");
    if (!__symbolic_CPXsolwritesolnpool) printf("CPXsolwritesolnpool\n");
    if (!__symbolic_CPXsolwritesolnpoolall) printf("CPXsolwritesolnpoolall\n");
    if (!__symbolic_CPXembwrite) printf("CPXembwrite\n");
    if (!__symbolic_CPXdperwrite) printf("CPXdperwrite\n");
    if (!__symbolic_CPXpperwrite) printf("CPXpperwrite\n");
    if (!__symbolic_CPXpreslvwrite) printf("CPXpreslvwrite\n");
    if (!__symbolic_CPXdualwrite) printf("CPXdualwrite\n");
    if (!__symbolic_CPXsetdefaults) printf("CPXsetdefaults\n");
    if (!__symbolic_CPXsetintparam) printf("CPXsetintparam\n");
    if (!__symbolic_CPXsetdblparam) printf("CPXsetdblparam\n");
    if (!__symbolic_CPXsetstrparam) printf("CPXsetstrparam\n");
    if (!__symbolic_CPXgetintparam) printf("CPXgetintparam\n");
    if (!__symbolic_CPXgetdblparam) printf("CPXgetdblparam\n");
    if (!__symbolic_CPXgetstrparam) printf("CPXgetstrparam\n");
    if (!__symbolic_CPXinfointparam) printf("CPXinfointparam\n");
    if (!__symbolic_CPXinfodblparam) printf("CPXinfodblparam\n");
    if (!__symbolic_CPXinfostrparam) printf("CPXinfostrparam\n");
    if (!__symbolic_CPXgetparamname) printf("CPXgetparamname\n");
    if (!__symbolic_CPXgetparamnum) printf("CPXgetparamnum\n");
    if (!__symbolic_CPXgetparamtype) printf("CPXgetparamtype\n");
    if (!__symbolic_CPXreadcopyparam) printf("CPXreadcopyparam\n");
    if (!__symbolic_CPXwriteparam) printf("CPXwriteparam\n");
    if (!__symbolic_CPXgetchgparam) printf("CPXgetchgparam\n");
    if (!__symbolic_CPXtuneparam) printf("CPXtuneparam\n");
    if (!__symbolic_CPXtuneparamprobset) printf("CPXtuneparamprobset\n");
    if (!__symbolic_CPXversion) printf("CPXversion\n");
    if (!__symbolic_CPXopenCPLEX) printf("CPXopenCPLEX\n");
    if (!__symbolic_CPXopenCPLEXruntime) printf("CPXopenCPLEXruntime\n");
    if (!__symbolic_CPXcloseCPLEX) printf("CPXcloseCPLEX\n");
    if (!__symbolic_CPXparenv) printf("CPXparenv\n");
    if (!__symbolic_CPXfreeparenv) printf("CPXfreeparenv\n");
    if (!__symbolic_CPXcheckcopylp) printf("CPXcheckcopylp\n");
    if (!__symbolic_CPXcheckcopylpwnames) printf("CPXcheckcopylpwnames\n");
    if (!__symbolic_CPXcheckaddcols) printf("CPXcheckaddcols\n");
    if (!__symbolic_CPXcheckaddrows) printf("CPXcheckaddrows\n");
    if (!__symbolic_CPXcheckchgcoeflist) printf("CPXcheckchgcoeflist\n");
    if (!__symbolic_CPXcheckvals) printf("CPXcheckvals\n");
    if (!__symbolic_CPXgetchannels) printf("CPXgetchannels\n");
    if (!__symbolic_CPXsetlogfile) printf("CPXsetlogfile\n");
    if (!__symbolic_CPXgetlogfile) printf("CPXgetlogfile\n");
    if (!__symbolic_CPXmsg) printf("CPXmsg\n");
    if (!__symbolic_CPXmsgstr) printf("CPXmsgstr\n");
    if (!__symbolic_CPXflushchannel) printf("CPXflushchannel\n");
    if (!__symbolic_CPXflushstdchannels) printf("CPXflushstdchannels\n");
    if (!__symbolic_CPXaddchannel) printf("CPXaddchannel\n");
    if (!__symbolic_CPXaddfpdest) printf("CPXaddfpdest\n");
    if (!__symbolic_CPXdelfpdest) printf("CPXdelfpdest\n");
    if (!__symbolic_CPXaddfuncdest) printf("CPXaddfuncdest\n");
    if (!__symbolic_CPXdelfuncdest) printf("CPXdelfuncdest\n");
    if (!__symbolic_CPXdelchannel) printf("CPXdelchannel\n");
    if (!__symbolic_CPXdisconnectchannel) printf("CPXdisconnectchannel\n");
    if (!__symbolic_CPXgeterrorstring) printf("CPXgeterrorstring\n");
    if (!__symbolic_CPXsetlpcallbackfunc) printf("CPXsetlpcallbackfunc\n");
    if (!__symbolic_CPXsetnetcallbackfunc) printf("CPXsetnetcallbackfunc\n");
    if (!__symbolic_CPXsettuningcallbackfunc) printf("CPXsettuningcallbackfunc\n");
    if (!__symbolic_CPXgetcallbackinfo) printf("CPXgetcallbackinfo\n");
    if (!__symbolic_CPXgetlpcallbackfunc) printf("CPXgetlpcallbackfunc\n");
    if (!__symbolic_CPXgetnetcallbackfunc) printf("CPXgetnetcallbackfunc\n");
    if (!__symbolic_CPXgettuningcallbackfunc) printf("CPXgettuningcallbackfunc\n");
    if (!__symbolic_CPXsetprofcallbackfunc) printf("CPXsetprofcallbackfunc\n");
    if (!__symbolic_CPXfopen) printf("CPXfopen\n");
    if (!__symbolic_CPXfclose) printf("CPXfclose\n");
    if (!__symbolic_CPXfputs) printf("CPXfputs\n");
    if (!__symbolic_CPXmalloc) printf("CPXmalloc\n");
    if (!__symbolic_CPXrealloc) printf("CPXrealloc\n");
    if (!__symbolic_CPXmemcpy) printf("CPXmemcpy\n");
    if (!__symbolic_CPXfree) printf("CPXfree\n");
    if (!__symbolic_CPXstrlen) printf("CPXstrlen\n");
    if (!__symbolic_CPXstrcpy) printf("CPXstrcpy\n");
    if (!__symbolic_CPXputenv) printf("CPXputenv\n");
    if (!__symbolic_CPXEisort) printf("CPXEisort\n");
    if (!__symbolic_CPXEinsort) printf("CPXEinsort\n");
    if (!__symbolic_CPXEgetThreadNumber) printf("CPXEgetThreadNumber\n");
    if (!__symbolic_CPXEgetmaxthreads) printf("CPXEgetmaxthreads\n");
    if (!__symbolic_CPXEsetJNI) printf("CPXEsetJNI\n");
    if (!__symbolic_CPXEgetJNI) printf("CPXEgetJNI\n");
    if (!__symbolic_CPXEsetnamefunctions) printf("CPXEsetnamefunctions\n");
    if (!__symbolic_CPXEsetnamedef) printf("CPXEsetnamedef\n");
    if (!__symbolic_CPXEdelnames) printf("CPXEdelnames\n");
    if (!__symbolic_CPXEgetCache) printf("CPXEgetCache\n");
    if (!__symbolic_CPXEcacheNewCols) printf("CPXEcacheNewCols\n");
    if (!__symbolic_CPXEcacheNewRows) printf("CPXEcacheNewRows\n");
    if (!__symbolic_CPXEcacheNewNZsByNZ) printf("CPXEcacheNewNZsByNZ\n");
    if (!__symbolic_CPXEgetorigcolind) printf("CPXEgetorigcolind\n");
    if (!__symbolic_CPXEgetorigrowind) printf("CPXEgetorigrowind\n");
    if (!__symbolic_CPXEgetbigreal) printf("CPXEgetbigreal\n");
    if (!__symbolic_CPXEispromotion) printf("CPXEispromotion\n");
    if (!__symbolic_CPXEgetnumrownz) printf("CPXEgetnumrownz\n");
    if (!__symbolic_CPXEcangetbase) printf("CPXEcangetbase\n");
    if (!__symbolic_CPXEwriteparam) printf("CPXEwriteparam\n");
    if (!__symbolic_CPXsetterminate) printf("CPXsetterminate\n");
    if (!__symbolic_CPXEsetterminatefunc) printf("CPXEsetterminatefunc\n");
    if (!__symbolic_CPXEnsAddNames) printf("CPXEnsAddNames\n");
    if (!__symbolic_CPXgetbhead) printf("CPXgetbhead\n");
    if (!__symbolic_CPXbinvcol) printf("CPXbinvcol\n");
    if (!__symbolic_CPXbinvrow) printf("CPXbinvrow\n");
    if (!__symbolic_CPXbinvacol) printf("CPXbinvacol\n");
    if (!__symbolic_CPXbinvarow) printf("CPXbinvarow\n");
    if (!__symbolic_CPXftran) printf("CPXftran\n");
    if (!__symbolic_CPXbtran) printf("CPXbtran\n");
    if (!__symbolic_CPXgetijrow) printf("CPXgetijrow\n");
    if (!__symbolic_CPXgetray) printf("CPXgetray\n");
    if (!__symbolic_CPXgetweight) printf("CPXgetweight\n");
    if (!__symbolic_CPXmdleave) printf("CPXmdleave\n");
    if (!__symbolic_CPXstrongbranch) printf("CPXstrongbranch\n");
    if (!__symbolic_CPXdualfarkas) printf("CPXdualfarkas\n");
    if (!__symbolic_CPXgetobjoffset) printf("CPXgetobjoffset\n");
    if (!__symbolic_CPXcopypartialbase) printf("CPXcopypartialbase\n");
    if (!__symbolic_CPXgetbasednorms) printf("CPXgetbasednorms\n");
    if (!__symbolic_CPXcopybasednorms) printf("CPXcopybasednorms\n");
    if (!__symbolic_CPXgetdnorms) printf("CPXgetdnorms\n");
    if (!__symbolic_CPXcopydnorms) printf("CPXcopydnorms\n");
    if (!__symbolic_CPXkilldnorms) printf("CPXkilldnorms\n");
    if (!__symbolic_CPXgetpnorms) printf("CPXgetpnorms\n");
    if (!__symbolic_CPXcopypnorms) printf("CPXcopypnorms\n");
    if (!__symbolic_CPXkillpnorms) printf("CPXkillpnorms\n");
    if (!__symbolic_CPXpivotin) printf("CPXpivotin\n");
    if (!__symbolic_CPXpivotout) printf("CPXpivotout\n");
    if (!__symbolic_CPXunscaleprob) printf("CPXunscaleprob\n");
    if (!__symbolic_CPXtightenbds) printf("CPXtightenbds\n");
    if (!__symbolic_CPXpresolve) printf("CPXpresolve\n");
    if (!__symbolic_CPXbasicpresolve) printf("CPXbasicpresolve\n");
    if (!__symbolic_CPXslackfromx) printf("CPXslackfromx\n");
    if (!__symbolic_CPXdjfrompi) printf("CPXdjfrompi\n");
    if (!__symbolic_CPXqpdjfrompi) printf("CPXqpdjfrompi\n");
    if (!__symbolic_CPXfreepresolve) printf("CPXfreepresolve\n");
    if (!__symbolic_CPXgetredlp) printf("CPXgetredlp\n");
    if (!__symbolic_CPXcrushx) printf("CPXcrushx\n");
    if (!__symbolic_CPXuncrushx) printf("CPXuncrushx\n");
    if (!__symbolic_CPXcrushpi) printf("CPXcrushpi\n");
    if (!__symbolic_CPXuncrushpi) printf("CPXuncrushpi\n");
    if (!__symbolic_CPXqpuncrushpi) printf("CPXqpuncrushpi\n");
    if (!__symbolic_CPXcrushform) printf("CPXcrushform\n");
    if (!__symbolic_CPXuncrushform) printf("CPXuncrushform\n");
    if (!__symbolic_CPXgetprestat) printf("CPXgetprestat\n");
    if (!__symbolic_CPXcopyprotected) printf("CPXcopyprotected\n");
    if (!__symbolic_CPXgetprotected) printf("CPXgetprotected\n");
    if (!__symbolic_CPXEaggregatevars) printf("CPXEaggregatevars\n");
    if (!__symbolic_CPXgettime) printf("CPXgettime\n");
    if (!__symbolic_CPXlpwrite) printf("CPXlpwrite\n");
    if (!__symbolic_CPXlprewrite) printf("CPXlprewrite\n");
    if (!__symbolic_CPXmpswrite) printf("CPXmpswrite\n");
    if (!__symbolic_CPXmpsrewrite) printf("CPXmpsrewrite\n");
    if (!__symbolic_CPXsavwrite) printf("CPXsavwrite\n");
    if (!__symbolic_CPXreadcopyvec) printf("CPXreadcopyvec\n");
    if (!__symbolic_CPXvecwrite) printf("CPXvecwrite\n");
    if (!__symbolic_CPXbinsolwrite) printf("CPXbinsolwrite\n");
    if (!__symbolic_CPXtxtsolwrite) printf("CPXtxtsolwrite\n");
    if (!__symbolic_CPXwritesol) printf("CPXwritesol\n");
    if (!__symbolic_CPXgetiis) printf("CPXgetiis\n");
    if (!__symbolic_CPXfindiis) printf("CPXfindiis\n");
    if (!__symbolic_CPXdisplayiis) printf("CPXdisplayiis\n");
    if (!__symbolic_CPXiiswrite) printf("CPXiiswrite\n");
    if (!__symbolic_CPXhybbaropt) printf("CPXhybbaropt\n");
    if (!__symbolic_CPXbaropt) printf("CPXbaropt\n");
    if (!__symbolic_CPXEgeneric_lock) printf("CPXEgeneric_lock\n");
    if (!__symbolic_CPXEgeneric_unlock) printf("CPXEgeneric_unlock\n");
    if (!__symbolic_CPXsetorderhookfunc) printf("CPXsetorderhookfunc\n");
    if (!__symbolic_CPXgetorderhookfunc) printf("CPXgetorderhookfunc\n");
    if (!__symbolic_CPXcopyctype) printf("CPXcopyctype\n");
    if (!__symbolic_CPXcopyorder) printf("CPXcopyorder\n");
    if (!__symbolic_CPXcopysos) printf("CPXcopysos\n");
    if (!__symbolic_CPXcopymipstart) printf("CPXcopymipstart\n");
    if (!__symbolic_CPXchgmipstart) printf("CPXchgmipstart\n");
    if (!__symbolic_CPXchgmipstarts) printf("CPXchgmipstarts\n");
    if (!__symbolic_CPXaddmipstarts) printf("CPXaddmipstarts\n");
    if (!__symbolic_CPXdelmipstarts) printf("CPXdelmipstarts\n");
    if (!__symbolic_CPXdelsetmipstarts) printf("CPXdelsetmipstarts\n");
    if (!__symbolic_CPXrefinemipstartconflict) printf("CPXrefinemipstartconflict\n");
    if (!__symbolic_CPXrefinemipstartconflictext) printf("CPXrefinemipstartconflictext\n");
    if (!__symbolic_CPXmipopt) printf("CPXmipopt\n");
    if (!__symbolic_CPXgetmipitcnt) printf("CPXgetmipitcnt\n");
    if (!__symbolic_CPXgetbestobjval) printf("CPXgetbestobjval\n");
    if (!__symbolic_CPXgetmiprelgap) printf("CPXgetmiprelgap\n");
    if (!__symbolic_CPXgetcutoff) printf("CPXgetcutoff\n");
    if (!__symbolic_CPXgetnodecnt) printf("CPXgetnodecnt\n");
    if (!__symbolic_CPXgetnodeleftcnt) printf("CPXgetnodeleftcnt\n");
    if (!__symbolic_CPXgetnodeint) printf("CPXgetnodeint\n");
    if (!__symbolic_CPXgetnumcuts) printf("CPXgetnumcuts\n");
    if (!__symbolic_CPXgetnummipstarts) printf("CPXgetnummipstarts\n");
    if (!__symbolic_CPXgetmipstart) printf("CPXgetmipstart\n");
    if (!__symbolic_CPXgetmipstarts) printf("CPXgetmipstarts\n");
    if (!__symbolic_CPXgetmipstartname) printf("CPXgetmipstartname\n");
    if (!__symbolic_CPXgetmipstartindex) printf("CPXgetmipstartindex\n");
    if (!__symbolic_CPXgetsolnpoolmipstart) printf("CPXgetsolnpoolmipstart\n");
    if (!__symbolic_CPXgetsolnpoolnummipstarts) printf("CPXgetsolnpoolnummipstarts\n");
    if (!__symbolic_CPXgetsubstat) printf("CPXgetsubstat\n");
    if (!__symbolic_CPXgetsubmethod) printf("CPXgetsubmethod\n");
    if (!__symbolic_CPXchgctype) printf("CPXchgctype\n");
    if (!__symbolic_CPXaddsos) printf("CPXaddsos\n");
    if (!__symbolic_CPXdelsetsos) printf("CPXdelsetsos\n");
    if (!__symbolic_CPXgetctype) printf("CPXgetctype\n");
    if (!__symbolic_CPXgetnumsos) printf("CPXgetnumsos\n");
    if (!__symbolic_CPXgetsos) printf("CPXgetsos\n");
    if (!__symbolic_CPXgetsosname) printf("CPXgetsosname\n");
    if (!__symbolic_CPXgetsosindex) printf("CPXgetsosindex\n");
    if (!__symbolic_CPXgetsosinfeas) printf("CPXgetsosinfeas\n");
    if (!__symbolic_CPXgetnumindconstrs) printf("CPXgetnumindconstrs\n");
    if (!__symbolic_CPXgetindconstr) printf("CPXgetindconstr\n");
    if (!__symbolic_CPXEgetindicator) printf("CPXEgetindicator\n");
    if (!__symbolic_CPXgetindconstrindex) printf("CPXgetindconstrindex\n");
    if (!__symbolic_CPXgetindconstrname) printf("CPXgetindconstrname\n");
    if (!__symbolic_CPXgetindconstrslack) printf("CPXgetindconstrslack\n");
    if (!__symbolic_CPXindconstrslackfromx) printf("CPXindconstrslackfromx\n");
    if (!__symbolic_CPXgetindconstrinfeas) printf("CPXgetindconstrinfeas\n");
    if (!__symbolic_CPXdelindconstrs) printf("CPXdelindconstrs\n");
    if (!__symbolic_CPXgetnumint) printf("CPXgetnumint\n");
    if (!__symbolic_CPXgetnumbin) printf("CPXgetnumbin\n");
    if (!__symbolic_CPXgetnumsemicont) printf("CPXgetnumsemicont\n");
    if (!__symbolic_CPXgetnumsemiint) printf("CPXgetnumsemiint\n");
    if (!__symbolic_CPXgetorder) printf("CPXgetorder\n");
    if (!__symbolic_CPXpopulate) printf("CPXpopulate\n");
    if (!__symbolic_CPXgetsolnpoolnumfilters) printf("CPXgetsolnpoolnumfilters\n");
    if (!__symbolic_CPXaddsolnpooldivfilter) printf("CPXaddsolnpooldivfilter\n");
    if (!__symbolic_CPXaddsolnpoolrngfilter) printf("CPXaddsolnpoolrngfilter\n");
    if (!__symbolic_CPXgetsolnpoolfiltertype) printf("CPXgetsolnpoolfiltertype\n");
    if (!__symbolic_CPXgetsolnpooldivfilter) printf("CPXgetsolnpooldivfilter\n");
    if (!__symbolic_CPXgetsolnpoolfilter) printf("CPXgetsolnpoolfilter\n");
    if (!__symbolic_CPXgetsolnpoolrngfilter) printf("CPXgetsolnpoolrngfilter\n");
    if (!__symbolic_CPXgetsolnpoolfiltername) printf("CPXgetsolnpoolfiltername\n");
    if (!__symbolic_CPXgetsolnpoolfilterindex) printf("CPXgetsolnpoolfilterindex\n");
    if (!__symbolic_CPXdelsolnpoolfilters) printf("CPXdelsolnpoolfilters\n");
    if (!__symbolic_CPXdelsetsolnpoolfilters) printf("CPXdelsetsolnpoolfilters\n");
    if (!__symbolic_CPXgetsolnpoolnumsolns) printf("CPXgetsolnpoolnumsolns\n");
    if (!__symbolic_CPXgetsolnpoolnumreplaced) printf("CPXgetsolnpoolnumreplaced\n");
    if (!__symbolic_CPXgetsolnpoolmeanobjval) printf("CPXgetsolnpoolmeanobjval\n");
    if (!__symbolic_CPXgetsolnpoolobjval) printf("CPXgetsolnpoolobjval\n");
    if (!__symbolic_CPXgetsolnpoolx) printf("CPXgetsolnpoolx\n");
    if (!__symbolic_CPXgetsolnpoolslack) printf("CPXgetsolnpoolslack\n");
    if (!__symbolic_CPXgetsolnpoolqconstrslack) printf("CPXgetsolnpoolqconstrslack\n");
    if (!__symbolic_CPXgetsolnpoolsolnname) printf("CPXgetsolnpoolsolnname\n");
    if (!__symbolic_CPXgetsolnpoolsolnindex) printf("CPXgetsolnpoolsolnindex\n");
    if (!__symbolic_CPXdelsolnpoolsolns) printf("CPXdelsolnpoolsolns\n");
    if (!__symbolic_CPXdelsetsolnpoolsolns) printf("CPXdelsetsolnpoolsolns\n");
    if (!__symbolic_CPXreadcopyorder) printf("CPXreadcopyorder\n");
    if (!__symbolic_CPXreadcopysolnpoolfilters) printf("CPXreadcopysolnpoolfilters\n");
    if (!__symbolic_CPXreadcopymipstart) printf("CPXreadcopymipstart\n");
    if (!__symbolic_CPXreadcopymipstarts) printf("CPXreadcopymipstarts\n");
    if (!__symbolic_CPXordwrite) printf("CPXordwrite\n");
    if (!__symbolic_CPXmstwrite) printf("CPXmstwrite\n");
    if (!__symbolic_CPXwritemipstarts) printf("CPXwritemipstarts\n");
    if (!__symbolic_CPXmstwritesolnpool) printf("CPXmstwritesolnpool\n");
    if (!__symbolic_CPXmstwritesolnpoolall) printf("CPXmstwritesolnpoolall\n");
    if (!__symbolic_CPXfltwrite) printf("CPXfltwrite\n");
    if (!__symbolic_CPXcheckcopyctype) printf("CPXcheckcopyctype\n");
    if (!__symbolic_CPXcheckcopysos) printf("CPXcheckcopysos\n");
    if (!__symbolic_CPXEchgsosname) printf("CPXEchgsosname\n");
    if (!__symbolic_CPXsetinfocallbackfunc) printf("CPXsetinfocallbackfunc\n");
    if (!__symbolic_CPXgetinfocallbackfunc) printf("CPXgetinfocallbackfunc\n");
    if (!__symbolic_CPXsetmipcallbackfunc) printf("CPXsetmipcallbackfunc\n");
    if (!__symbolic_CPXgetmipcallbackfunc) printf("CPXgetmipcallbackfunc\n");
    if (!__symbolic_CPXsetbranchcallbackfunc) printf("CPXsetbranchcallbackfunc\n");
    if (!__symbolic_CPXsetbranchnosolncallbackfunc) printf("CPXsetbranchnosolncallbackfunc\n");
    if (!__symbolic_CPXsetcutcallbackfunc) printf("CPXsetcutcallbackfunc\n");
    if (!__symbolic_CPXsetnodecallbackfunc) printf("CPXsetnodecallbackfunc\n");
    if (!__symbolic_CPXsetheuristiccallbackfunc) printf("CPXsetheuristiccallbackfunc\n");
    if (!__symbolic_CPXsetincumbentcallbackfunc) printf("CPXsetincumbentcallbackfunc\n");
    if (!__symbolic_CPXsetsolvecallbackfunc) printf("CPXsetsolvecallbackfunc\n");
    if (!__symbolic_CPXsetdeletenodecallbackfunc) printf("CPXsetdeletenodecallbackfunc\n");
    if (!__symbolic_CPXgetbranchcallbackfunc) printf("CPXgetbranchcallbackfunc\n");
    if (!__symbolic_CPXgetbranchnosolncallbackfunc) printf("CPXgetbranchnosolncallbackfunc\n");
    if (!__symbolic_CPXgetcutcallbackfunc) printf("CPXgetcutcallbackfunc\n");
    if (!__symbolic_CPXgetnodecallbackfunc) printf("CPXgetnodecallbackfunc\n");
    if (!__symbolic_CPXgetheuristiccallbackfunc) printf("CPXgetheuristiccallbackfunc\n");
    if (!__symbolic_CPXgetincumbentcallbackfunc) printf("CPXgetincumbentcallbackfunc\n");
    if (!__symbolic_CPXgetsolvecallbackfunc) printf("CPXgetsolvecallbackfunc\n");
    if (!__symbolic_CPXgetdeletenodecallbackfunc) printf("CPXgetdeletenodecallbackfunc\n");
    if (!__symbolic_CPXgetcallbacknodelp) printf("CPXgetcallbacknodelp\n");
    if (!__symbolic_CPXgetcallbacknodeinfo) printf("CPXgetcallbacknodeinfo\n");
    if (!__symbolic_CPXgetcallbackseqinfo) printf("CPXgetcallbackseqinfo\n");
    if (!__symbolic_CPXgetcallbacksosinfo) printf("CPXgetcallbacksosinfo\n");
    if (!__symbolic_CPXgetcallbackindicatorinfo) printf("CPXgetcallbackindicatorinfo\n");
    if (!__symbolic_CPXcutcallbackadd) printf("CPXcutcallbackadd\n");
    if (!__symbolic_CPXcutcallbackaddlocal) printf("CPXcutcallbackaddlocal\n");
    if (!__symbolic_CPXbranchcallbackbranchbds) printf("CPXbranchcallbackbranchbds\n");
    if (!__symbolic_CPXbranchcallbackbranchgeneral) printf("CPXbranchcallbackbranchgeneral\n");
    if (!__symbolic_CPXbranchcallbackbranchconstraints) printf("CPXbranchcallbackbranchconstraints\n");
    if (!__symbolic_CPXgetcallbacknodex) printf("CPXgetcallbacknodex\n");
    if (!__symbolic_CPXgetcallbacknodeobjval) printf("CPXgetcallbacknodeobjval\n");
    if (!__symbolic_CPXgetcallbackctype) printf("CPXgetcallbackctype\n");
    if (!__symbolic_CPXgetcallbackorder) printf("CPXgetcallbackorder\n");
    if (!__symbolic_CPXgetcallbackpseudocosts) printf("CPXgetcallbackpseudocosts\n");
    if (!__symbolic_CPXgetcallbackincumbent) printf("CPXgetcallbackincumbent\n");
    if (!__symbolic_CPXgetcallbacknodeintfeas) printf("CPXgetcallbacknodeintfeas\n");
    if (!__symbolic_CPXgetcallbackgloballb) printf("CPXgetcallbackgloballb\n");
    if (!__symbolic_CPXgetcallbackglobalub) printf("CPXgetcallbackglobalub\n");
    if (!__symbolic_CPXgetcallbacknodelb) printf("CPXgetcallbacknodelb\n");
    if (!__symbolic_CPXgetcallbacknodeub) printf("CPXgetcallbacknodeub\n");
    if (!__symbolic_CPXgetcallbacklp) printf("CPXgetcallbacklp\n");
    if (!__symbolic_CPXgetcallbacknodestat) printf("CPXgetcallbacknodestat\n");
    if (!__symbolic_CPXgetcallbackbranchconstraints) printf("CPXgetcallbackbranchconstraints\n");
    if (!__symbolic_CPXaddusercuts) printf("CPXaddusercuts\n");
    if (!__symbolic_CPXaddlazyconstraints) printf("CPXaddlazyconstraints\n");
    if (!__symbolic_CPXfreeusercuts) printf("CPXfreeusercuts\n");
    if (!__symbolic_CPXfreelazyconstraints) printf("CPXfreelazyconstraints\n");
    if (!__symbolic_CPXEgetusercuts) printf("CPXEgetusercuts\n");
    if (!__symbolic_CPXEgetusercutname) printf("CPXEgetusercutname\n");
    if (!__symbolic_CPXEgetlazyconstraints) printf("CPXEgetlazyconstraints\n");
    if (!__symbolic_CPXEgetlazyconstraintname) printf("CPXEgetlazyconstraintname\n");
    if (!__symbolic_CPXordread) printf("CPXordread\n");
    if (!__symbolic_CPXaddindconstr) printf("CPXaddindconstr\n");
    if (!__symbolic_CPXEgetnumgconstrs) printf("CPXEgetnumgconstrs\n");
    if (!__symbolic_CPXEdelgconstrs) printf("CPXEdelgconstrs\n");
    if (!__symbolic_CPXEaddindconstr) printf("CPXEaddindconstr\n");
    if (!__symbolic_CPXEaddminexpr) printf("CPXEaddminexpr\n");
    if (!__symbolic_CPXEaddmaxexpr) printf("CPXEaddmaxexpr\n");
    if (!__symbolic_CPXEaddpwl) printf("CPXEaddpwl\n");
    if (!__symbolic_CPXEaddabs) printf("CPXEaddabs\n");
    if (!__symbolic_CPXEaddsetvar) printf("CPXEaddsetvar\n");
    if (!__symbolic_CPXEchgsetvar) printf("CPXEchgsetvar\n");
    if (!__symbolic_CPXEgetsetvarvalues) printf("CPXEgetsetvarvalues\n");
    if (!__symbolic_CPXEaddsetvarmember) printf("CPXEaddsetvarmember\n");
    if (!__symbolic_CPXEaddsetvarcard) printf("CPXEaddsetvarcard\n");
    if (!__symbolic_CPXEaddsetvarsum) printf("CPXEaddsetvarsum\n");
    if (!__symbolic_CPXEaddsetvarmin) printf("CPXEaddsetvarmin\n");
    if (!__symbolic_CPXEaddsetvarmax) printf("CPXEaddsetvarmax\n");
    if (!__symbolic_CPXEaddsetvarsubset) printf("CPXEaddsetvarsubset\n");
    if (!__symbolic_CPXEaddsetvardomain) printf("CPXEaddsetvardomain\n");
    if (!__symbolic_CPXEaddsetvarunion) printf("CPXEaddsetvarunion\n");
    if (!__symbolic_CPXEaddsetvarintersection) printf("CPXEaddsetvarintersection\n");
    if (!__symbolic_CPXEaddsetvarnullintersect) printf("CPXEaddsetvarnullintersect\n");
    if (!__symbolic_CPXEaddsetvarintersect) printf("CPXEaddsetvarintersect\n");
    if (!__symbolic_CPXEaddsetvareq) printf("CPXEaddsetvareq\n");
    if (!__symbolic_CPXEaddsetvarneq) printf("CPXEaddsetvarneq\n");
    if (!__symbolic_CPXEaddsetvarneqcst) printf("CPXEaddsetvarneqcst\n");
    if (!__symbolic_CPXNETcreateprob) printf("CPXNETcreateprob\n");
    if (!__symbolic_CPXNETfreeprob) printf("CPXNETfreeprob\n");
    if (!__symbolic_CPXNETcopynet) printf("CPXNETcopynet\n");
    if (!__symbolic_CPXNETcopybase) printf("CPXNETcopybase\n");
    if (!__symbolic_CPXNETaddnodes) printf("CPXNETaddnodes\n");
    if (!__symbolic_CPXNETaddarcs) printf("CPXNETaddarcs\n");
    if (!__symbolic_CPXNETdelnodes) printf("CPXNETdelnodes\n");
    if (!__symbolic_CPXNETdelarcs) printf("CPXNETdelarcs\n");
    if (!__symbolic_CPXNETdelset) printf("CPXNETdelset\n");
    if (!__symbolic_CPXNETprimopt) printf("CPXNETprimopt\n");
    if (!__symbolic_CPXNETgetstat) printf("CPXNETgetstat\n");
    if (!__symbolic_CPXNETgetobjval) printf("CPXNETgetobjval\n");
    if (!__symbolic_CPXNETgetx) printf("CPXNETgetx\n");
    if (!__symbolic_CPXNETgetpi) printf("CPXNETgetpi\n");
    if (!__symbolic_CPXNETgetslack) printf("CPXNETgetslack\n");
    if (!__symbolic_CPXNETgetdj) printf("CPXNETgetdj\n");
    if (!__symbolic_CPXNETgetitcnt) printf("CPXNETgetitcnt\n");
    if (!__symbolic_CPXNETgetphase1cnt) printf("CPXNETgetphase1cnt\n");
    if (!__symbolic_CPXNETgetbase) printf("CPXNETgetbase\n");
    if (!__symbolic_CPXNETsolution) printf("CPXNETsolution\n");
    if (!__symbolic_CPXNETsolninfo) printf("CPXNETsolninfo\n");
    if (!__symbolic_CPXNETchgname) printf("CPXNETchgname\n");
    if (!__symbolic_CPXNETchgarcname) printf("CPXNETchgarcname\n");
    if (!__symbolic_CPXNETchgnodename) printf("CPXNETchgnodename\n");
    if (!__symbolic_CPXNETchgobjsen) printf("CPXNETchgobjsen\n");
    if (!__symbolic_CPXNETchgbds) printf("CPXNETchgbds\n");
    if (!__symbolic_CPXNETchgarcnodes) printf("CPXNETchgarcnodes\n");
    if (!__symbolic_CPXNETchgobj) printf("CPXNETchgobj\n");
    if (!__symbolic_CPXNETchgsupply) printf("CPXNETchgsupply\n");
    if (!__symbolic_CPXNETgetobjsen) printf("CPXNETgetobjsen\n");
    if (!__symbolic_CPXNETgetsupply) printf("CPXNETgetsupply\n");
    if (!__symbolic_CPXNETgetprobname) printf("CPXNETgetprobname\n");
    if (!__symbolic_CPXNETgetnodename) printf("CPXNETgetnodename\n");
    if (!__symbolic_CPXNETgetarcname) printf("CPXNETgetarcname\n");
    if (!__symbolic_CPXNETgetlb) printf("CPXNETgetlb\n");
    if (!__symbolic_CPXNETgetub) printf("CPXNETgetub\n");
    if (!__symbolic_CPXNETgetobj) printf("CPXNETgetobj\n");
    if (!__symbolic_CPXNETgetarcnodes) printf("CPXNETgetarcnodes\n");
    if (!__symbolic_CPXNETgetnodearcs) printf("CPXNETgetnodearcs\n");
    if (!__symbolic_CPXNETgetnumnodes) printf("CPXNETgetnumnodes\n");
    if (!__symbolic_CPXNETgetnumarcs) printf("CPXNETgetnumarcs\n");
    if (!__symbolic_CPXNETgetnodeindex) printf("CPXNETgetnodeindex\n");
    if (!__symbolic_CPXNETgetarcindex) printf("CPXNETgetarcindex\n");
    if (!__symbolic_CPXNETreadcopyprob) printf("CPXNETreadcopyprob\n");
    if (!__symbolic_CPXNETreadcopybase) printf("CPXNETreadcopybase\n");
    if (!__symbolic_CPXNETwriteprob) printf("CPXNETwriteprob\n");
    if (!__symbolic_CPXNETbasewrite) printf("CPXNETbasewrite\n");
    if (!__symbolic_CPXNETcheckcopynet) printf("CPXNETcheckcopynet\n");
    if (!__symbolic_CPXcopyquad) printf("CPXcopyquad\n");
    if (!__symbolic_CPXcopyqpsep) printf("CPXcopyqpsep\n");
    if (!__symbolic_CPXchgqpcoef) printf("CPXchgqpcoef\n");
    if (!__symbolic_CPXgetnumqpnz) printf("CPXgetnumqpnz\n");
    if (!__symbolic_CPXgetnumquad) printf("CPXgetnumquad\n");
    if (!__symbolic_CPXgetqpcoef) printf("CPXgetqpcoef\n");
    if (!__symbolic_CPXgetquad) printf("CPXgetquad\n");
    if (!__symbolic_CPXqpindefcertificate) printf("CPXqpindefcertificate\n");
    if (!__symbolic_CPXcheckcopyqpsep) printf("CPXcheckcopyqpsep\n");
    if (!__symbolic_CPXcheckcopyquad) printf("CPXcheckcopyquad\n");
    if (!__symbolic_CPXqpopt) printf("CPXqpopt\n");
    if (!__symbolic_CPXaddqconstr) printf("CPXaddqconstr\n");
    if (!__symbolic_CPXdelqconstrs) printf("CPXdelqconstrs\n");
    if (!__symbolic_CPXgetnumqconstrs) printf("CPXgetnumqconstrs\n");
    if (!__symbolic_CPXgetqconstrindex) printf("CPXgetqconstrindex\n");
    if (!__symbolic_CPXgetqconstr) printf("CPXgetqconstr\n");
    if (!__symbolic_CPXgetqconstrname) printf("CPXgetqconstrname\n");
    if (!__symbolic_CPXgetqconstrslack) printf("CPXgetqconstrslack\n");
    if (!__symbolic_CPXqconstrslackfromx) printf("CPXqconstrslackfromx\n");
    if (!__symbolic_CPXgetqconstrinfeas) printf("CPXgetqconstrinfeas\n");
    if (!__symbolic_CPXgetxqxax) printf("CPXgetxqxax\n");
    if (!__symbolic_CPXEchgqcname) printf("CPXEchgqcname\n");

}

int unload_cplex_symbols() {
    /* unload library */
    if (lt_dlclose (__cplex_handle) != 0) return SYMBOL_UNLOAD_FAIL;

    /* exit */
    if (lt_dlexit() != 0) return SYMBOL_UNLOAD_FAIL;

    return SYMBOL_UNLOAD_SUCCESS;
}

