#ifndef CONFIG_H
#define CONFIG_H

#define COMPILED_WITH_CPLEX_SUPPORT
#define  COMPILED_WITH_GLPK_SUPPORT
#define COMPILED_WITH_XPRESS_SUPPORT
#define COMPILED_WITH_GUROBI_SUPPORT

#endif /* CONFIG_H */
