/*
 *!/bin/sh
 *
 * Copyright 2010-2012 Christophe-Marie Duquesne <chm.duquesne@gmail.com>
 *
 * This file is part of lazylpsolverlibs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License.
 *
 * lazylpsolverlibs is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the Eclipse Public License
 * along with this program.  If not, see
 * <http://www.eclipse.org/legal/epl-v10.html>.
 *
 * This file was generated by tools/generate_stub.sh. Do not modify
 * directly
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lazyxprs.h"

GModule *g_module_open_all(const gchar *name, GModuleFlags flags) {
    char *LIB_PATH, *LIB_PATH_COPY, *p, *dir;
    GModule *res;

    p = NULL;
    dir = NULL;
    res = NULL;

#ifdef _WIN32
    LIB_PATH = getenv("PATH");
#define PATH_SEP ';'
#else
    LIB_PATH = getenv("LD_LIBRARY_PATH");
#define PATH_SEP ':'
#endif

    res = g_module_open(g_module_build_path(NULL, name), flags);
    if (res) {
        return res;
    }
    if (LIB_PATH) {
        LIB_PATH_COPY = malloc(strlen(LIB_PATH));
        strncpy(LIB_PATH_COPY, LIB_PATH, strlen(LIB_PATH));
        p = LIB_PATH_COPY;
        dir = p;
        while ((p = strchr(p, PATH_SEP))) {
            *p = '\0';
            p++;
            res = g_module_open(g_module_build_path(dir, name), flags);
            if (res) {
                free(LIB_PATH_COPY);
                return res;
            }
            dir = p;
        }
        res = g_module_open(g_module_build_path(dir, name), flags);
        free(LIB_PATH_COPY);
    }

    return res;
}

int load_xprs_symbols() {
    int res;
    char *LAZYLPSOLVERLIBS_XPRS_LIB_PATH; /* environment variable */
    LAZYLPSOLVERLIBS_XPRS_LIB_PATH = NULL;
    __xprs_module = NULL;

    /* first, try to read the path to load from the environment */
    LAZYLPSOLVERLIBS_XPRS_LIB_PATH = getenv("LAZYLPSOLVERLIBS_XPRS_LIB_PATH");
    if (LAZYLPSOLVERLIBS_XPRS_LIB_PATH != NULL) {
        __xprs_module = g_module_open(LAZYLPSOLVERLIBS_XPRS_LIB_PATH, G_MODULE_BIND_LAZY);
    }

    /* if this failed, try to load libraries without version number */
    if (!__xprs_module) __xprs_module = g_module_open_all("xprs", G_MODULE_BIND_LAZY);


    /* if everything failed, give up */
    if (!__xprs_module) return SYMBOL_LOAD_FAIL;

    res = SYMBOL_LOAD_SUCCESS;

    if (!g_module_symbol(__xprs_module, "XPRSaddcols", (gpointer *) &__symbolic_XPRSaddcols)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddcuts", (gpointer *) &__symbolic_XPRSaddcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddnames", (gpointer *) &__symbolic_XPRSaddnames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddqmatrix", (gpointer *) &__symbolic_XPRSaddqmatrix)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddrows", (gpointer *) &__symbolic_XPRSaddrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddsetnames", (gpointer *) &__symbolic_XPRSaddsetnames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSaddsets", (gpointer *) &__symbolic_XPRSaddsets)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSalter", (gpointer *) &__symbolic_XPRSalter)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSbasiscondition", (gpointer *) &__symbolic_XPRSbasiscondition)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSbeginlicensing", (gpointer *) &__symbolic_XPRSbeginlicensing)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_addbounds", (gpointer *) &__symbolic_XPRS_bo_addbounds)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_addbranches", (gpointer *) &__symbolic_XPRS_bo_addbranches)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_addcuts", (gpointer *) &__symbolic_XPRS_bo_addcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_addrows", (gpointer *) &__symbolic_XPRS_bo_addrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_create", (gpointer *) &__symbolic_XPRS_bo_create)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_destroy", (gpointer *) &__symbolic_XPRS_bo_destroy)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_getbounds", (gpointer *) &__symbolic_XPRS_bo_getbounds)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_getbranches", (gpointer *) &__symbolic_XPRS_bo_getbranches)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_getid", (gpointer *) &__symbolic_XPRS_bo_getid)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_getlasterror", (gpointer *) &__symbolic_XPRS_bo_getlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_getrows", (gpointer *) &__symbolic_XPRS_bo_getrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_setcbmsghandler", (gpointer *) &__symbolic_XPRS_bo_setcbmsghandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_setpreferredbranch", (gpointer *) &__symbolic_XPRS_bo_setpreferredbranch)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_setpriority", (gpointer *) &__symbolic_XPRS_bo_setpriority)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_bo_store", (gpointer *) &__symbolic_XPRS_bo_store)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSbtran", (gpointer *) &__symbolic_XPRSbtran)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgbounds", (gpointer *) &__symbolic_XPRSchgbounds)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgcoef", (gpointer *) &__symbolic_XPRSchgcoef)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgcoltype", (gpointer *) &__symbolic_XPRSchgcoltype)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgmcoef", (gpointer *) &__symbolic_XPRSchgmcoef)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgmqobj", (gpointer *) &__symbolic_XPRSchgmqobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgobj", (gpointer *) &__symbolic_XPRSchgobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgobjsense", (gpointer *) &__symbolic_XPRSchgobjsense)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgqobj", (gpointer *) &__symbolic_XPRSchgqobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgqrowcoeff", (gpointer *) &__symbolic_XPRSchgqrowcoeff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgrhs", (gpointer *) &__symbolic_XPRSchgrhs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgrhsrange", (gpointer *) &__symbolic_XPRSchgrhsrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSchgrowtype", (gpointer *) &__symbolic_XPRSchgrowtype)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRScopycallbacks", (gpointer *) &__symbolic_XPRScopycallbacks)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRScopycontrols", (gpointer *) &__symbolic_XPRScopycontrols)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRScopyprob", (gpointer *) &__symbolic_XPRScopyprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRScreateprob", (gpointer *) &__symbolic_XPRScreateprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelcols", (gpointer *) &__symbolic_XPRSdelcols)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelcpcuts", (gpointer *) &__symbolic_XPRSdelcpcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelcuts", (gpointer *) &__symbolic_XPRSdelcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelindicators", (gpointer *) &__symbolic_XPRSdelindicators)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelnode", (gpointer *) &__symbolic_XPRSdelnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelqmatrix", (gpointer *) &__symbolic_XPRSdelqmatrix)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelrows", (gpointer *) &__symbolic_XPRSdelrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdelsets", (gpointer *) &__symbolic_XPRSdelsets)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSdestroyprob", (gpointer *) &__symbolic_XPRSdestroyprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSendlicensing", (gpointer *) &__symbolic_XPRSendlicensing)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSfixglobal", (gpointer *) &__symbolic_XPRSfixglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSfixglobals", (gpointer *) &__symbolic_XPRSfixglobals)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSfree", (gpointer *) &__symbolic_XPRSfree)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSftran", (gpointer *) &__symbolic_XPRSftran)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_ge_getlasterror", (gpointer *) &__symbolic_XPRS_ge_getlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_ge_setcbmsghandler", (gpointer *) &__symbolic_XPRS_ge_setcbmsghandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetbanner", (gpointer *) &__symbolic_XPRSgetbanner)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetbasis", (gpointer *) &__symbolic_XPRSgetbasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbbariteration", (gpointer *) &__symbolic_XPRSgetcbbariteration)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbbarlog", (gpointer *) &__symbolic_XPRSgetcbbarlog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbchgbranch", (gpointer *) &__symbolic_XPRSgetcbchgbranch)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbchgbranchobject", (gpointer *) &__symbolic_XPRSgetcbchgbranchobject)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbchgnode", (gpointer *) &__symbolic_XPRSgetcbchgnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbcutlog", (gpointer *) &__symbolic_XPRSgetcbcutlog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbcutmgr", (gpointer *) &__symbolic_XPRSgetcbcutmgr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbdestroymt", (gpointer *) &__symbolic_XPRSgetcbdestroymt)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbestimate", (gpointer *) &__symbolic_XPRSgetcbestimate)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbgloballog", (gpointer *) &__symbolic_XPRSgetcbgloballog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbinfnode", (gpointer *) &__symbolic_XPRSgetcbinfnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbintsol", (gpointer *) &__symbolic_XPRSgetcbintsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcblplog", (gpointer *) &__symbolic_XPRSgetcblplog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbmessage", (gpointer *) &__symbolic_XPRSgetcbmessage)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbmipthread", (gpointer *) &__symbolic_XPRSgetcbmipthread)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbnewnode", (gpointer *) &__symbolic_XPRSgetcbnewnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbnlpevaluate", (gpointer *) &__symbolic_XPRSgetcbnlpevaluate)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbnlpgradient", (gpointer *) &__symbolic_XPRSgetcbnlpgradient)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbnlphessian", (gpointer *) &__symbolic_XPRSgetcbnlphessian)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbnodecutoff", (gpointer *) &__symbolic_XPRSgetcbnodecutoff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcboptnode", (gpointer *) &__symbolic_XPRSgetcboptnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbpreintsol", (gpointer *) &__symbolic_XPRSgetcbpreintsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbprenode", (gpointer *) &__symbolic_XPRSgetcbprenode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcbsepnode", (gpointer *) &__symbolic_XPRSgetcbsepnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcoef", (gpointer *) &__symbolic_XPRSgetcoef)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcolrange", (gpointer *) &__symbolic_XPRSgetcolrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcols", (gpointer *) &__symbolic_XPRSgetcols)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcoltype", (gpointer *) &__symbolic_XPRSgetcoltype)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcpcutlist", (gpointer *) &__symbolic_XPRSgetcpcutlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcpcuts", (gpointer *) &__symbolic_XPRSgetcpcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcutlist", (gpointer *) &__symbolic_XPRSgetcutlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcutmap", (gpointer *) &__symbolic_XPRSgetcutmap)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetcutslack", (gpointer *) &__symbolic_XPRSgetcutslack)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetdaysleft", (gpointer *) &__symbolic_XPRSgetdaysleft)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetdblattrib", (gpointer *) &__symbolic_XPRSgetdblattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetdblcontrol", (gpointer *) &__symbolic_XPRSgetdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetdirs", (gpointer *) &__symbolic_XPRSgetdirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetglobal", (gpointer *) &__symbolic_XPRSgetglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetiis", (gpointer *) &__symbolic_XPRSgetiis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetiisdata", (gpointer *) &__symbolic_XPRSgetiisdata)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetindex", (gpointer *) &__symbolic_XPRSgetindex)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetindicators", (gpointer *) &__symbolic_XPRSgetindicators)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetinfeas", (gpointer *) &__symbolic_XPRSgetinfeas)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetintattrib", (gpointer *) &__symbolic_XPRSgetintattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetintcontrol", (gpointer *) &__symbolic_XPRSgetintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetlasterror", (gpointer *) &__symbolic_XPRSgetlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetlb", (gpointer *) &__symbolic_XPRSgetlb)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetlicerrmsg", (gpointer *) &__symbolic_XPRSgetlicerrmsg)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetlpsol", (gpointer *) &__symbolic_XPRSgetlpsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetmessagestatus", (gpointer *) &__symbolic_XPRSgetmessagestatus)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetmipsol", (gpointer *) &__symbolic_XPRSgetmipsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetmqobj", (gpointer *) &__symbolic_XPRSgetmqobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetnamelist", (gpointer *) &__symbolic_XPRSgetnamelist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetnamelistobject", (gpointer *) &__symbolic_XPRSgetnamelistobject)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetnames", (gpointer *) &__symbolic_XPRSgetnames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetobj", (gpointer *) &__symbolic_XPRSgetobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetobjecttypename", (gpointer *) &__symbolic_XPRSgetobjecttypename)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetpivotorder", (gpointer *) &__symbolic_XPRSgetpivotorder)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetpivots", (gpointer *) &__symbolic_XPRSgetpivots)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetpresolvebasis", (gpointer *) &__symbolic_XPRSgetpresolvebasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetpresolvemap", (gpointer *) &__symbolic_XPRSgetpresolvemap)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetpresolvesol", (gpointer *) &__symbolic_XPRSgetpresolvesol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetprobname", (gpointer *) &__symbolic_XPRSgetprobname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetqobj", (gpointer *) &__symbolic_XPRSgetqobj)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetqrowcoeff", (gpointer *) &__symbolic_XPRSgetqrowcoeff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetqrowqmatrix", (gpointer *) &__symbolic_XPRSgetqrowqmatrix)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetqrowqmatrixtriplets", (gpointer *) &__symbolic_XPRSgetqrowqmatrixtriplets)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetqrows", (gpointer *) &__symbolic_XPRSgetqrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetrhs", (gpointer *) &__symbolic_XPRSgetrhs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetrhsrange", (gpointer *) &__symbolic_XPRSgetrhsrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetrowrange", (gpointer *) &__symbolic_XPRSgetrowrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetrows", (gpointer *) &__symbolic_XPRSgetrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetrowtype", (gpointer *) &__symbolic_XPRSgetrowtype)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetscaledinfeas", (gpointer *) &__symbolic_XPRSgetscaledinfeas)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetsol", (gpointer *) &__symbolic_XPRSgetsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetstrattrib", (gpointer *) &__symbolic_XPRSgetstrattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetstrcontrol", (gpointer *) &__symbolic_XPRSgetstrcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetub", (gpointer *) &__symbolic_XPRSgetub)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetunbvec", (gpointer *) &__symbolic_XPRSgetunbvec)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgetversion", (gpointer *) &__symbolic_XPRSgetversion)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSglobal", (gpointer *) &__symbolic_XPRSglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSgoal", (gpointer *) &__symbolic_XPRSgoal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisall", (gpointer *) &__symbolic_XPRSiisall)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisclear", (gpointer *) &__symbolic_XPRSiisclear)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisfirst", (gpointer *) &__symbolic_XPRSiisfirst)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisisolations", (gpointer *) &__symbolic_XPRSiisisolations)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisnext", (gpointer *) &__symbolic_XPRSiisnext)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiisstatus", (gpointer *) &__symbolic_XPRSiisstatus)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSiiswrite", (gpointer *) &__symbolic_XPRSiiswrite)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSinit", (gpointer *) &__symbolic_XPRSinit)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSinitglobal", (gpointer *) &__symbolic_XPRSinitglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSinitializenlphessian", (gpointer *) &__symbolic_XPRSinitializenlphessian)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSinitializenlphessian_indexpairs", (gpointer *) &__symbolic_XPRSinitializenlphessian_indexpairs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSinterrupt", (gpointer *) &__symbolic_XPRSinterrupt)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSlicense", (gpointer *) &__symbolic_XPRSlicense)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadbasis", (gpointer *) &__symbolic_XPRSloadbasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadbranchdirs", (gpointer *) &__symbolic_XPRSloadbranchdirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadcuts", (gpointer *) &__symbolic_XPRSloadcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloaddelayedrows", (gpointer *) &__symbolic_XPRSloaddelayedrows)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloaddirs", (gpointer *) &__symbolic_XPRSloaddirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadglobal", (gpointer *) &__symbolic_XPRSloadglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadlp", (gpointer *) &__symbolic_XPRSloadlp)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadmipsol", (gpointer *) &__symbolic_XPRSloadmipsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadmodelcuts", (gpointer *) &__symbolic_XPRSloadmodelcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadpresolvebasis", (gpointer *) &__symbolic_XPRSloadpresolvebasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadpresolvedirs", (gpointer *) &__symbolic_XPRSloadpresolvedirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadqcqp", (gpointer *) &__symbolic_XPRSloadqcqp)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadqcqpglobal", (gpointer *) &__symbolic_XPRSloadqcqpglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadqglobal", (gpointer *) &__symbolic_XPRSloadqglobal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadqp", (gpointer *) &__symbolic_XPRSloadqp)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSloadsecurevecs", (gpointer *) &__symbolic_XPRSloadsecurevecs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSlogfilehandler", (gpointer *) &__symbolic_XPRSlogfilehandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSlpoptimize", (gpointer *) &__symbolic_XPRSlpoptimize)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSmaxim", (gpointer *) &__symbolic_XPRSmaxim)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSminim", (gpointer *) &__symbolic_XPRSminim)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSmipoptimize", (gpointer *) &__symbolic_XPRSmipoptimize)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_create", (gpointer *) &__symbolic_XPRS_mse_create)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_destroy", (gpointer *) &__symbolic_XPRS_mse_destroy)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getcbgetsolutiondiff", (gpointer *) &__symbolic_XPRS_mse_getcbgetsolutiondiff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getcullchoice", (gpointer *) &__symbolic_XPRS_mse_getcullchoice)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getdblattrib", (gpointer *) &__symbolic_XPRS_mse_getdblattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getdblcontrol", (gpointer *) &__symbolic_XPRS_mse_getdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getintattrib", (gpointer *) &__symbolic_XPRS_mse_getintattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getintcontrol", (gpointer *) &__symbolic_XPRS_mse_getintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getlasterror", (gpointer *) &__symbolic_XPRS_mse_getlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getsolbasename", (gpointer *) &__symbolic_XPRS_mse_getsolbasename)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getsollist", (gpointer *) &__symbolic_XPRS_mse_getsollist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_getsolmetric", (gpointer *) &__symbolic_XPRS_mse_getsolmetric)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_maxim", (gpointer *) &__symbolic_XPRS_mse_maxim)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_minim", (gpointer *) &__symbolic_XPRS_mse_minim)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_opt", (gpointer *) &__symbolic_XPRS_mse_opt)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_setcbgetsolutiondiff", (gpointer *) &__symbolic_XPRS_mse_setcbgetsolutiondiff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_setcbmsghandler", (gpointer *) &__symbolic_XPRS_mse_setcbmsghandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_setdblcontrol", (gpointer *) &__symbolic_XPRS_mse_setdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_setintcontrol", (gpointer *) &__symbolic_XPRS_mse_setintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_mse_setsolbasename", (gpointer *) &__symbolic_XPRS_mse_setsolbasename)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_create", (gpointer *) &__symbolic_XPRS_msp_create)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_delsol", (gpointer *) &__symbolic_XPRS_msp_delsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_destroy", (gpointer *) &__symbolic_XPRS_msp_destroy)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_findsolbyname", (gpointer *) &__symbolic_XPRS_msp_findsolbyname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblattrib", (gpointer *) &__symbolic_XPRS_msp_getdblattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblattribprob", (gpointer *) &__symbolic_XPRS_msp_getdblattribprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblattribprobextreme", (gpointer *) &__symbolic_XPRS_msp_getdblattribprobextreme)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblattribprobsol", (gpointer *) &__symbolic_XPRS_msp_getdblattribprobsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblattribsol", (gpointer *) &__symbolic_XPRS_msp_getdblattribsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblcontrol", (gpointer *) &__symbolic_XPRS_msp_getdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getdblcontrolsol", (gpointer *) &__symbolic_XPRS_msp_getdblcontrolsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintattrib", (gpointer *) &__symbolic_XPRS_msp_getintattrib)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintattribprob", (gpointer *) &__symbolic_XPRS_msp_getintattribprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintattribprobextreme", (gpointer *) &__symbolic_XPRS_msp_getintattribprobextreme)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintattribprobsol", (gpointer *) &__symbolic_XPRS_msp_getintattribprobsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintattribsol", (gpointer *) &__symbolic_XPRS_msp_getintattribsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintcontrol", (gpointer *) &__symbolic_XPRS_msp_getintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getintcontrolsol", (gpointer *) &__symbolic_XPRS_msp_getintcontrolsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getlasterror", (gpointer *) &__symbolic_XPRS_msp_getlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getsol", (gpointer *) &__symbolic_XPRS_msp_getsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getsollist", (gpointer *) &__symbolic_XPRS_msp_getsollist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getsollist2", (gpointer *) &__symbolic_XPRS_msp_getsollist2)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_getsolname", (gpointer *) &__symbolic_XPRS_msp_getsolname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_loadsol", (gpointer *) &__symbolic_XPRS_msp_loadsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_probattach", (gpointer *) &__symbolic_XPRS_msp_probattach)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_probdetach", (gpointer *) &__symbolic_XPRS_msp_probdetach)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_readslxsol", (gpointer *) &__symbolic_XPRS_msp_readslxsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setcbmsghandler", (gpointer *) &__symbolic_XPRS_msp_setcbmsghandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setdblcontrol", (gpointer *) &__symbolic_XPRS_msp_setdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setdblcontrolsol", (gpointer *) &__symbolic_XPRS_msp_setdblcontrolsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setintcontrol", (gpointer *) &__symbolic_XPRS_msp_setintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setintcontrolsol", (gpointer *) &__symbolic_XPRS_msp_setintcontrolsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_setsolname", (gpointer *) &__symbolic_XPRS_msp_setsolname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_msp_writeslxsol", (gpointer *) &__symbolic_XPRS_msp_writeslxsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_addnames", (gpointer *) &__symbolic_XPRS_nml_addnames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_copynames", (gpointer *) &__symbolic_XPRS_nml_copynames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_create", (gpointer *) &__symbolic_XPRS_nml_create)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_destroy", (gpointer *) &__symbolic_XPRS_nml_destroy)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_findname", (gpointer *) &__symbolic_XPRS_nml_findname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_getlasterror", (gpointer *) &__symbolic_XPRS_nml_getlasterror)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_getmaxnamelen", (gpointer *) &__symbolic_XPRS_nml_getmaxnamelen)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_getnamecount", (gpointer *) &__symbolic_XPRS_nml_getnamecount)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_getnames", (gpointer *) &__symbolic_XPRS_nml_getnames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_removenames", (gpointer *) &__symbolic_XPRS_nml_removenames)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRS_nml_setcbmsghandler", (gpointer *) &__symbolic_XPRS_nml_setcbmsghandler)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSobjsa", (gpointer *) &__symbolic_XPRSobjsa)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSpivot", (gpointer *) &__symbolic_XPRSpivot)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSpostsolve", (gpointer *) &__symbolic_XPRSpostsolve)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSpresolverow", (gpointer *) &__symbolic_XPRSpresolverow)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSrange", (gpointer *) &__symbolic_XPRSrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSreadbasis", (gpointer *) &__symbolic_XPRSreadbasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSreadbinsol", (gpointer *) &__symbolic_XPRSreadbinsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSreaddirs", (gpointer *) &__symbolic_XPRSreaddirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSreadprob", (gpointer *) &__symbolic_XPRSreadprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSreadslxsol", (gpointer *) &__symbolic_XPRSreadslxsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSrepairinfeas", (gpointer *) &__symbolic_XPRSrepairinfeas)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSrepairweightedinfeas", (gpointer *) &__symbolic_XPRSrepairweightedinfeas)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSresetnlp", (gpointer *) &__symbolic_XPRSresetnlp)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSrestore", (gpointer *) &__symbolic_XPRSrestore)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSrhssa", (gpointer *) &__symbolic_XPRSrhssa)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsave", (gpointer *) &__symbolic_XPRSsave)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSscale", (gpointer *) &__symbolic_XPRSscale)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetbranchbounds", (gpointer *) &__symbolic_XPRSsetbranchbounds)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetbranchcuts", (gpointer *) &__symbolic_XPRSsetbranchcuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbbariteration", (gpointer *) &__symbolic_XPRSsetcbbariteration)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbbarlog", (gpointer *) &__symbolic_XPRSsetcbbarlog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbchgbranch", (gpointer *) &__symbolic_XPRSsetcbchgbranch)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbchgbranchobject", (gpointer *) &__symbolic_XPRSsetcbchgbranchobject)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbchgnode", (gpointer *) &__symbolic_XPRSsetcbchgnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbcutlog", (gpointer *) &__symbolic_XPRSsetcbcutlog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbcutmgr", (gpointer *) &__symbolic_XPRSsetcbcutmgr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbdestroymt", (gpointer *) &__symbolic_XPRSsetcbdestroymt)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbestimate", (gpointer *) &__symbolic_XPRSsetcbestimate)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbgloballog", (gpointer *) &__symbolic_XPRSsetcbgloballog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbinfnode", (gpointer *) &__symbolic_XPRSsetcbinfnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbintsol", (gpointer *) &__symbolic_XPRSsetcbintsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcblplog", (gpointer *) &__symbolic_XPRSsetcblplog)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbmessage", (gpointer *) &__symbolic_XPRSsetcbmessage)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbmipthread", (gpointer *) &__symbolic_XPRSsetcbmipthread)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbnewnode", (gpointer *) &__symbolic_XPRSsetcbnewnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbnlpevaluate", (gpointer *) &__symbolic_XPRSsetcbnlpevaluate)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbnlpgradient", (gpointer *) &__symbolic_XPRSsetcbnlpgradient)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbnlphessian", (gpointer *) &__symbolic_XPRSsetcbnlphessian)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbnodecutoff", (gpointer *) &__symbolic_XPRSsetcbnodecutoff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcboptnode", (gpointer *) &__symbolic_XPRSsetcboptnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbpreintsol", (gpointer *) &__symbolic_XPRSsetcbpreintsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbprenode", (gpointer *) &__symbolic_XPRSsetcbprenode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetcbsepnode", (gpointer *) &__symbolic_XPRSsetcbsepnode)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetdblcontrol", (gpointer *) &__symbolic_XPRSsetdblcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetdefaultcontrol", (gpointer *) &__symbolic_XPRSsetdefaultcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetdefaults", (gpointer *) &__symbolic_XPRSsetdefaults)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetindicators", (gpointer *) &__symbolic_XPRSsetindicators)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetintcontrol", (gpointer *) &__symbolic_XPRSsetintcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetlogfile", (gpointer *) &__symbolic_XPRSsetlogfile)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetmessagestatus", (gpointer *) &__symbolic_XPRSsetmessagestatus)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetprobname", (gpointer *) &__symbolic_XPRSsetprobname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSsetstrcontrol", (gpointer *) &__symbolic_XPRSsetstrcontrol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSstorebounds", (gpointer *) &__symbolic_XPRSstorebounds)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSstorecuts", (gpointer *) &__symbolic_XPRSstorecuts)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwritebasis", (gpointer *) &__symbolic_XPRSwritebasis)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwritebinsol", (gpointer *) &__symbolic_XPRSwritebinsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwritedirs", (gpointer *) &__symbolic_XPRSwritedirs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwriteprob", (gpointer *) &__symbolic_XPRSwriteprob)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwriteprtrange", (gpointer *) &__symbolic_XPRSwriteprtrange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwriteprtsol", (gpointer *) &__symbolic_XPRSwriteprtsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwriterange", (gpointer *) &__symbolic_XPRSwriterange)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwriteslxsol", (gpointer *) &__symbolic_XPRSwriteslxsol)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__xprs_module, "XPRSwritesol", (gpointer *) &__symbolic_XPRSwritesol)) res = SYMBOL_MISSING;

    return res;
}

void print_xprs_missing_symbols() {

    if (!__symbolic_XPRSaddcols) printf("XPRSaddcols\n");
    if (!__symbolic_XPRSaddcuts) printf("XPRSaddcuts\n");
    if (!__symbolic_XPRSaddnames) printf("XPRSaddnames\n");
    if (!__symbolic_XPRSaddqmatrix) printf("XPRSaddqmatrix\n");
    if (!__symbolic_XPRSaddrows) printf("XPRSaddrows\n");
    if (!__symbolic_XPRSaddsetnames) printf("XPRSaddsetnames\n");
    if (!__symbolic_XPRSaddsets) printf("XPRSaddsets\n");
    if (!__symbolic_XPRSalter) printf("XPRSalter\n");
    if (!__symbolic_XPRSbasiscondition) printf("XPRSbasiscondition\n");
    if (!__symbolic_XPRSbeginlicensing) printf("XPRSbeginlicensing\n");
    if (!__symbolic_XPRS_bo_addbounds) printf("XPRS_bo_addbounds\n");
    if (!__symbolic_XPRS_bo_addbranches) printf("XPRS_bo_addbranches\n");
    if (!__symbolic_XPRS_bo_addcuts) printf("XPRS_bo_addcuts\n");
    if (!__symbolic_XPRS_bo_addrows) printf("XPRS_bo_addrows\n");
    if (!__symbolic_XPRS_bo_create) printf("XPRS_bo_create\n");
    if (!__symbolic_XPRS_bo_destroy) printf("XPRS_bo_destroy\n");
    if (!__symbolic_XPRS_bo_getbounds) printf("XPRS_bo_getbounds\n");
    if (!__symbolic_XPRS_bo_getbranches) printf("XPRS_bo_getbranches\n");
    if (!__symbolic_XPRS_bo_getid) printf("XPRS_bo_getid\n");
    if (!__symbolic_XPRS_bo_getlasterror) printf("XPRS_bo_getlasterror\n");
    if (!__symbolic_XPRS_bo_getrows) printf("XPRS_bo_getrows\n");
    if (!__symbolic_XPRS_bo_setcbmsghandler) printf("XPRS_bo_setcbmsghandler\n");
    if (!__symbolic_XPRS_bo_setpreferredbranch) printf("XPRS_bo_setpreferredbranch\n");
    if (!__symbolic_XPRS_bo_setpriority) printf("XPRS_bo_setpriority\n");
    if (!__symbolic_XPRS_bo_store) printf("XPRS_bo_store\n");
    if (!__symbolic_XPRSbtran) printf("XPRSbtran\n");
    if (!__symbolic_XPRSchgbounds) printf("XPRSchgbounds\n");
    if (!__symbolic_XPRSchgcoef) printf("XPRSchgcoef\n");
    if (!__symbolic_XPRSchgcoltype) printf("XPRSchgcoltype\n");
    if (!__symbolic_XPRSchgmcoef) printf("XPRSchgmcoef\n");
    if (!__symbolic_XPRSchgmqobj) printf("XPRSchgmqobj\n");
    if (!__symbolic_XPRSchgobj) printf("XPRSchgobj\n");
    if (!__symbolic_XPRSchgobjsense) printf("XPRSchgobjsense\n");
    if (!__symbolic_XPRSchgqobj) printf("XPRSchgqobj\n");
    if (!__symbolic_XPRSchgqrowcoeff) printf("XPRSchgqrowcoeff\n");
    if (!__symbolic_XPRSchgrhs) printf("XPRSchgrhs\n");
    if (!__symbolic_XPRSchgrhsrange) printf("XPRSchgrhsrange\n");
    if (!__symbolic_XPRSchgrowtype) printf("XPRSchgrowtype\n");
    if (!__symbolic_XPRScopycallbacks) printf("XPRScopycallbacks\n");
    if (!__symbolic_XPRScopycontrols) printf("XPRScopycontrols\n");
    if (!__symbolic_XPRScopyprob) printf("XPRScopyprob\n");
    if (!__symbolic_XPRScreateprob) printf("XPRScreateprob\n");
    if (!__symbolic_XPRSdelcols) printf("XPRSdelcols\n");
    if (!__symbolic_XPRSdelcpcuts) printf("XPRSdelcpcuts\n");
    if (!__symbolic_XPRSdelcuts) printf("XPRSdelcuts\n");
    if (!__symbolic_XPRSdelindicators) printf("XPRSdelindicators\n");
    if (!__symbolic_XPRSdelnode) printf("XPRSdelnode\n");
    if (!__symbolic_XPRSdelqmatrix) printf("XPRSdelqmatrix\n");
    if (!__symbolic_XPRSdelrows) printf("XPRSdelrows\n");
    if (!__symbolic_XPRSdelsets) printf("XPRSdelsets\n");
    if (!__symbolic_XPRSdestroyprob) printf("XPRSdestroyprob\n");
    if (!__symbolic_XPRSendlicensing) printf("XPRSendlicensing\n");
    if (!__symbolic_XPRSfixglobal) printf("XPRSfixglobal\n");
    if (!__symbolic_XPRSfixglobals) printf("XPRSfixglobals\n");
    if (!__symbolic_XPRSfree) printf("XPRSfree\n");
    if (!__symbolic_XPRSftran) printf("XPRSftran\n");
    if (!__symbolic_XPRS_ge_getlasterror) printf("XPRS_ge_getlasterror\n");
    if (!__symbolic_XPRS_ge_setcbmsghandler) printf("XPRS_ge_setcbmsghandler\n");
    if (!__symbolic_XPRSgetbanner) printf("XPRSgetbanner\n");
    if (!__symbolic_XPRSgetbasis) printf("XPRSgetbasis\n");
    if (!__symbolic_XPRSgetcbbariteration) printf("XPRSgetcbbariteration\n");
    if (!__symbolic_XPRSgetcbbarlog) printf("XPRSgetcbbarlog\n");
    if (!__symbolic_XPRSgetcbchgbranch) printf("XPRSgetcbchgbranch\n");
    if (!__symbolic_XPRSgetcbchgbranchobject) printf("XPRSgetcbchgbranchobject\n");
    if (!__symbolic_XPRSgetcbchgnode) printf("XPRSgetcbchgnode\n");
    if (!__symbolic_XPRSgetcbcutlog) printf("XPRSgetcbcutlog\n");
    if (!__symbolic_XPRSgetcbcutmgr) printf("XPRSgetcbcutmgr\n");
    if (!__symbolic_XPRSgetcbdestroymt) printf("XPRSgetcbdestroymt\n");
    if (!__symbolic_XPRSgetcbestimate) printf("XPRSgetcbestimate\n");
    if (!__symbolic_XPRSgetcbgloballog) printf("XPRSgetcbgloballog\n");
    if (!__symbolic_XPRSgetcbinfnode) printf("XPRSgetcbinfnode\n");
    if (!__symbolic_XPRSgetcbintsol) printf("XPRSgetcbintsol\n");
    if (!__symbolic_XPRSgetcblplog) printf("XPRSgetcblplog\n");
    if (!__symbolic_XPRSgetcbmessage) printf("XPRSgetcbmessage\n");
    if (!__symbolic_XPRSgetcbmipthread) printf("XPRSgetcbmipthread\n");
    if (!__symbolic_XPRSgetcbnewnode) printf("XPRSgetcbnewnode\n");
    if (!__symbolic_XPRSgetcbnlpevaluate) printf("XPRSgetcbnlpevaluate\n");
    if (!__symbolic_XPRSgetcbnlpgradient) printf("XPRSgetcbnlpgradient\n");
    if (!__symbolic_XPRSgetcbnlphessian) printf("XPRSgetcbnlphessian\n");
    if (!__symbolic_XPRSgetcbnodecutoff) printf("XPRSgetcbnodecutoff\n");
    if (!__symbolic_XPRSgetcboptnode) printf("XPRSgetcboptnode\n");
    if (!__symbolic_XPRSgetcbpreintsol) printf("XPRSgetcbpreintsol\n");
    if (!__symbolic_XPRSgetcbprenode) printf("XPRSgetcbprenode\n");
    if (!__symbolic_XPRSgetcbsepnode) printf("XPRSgetcbsepnode\n");
    if (!__symbolic_XPRSgetcoef) printf("XPRSgetcoef\n");
    if (!__symbolic_XPRSgetcolrange) printf("XPRSgetcolrange\n");
    if (!__symbolic_XPRSgetcols) printf("XPRSgetcols\n");
    if (!__symbolic_XPRSgetcoltype) printf("XPRSgetcoltype\n");
    if (!__symbolic_XPRSgetcpcutlist) printf("XPRSgetcpcutlist\n");
    if (!__symbolic_XPRSgetcpcuts) printf("XPRSgetcpcuts\n");
    if (!__symbolic_XPRSgetcutlist) printf("XPRSgetcutlist\n");
    if (!__symbolic_XPRSgetcutmap) printf("XPRSgetcutmap\n");
    if (!__symbolic_XPRSgetcutslack) printf("XPRSgetcutslack\n");
    if (!__symbolic_XPRSgetdaysleft) printf("XPRSgetdaysleft\n");
    if (!__symbolic_XPRSgetdblattrib) printf("XPRSgetdblattrib\n");
    if (!__symbolic_XPRSgetdblcontrol) printf("XPRSgetdblcontrol\n");
    if (!__symbolic_XPRSgetdirs) printf("XPRSgetdirs\n");
    if (!__symbolic_XPRSgetglobal) printf("XPRSgetglobal\n");
    if (!__symbolic_XPRSgetiis) printf("XPRSgetiis\n");
    if (!__symbolic_XPRSgetiisdata) printf("XPRSgetiisdata\n");
    if (!__symbolic_XPRSgetindex) printf("XPRSgetindex\n");
    if (!__symbolic_XPRSgetindicators) printf("XPRSgetindicators\n");
    if (!__symbolic_XPRSgetinfeas) printf("XPRSgetinfeas\n");
    if (!__symbolic_XPRSgetintattrib) printf("XPRSgetintattrib\n");
    if (!__symbolic_XPRSgetintcontrol) printf("XPRSgetintcontrol\n");
    if (!__symbolic_XPRSgetlasterror) printf("XPRSgetlasterror\n");
    if (!__symbolic_XPRSgetlb) printf("XPRSgetlb\n");
    if (!__symbolic_XPRSgetlicerrmsg) printf("XPRSgetlicerrmsg\n");
    if (!__symbolic_XPRSgetlpsol) printf("XPRSgetlpsol\n");
    if (!__symbolic_XPRSgetmessagestatus) printf("XPRSgetmessagestatus\n");
    if (!__symbolic_XPRSgetmipsol) printf("XPRSgetmipsol\n");
    if (!__symbolic_XPRSgetmqobj) printf("XPRSgetmqobj\n");
    if (!__symbolic_XPRSgetnamelist) printf("XPRSgetnamelist\n");
    if (!__symbolic_XPRSgetnamelistobject) printf("XPRSgetnamelistobject\n");
    if (!__symbolic_XPRSgetnames) printf("XPRSgetnames\n");
    if (!__symbolic_XPRSgetobj) printf("XPRSgetobj\n");
    if (!__symbolic_XPRSgetobjecttypename) printf("XPRSgetobjecttypename\n");
    if (!__symbolic_XPRSgetpivotorder) printf("XPRSgetpivotorder\n");
    if (!__symbolic_XPRSgetpivots) printf("XPRSgetpivots\n");
    if (!__symbolic_XPRSgetpresolvebasis) printf("XPRSgetpresolvebasis\n");
    if (!__symbolic_XPRSgetpresolvemap) printf("XPRSgetpresolvemap\n");
    if (!__symbolic_XPRSgetpresolvesol) printf("XPRSgetpresolvesol\n");
    if (!__symbolic_XPRSgetprobname) printf("XPRSgetprobname\n");
    if (!__symbolic_XPRSgetqobj) printf("XPRSgetqobj\n");
    if (!__symbolic_XPRSgetqrowcoeff) printf("XPRSgetqrowcoeff\n");
    if (!__symbolic_XPRSgetqrowqmatrix) printf("XPRSgetqrowqmatrix\n");
    if (!__symbolic_XPRSgetqrowqmatrixtriplets) printf("XPRSgetqrowqmatrixtriplets\n");
    if (!__symbolic_XPRSgetqrows) printf("XPRSgetqrows\n");
    if (!__symbolic_XPRSgetrhs) printf("XPRSgetrhs\n");
    if (!__symbolic_XPRSgetrhsrange) printf("XPRSgetrhsrange\n");
    if (!__symbolic_XPRSgetrowrange) printf("XPRSgetrowrange\n");
    if (!__symbolic_XPRSgetrows) printf("XPRSgetrows\n");
    if (!__symbolic_XPRSgetrowtype) printf("XPRSgetrowtype\n");
    if (!__symbolic_XPRSgetscaledinfeas) printf("XPRSgetscaledinfeas\n");
    if (!__symbolic_XPRSgetsol) printf("XPRSgetsol\n");
    if (!__symbolic_XPRSgetstrattrib) printf("XPRSgetstrattrib\n");
    if (!__symbolic_XPRSgetstrcontrol) printf("XPRSgetstrcontrol\n");
    if (!__symbolic_XPRSgetub) printf("XPRSgetub\n");
    if (!__symbolic_XPRSgetunbvec) printf("XPRSgetunbvec\n");
    if (!__symbolic_XPRSgetversion) printf("XPRSgetversion\n");
    if (!__symbolic_XPRSglobal) printf("XPRSglobal\n");
    if (!__symbolic_XPRSgoal) printf("XPRSgoal\n");
    if (!__symbolic_XPRSiisall) printf("XPRSiisall\n");
    if (!__symbolic_XPRSiisclear) printf("XPRSiisclear\n");
    if (!__symbolic_XPRSiisfirst) printf("XPRSiisfirst\n");
    if (!__symbolic_XPRSiisisolations) printf("XPRSiisisolations\n");
    if (!__symbolic_XPRSiisnext) printf("XPRSiisnext\n");
    if (!__symbolic_XPRSiisstatus) printf("XPRSiisstatus\n");
    if (!__symbolic_XPRSiiswrite) printf("XPRSiiswrite\n");
    if (!__symbolic_XPRSinit) printf("XPRSinit\n");
    if (!__symbolic_XPRSinitglobal) printf("XPRSinitglobal\n");
    if (!__symbolic_XPRSinitializenlphessian) printf("XPRSinitializenlphessian\n");
    if (!__symbolic_XPRSinitializenlphessian_indexpairs) printf("XPRSinitializenlphessian_indexpairs\n");
    if (!__symbolic_XPRSinterrupt) printf("XPRSinterrupt\n");
    if (!__symbolic_XPRSlicense) printf("XPRSlicense\n");
    if (!__symbolic_XPRSloadbasis) printf("XPRSloadbasis\n");
    if (!__symbolic_XPRSloadbranchdirs) printf("XPRSloadbranchdirs\n");
    if (!__symbolic_XPRSloadcuts) printf("XPRSloadcuts\n");
    if (!__symbolic_XPRSloaddelayedrows) printf("XPRSloaddelayedrows\n");
    if (!__symbolic_XPRSloaddirs) printf("XPRSloaddirs\n");
    if (!__symbolic_XPRSloadglobal) printf("XPRSloadglobal\n");
    if (!__symbolic_XPRSloadlp) printf("XPRSloadlp\n");
    if (!__symbolic_XPRSloadmipsol) printf("XPRSloadmipsol\n");
    if (!__symbolic_XPRSloadmodelcuts) printf("XPRSloadmodelcuts\n");
    if (!__symbolic_XPRSloadpresolvebasis) printf("XPRSloadpresolvebasis\n");
    if (!__symbolic_XPRSloadpresolvedirs) printf("XPRSloadpresolvedirs\n");
    if (!__symbolic_XPRSloadqcqp) printf("XPRSloadqcqp\n");
    if (!__symbolic_XPRSloadqcqpglobal) printf("XPRSloadqcqpglobal\n");
    if (!__symbolic_XPRSloadqglobal) printf("XPRSloadqglobal\n");
    if (!__symbolic_XPRSloadqp) printf("XPRSloadqp\n");
    if (!__symbolic_XPRSloadsecurevecs) printf("XPRSloadsecurevecs\n");
    if (!__symbolic_XPRSlogfilehandler) printf("XPRSlogfilehandler\n");
    if (!__symbolic_XPRSlpoptimize) printf("XPRSlpoptimize\n");
    if (!__symbolic_XPRSmaxim) printf("XPRSmaxim\n");
    if (!__symbolic_XPRSminim) printf("XPRSminim\n");
    if (!__symbolic_XPRSmipoptimize) printf("XPRSmipoptimize\n");
    if (!__symbolic_XPRS_mse_create) printf("XPRS_mse_create\n");
    if (!__symbolic_XPRS_mse_destroy) printf("XPRS_mse_destroy\n");
    if (!__symbolic_XPRS_mse_getcbgetsolutiondiff) printf("XPRS_mse_getcbgetsolutiondiff\n");
    if (!__symbolic_XPRS_mse_getcullchoice) printf("XPRS_mse_getcullchoice\n");
    if (!__symbolic_XPRS_mse_getdblattrib) printf("XPRS_mse_getdblattrib\n");
    if (!__symbolic_XPRS_mse_getdblcontrol) printf("XPRS_mse_getdblcontrol\n");
    if (!__symbolic_XPRS_mse_getintattrib) printf("XPRS_mse_getintattrib\n");
    if (!__symbolic_XPRS_mse_getintcontrol) printf("XPRS_mse_getintcontrol\n");
    if (!__symbolic_XPRS_mse_getlasterror) printf("XPRS_mse_getlasterror\n");
    if (!__symbolic_XPRS_mse_getsolbasename) printf("XPRS_mse_getsolbasename\n");
    if (!__symbolic_XPRS_mse_getsollist) printf("XPRS_mse_getsollist\n");
    if (!__symbolic_XPRS_mse_getsolmetric) printf("XPRS_mse_getsolmetric\n");
    if (!__symbolic_XPRS_mse_maxim) printf("XPRS_mse_maxim\n");
    if (!__symbolic_XPRS_mse_minim) printf("XPRS_mse_minim\n");
    if (!__symbolic_XPRS_mse_opt) printf("XPRS_mse_opt\n");
    if (!__symbolic_XPRS_mse_setcbgetsolutiondiff) printf("XPRS_mse_setcbgetsolutiondiff\n");
    if (!__symbolic_XPRS_mse_setcbmsghandler) printf("XPRS_mse_setcbmsghandler\n");
    if (!__symbolic_XPRS_mse_setdblcontrol) printf("XPRS_mse_setdblcontrol\n");
    if (!__symbolic_XPRS_mse_setintcontrol) printf("XPRS_mse_setintcontrol\n");
    if (!__symbolic_XPRS_mse_setsolbasename) printf("XPRS_mse_setsolbasename\n");
    if (!__symbolic_XPRS_msp_create) printf("XPRS_msp_create\n");
    if (!__symbolic_XPRS_msp_delsol) printf("XPRS_msp_delsol\n");
    if (!__symbolic_XPRS_msp_destroy) printf("XPRS_msp_destroy\n");
    if (!__symbolic_XPRS_msp_findsolbyname) printf("XPRS_msp_findsolbyname\n");
    if (!__symbolic_XPRS_msp_getdblattrib) printf("XPRS_msp_getdblattrib\n");
    if (!__symbolic_XPRS_msp_getdblattribprob) printf("XPRS_msp_getdblattribprob\n");
    if (!__symbolic_XPRS_msp_getdblattribprobextreme) printf("XPRS_msp_getdblattribprobextreme\n");
    if (!__symbolic_XPRS_msp_getdblattribprobsol) printf("XPRS_msp_getdblattribprobsol\n");
    if (!__symbolic_XPRS_msp_getdblattribsol) printf("XPRS_msp_getdblattribsol\n");
    if (!__symbolic_XPRS_msp_getdblcontrol) printf("XPRS_msp_getdblcontrol\n");
    if (!__symbolic_XPRS_msp_getdblcontrolsol) printf("XPRS_msp_getdblcontrolsol\n");
    if (!__symbolic_XPRS_msp_getintattrib) printf("XPRS_msp_getintattrib\n");
    if (!__symbolic_XPRS_msp_getintattribprob) printf("XPRS_msp_getintattribprob\n");
    if (!__symbolic_XPRS_msp_getintattribprobextreme) printf("XPRS_msp_getintattribprobextreme\n");
    if (!__symbolic_XPRS_msp_getintattribprobsol) printf("XPRS_msp_getintattribprobsol\n");
    if (!__symbolic_XPRS_msp_getintattribsol) printf("XPRS_msp_getintattribsol\n");
    if (!__symbolic_XPRS_msp_getintcontrol) printf("XPRS_msp_getintcontrol\n");
    if (!__symbolic_XPRS_msp_getintcontrolsol) printf("XPRS_msp_getintcontrolsol\n");
    if (!__symbolic_XPRS_msp_getlasterror) printf("XPRS_msp_getlasterror\n");
    if (!__symbolic_XPRS_msp_getsol) printf("XPRS_msp_getsol\n");
    if (!__symbolic_XPRS_msp_getsollist) printf("XPRS_msp_getsollist\n");
    if (!__symbolic_XPRS_msp_getsollist2) printf("XPRS_msp_getsollist2\n");
    if (!__symbolic_XPRS_msp_getsolname) printf("XPRS_msp_getsolname\n");
    if (!__symbolic_XPRS_msp_loadsol) printf("XPRS_msp_loadsol\n");
    if (!__symbolic_XPRS_msp_probattach) printf("XPRS_msp_probattach\n");
    if (!__symbolic_XPRS_msp_probdetach) printf("XPRS_msp_probdetach\n");
    if (!__symbolic_XPRS_msp_readslxsol) printf("XPRS_msp_readslxsol\n");
    if (!__symbolic_XPRS_msp_setcbmsghandler) printf("XPRS_msp_setcbmsghandler\n");
    if (!__symbolic_XPRS_msp_setdblcontrol) printf("XPRS_msp_setdblcontrol\n");
    if (!__symbolic_XPRS_msp_setdblcontrolsol) printf("XPRS_msp_setdblcontrolsol\n");
    if (!__symbolic_XPRS_msp_setintcontrol) printf("XPRS_msp_setintcontrol\n");
    if (!__symbolic_XPRS_msp_setintcontrolsol) printf("XPRS_msp_setintcontrolsol\n");
    if (!__symbolic_XPRS_msp_setsolname) printf("XPRS_msp_setsolname\n");
    if (!__symbolic_XPRS_msp_writeslxsol) printf("XPRS_msp_writeslxsol\n");
    if (!__symbolic_XPRS_nml_addnames) printf("XPRS_nml_addnames\n");
    if (!__symbolic_XPRS_nml_copynames) printf("XPRS_nml_copynames\n");
    if (!__symbolic_XPRS_nml_create) printf("XPRS_nml_create\n");
    if (!__symbolic_XPRS_nml_destroy) printf("XPRS_nml_destroy\n");
    if (!__symbolic_XPRS_nml_findname) printf("XPRS_nml_findname\n");
    if (!__symbolic_XPRS_nml_getlasterror) printf("XPRS_nml_getlasterror\n");
    if (!__symbolic_XPRS_nml_getmaxnamelen) printf("XPRS_nml_getmaxnamelen\n");
    if (!__symbolic_XPRS_nml_getnamecount) printf("XPRS_nml_getnamecount\n");
    if (!__symbolic_XPRS_nml_getnames) printf("XPRS_nml_getnames\n");
    if (!__symbolic_XPRS_nml_removenames) printf("XPRS_nml_removenames\n");
    if (!__symbolic_XPRS_nml_setcbmsghandler) printf("XPRS_nml_setcbmsghandler\n");
    if (!__symbolic_XPRSobjsa) printf("XPRSobjsa\n");
    if (!__symbolic_XPRSpivot) printf("XPRSpivot\n");
    if (!__symbolic_XPRSpostsolve) printf("XPRSpostsolve\n");
    if (!__symbolic_XPRSpresolverow) printf("XPRSpresolverow\n");
    if (!__symbolic_XPRSrange) printf("XPRSrange\n");
    if (!__symbolic_XPRSreadbasis) printf("XPRSreadbasis\n");
    if (!__symbolic_XPRSreadbinsol) printf("XPRSreadbinsol\n");
    if (!__symbolic_XPRSreaddirs) printf("XPRSreaddirs\n");
    if (!__symbolic_XPRSreadprob) printf("XPRSreadprob\n");
    if (!__symbolic_XPRSreadslxsol) printf("XPRSreadslxsol\n");
    if (!__symbolic_XPRSrepairinfeas) printf("XPRSrepairinfeas\n");
    if (!__symbolic_XPRSrepairweightedinfeas) printf("XPRSrepairweightedinfeas\n");
    if (!__symbolic_XPRSresetnlp) printf("XPRSresetnlp\n");
    if (!__symbolic_XPRSrestore) printf("XPRSrestore\n");
    if (!__symbolic_XPRSrhssa) printf("XPRSrhssa\n");
    if (!__symbolic_XPRSsave) printf("XPRSsave\n");
    if (!__symbolic_XPRSscale) printf("XPRSscale\n");
    if (!__symbolic_XPRSsetbranchbounds) printf("XPRSsetbranchbounds\n");
    if (!__symbolic_XPRSsetbranchcuts) printf("XPRSsetbranchcuts\n");
    if (!__symbolic_XPRSsetcbbariteration) printf("XPRSsetcbbariteration\n");
    if (!__symbolic_XPRSsetcbbarlog) printf("XPRSsetcbbarlog\n");
    if (!__symbolic_XPRSsetcbchgbranch) printf("XPRSsetcbchgbranch\n");
    if (!__symbolic_XPRSsetcbchgbranchobject) printf("XPRSsetcbchgbranchobject\n");
    if (!__symbolic_XPRSsetcbchgnode) printf("XPRSsetcbchgnode\n");
    if (!__symbolic_XPRSsetcbcutlog) printf("XPRSsetcbcutlog\n");
    if (!__symbolic_XPRSsetcbcutmgr) printf("XPRSsetcbcutmgr\n");
    if (!__symbolic_XPRSsetcbdestroymt) printf("XPRSsetcbdestroymt\n");
    if (!__symbolic_XPRSsetcbestimate) printf("XPRSsetcbestimate\n");
    if (!__symbolic_XPRSsetcbgloballog) printf("XPRSsetcbgloballog\n");
    if (!__symbolic_XPRSsetcbinfnode) printf("XPRSsetcbinfnode\n");
    if (!__symbolic_XPRSsetcbintsol) printf("XPRSsetcbintsol\n");
    if (!__symbolic_XPRSsetcblplog) printf("XPRSsetcblplog\n");
    if (!__symbolic_XPRSsetcbmessage) printf("XPRSsetcbmessage\n");
    if (!__symbolic_XPRSsetcbmipthread) printf("XPRSsetcbmipthread\n");
    if (!__symbolic_XPRSsetcbnewnode) printf("XPRSsetcbnewnode\n");
    if (!__symbolic_XPRSsetcbnlpevaluate) printf("XPRSsetcbnlpevaluate\n");
    if (!__symbolic_XPRSsetcbnlpgradient) printf("XPRSsetcbnlpgradient\n");
    if (!__symbolic_XPRSsetcbnlphessian) printf("XPRSsetcbnlphessian\n");
    if (!__symbolic_XPRSsetcbnodecutoff) printf("XPRSsetcbnodecutoff\n");
    if (!__symbolic_XPRSsetcboptnode) printf("XPRSsetcboptnode\n");
    if (!__symbolic_XPRSsetcbpreintsol) printf("XPRSsetcbpreintsol\n");
    if (!__symbolic_XPRSsetcbprenode) printf("XPRSsetcbprenode\n");
    if (!__symbolic_XPRSsetcbsepnode) printf("XPRSsetcbsepnode\n");
    if (!__symbolic_XPRSsetdblcontrol) printf("XPRSsetdblcontrol\n");
    if (!__symbolic_XPRSsetdefaultcontrol) printf("XPRSsetdefaultcontrol\n");
    if (!__symbolic_XPRSsetdefaults) printf("XPRSsetdefaults\n");
    if (!__symbolic_XPRSsetindicators) printf("XPRSsetindicators\n");
    if (!__symbolic_XPRSsetintcontrol) printf("XPRSsetintcontrol\n");
    if (!__symbolic_XPRSsetlogfile) printf("XPRSsetlogfile\n");
    if (!__symbolic_XPRSsetmessagestatus) printf("XPRSsetmessagestatus\n");
    if (!__symbolic_XPRSsetprobname) printf("XPRSsetprobname\n");
    if (!__symbolic_XPRSsetstrcontrol) printf("XPRSsetstrcontrol\n");
    if (!__symbolic_XPRSstorebounds) printf("XPRSstorebounds\n");
    if (!__symbolic_XPRSstorecuts) printf("XPRSstorecuts\n");
    if (!__symbolic_XPRSwritebasis) printf("XPRSwritebasis\n");
    if (!__symbolic_XPRSwritebinsol) printf("XPRSwritebinsol\n");
    if (!__symbolic_XPRSwritedirs) printf("XPRSwritedirs\n");
    if (!__symbolic_XPRSwriteprob) printf("XPRSwriteprob\n");
    if (!__symbolic_XPRSwriteprtrange) printf("XPRSwriteprtrange\n");
    if (!__symbolic_XPRSwriteprtsol) printf("XPRSwriteprtsol\n");
    if (!__symbolic_XPRSwriterange) printf("XPRSwriterange\n");
    if (!__symbolic_XPRSwriteslxsol) printf("XPRSwriteslxsol\n");
    if (!__symbolic_XPRSwritesol) printf("XPRSwritesol\n");

}

int unload_xprs_symbols() {
    /* unload library */
    if (!g_module_close (__xprs_module)) return SYMBOL_UNLOAD_FAIL;

    return SYMBOL_UNLOAD_SUCCESS;
}

