/*
 *!/bin/sh
 *
 * Copyright 2010-2012 Christophe-Marie Duquesne <chm.duquesne@gmail.com>
 *
 * This file is part of lazylpsolverlibs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License.
 *
 * lazylpsolverlibs is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the Eclipse Public License
 * along with this program.  If not, see
 * <http://www.eclipse.org/legal/epl-v10.html>.
 *
 * This file was generated by tools/generate_stub.sh. Do not modify
 * directly
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lazygurobi.h"

GModule *g_module_open_all(const gchar *name, GModuleFlags flags) {
    char *LIB_PATH, *LIB_PATH_COPY, *p, *dir;
    GModule *res;

    p = NULL;
    dir = NULL;
    res = NULL;

#ifdef _WIN32
    LIB_PATH = getenv("PATH");
#define PATH_SEP ';'
#else
    LIB_PATH = getenv("LD_LIBRARY_PATH");
#define PATH_SEP ':'
#endif

    res = g_module_open(g_module_build_path(NULL, name), flags);
    if (res) {
        return res;
    }
    if (LIB_PATH) {
        LIB_PATH_COPY = malloc(strlen(LIB_PATH));
        strncpy(LIB_PATH_COPY, LIB_PATH, strlen(LIB_PATH));
        p = LIB_PATH_COPY;
        dir = p;
        while ((p = strchr(p, PATH_SEP))) {
            *p = '\0';
            p++;
            res = g_module_open(g_module_build_path(dir, name), flags);
            if (res) {
                free(LIB_PATH_COPY);
                return res;
            }
            dir = p;
        }
        res = g_module_open(g_module_build_path(dir, name), flags);
        free(LIB_PATH_COPY);
    }

    return res;
}

int load_gurobi_symbols() {
    int res;
    char *LAZYLPSOLVERLIBS_GUROBI_LIB_PATH; /* environment variable */
    LAZYLPSOLVERLIBS_GUROBI_LIB_PATH = NULL;
    __gurobi_module = NULL;

    /* first, try to read the path to load from the environment */
    LAZYLPSOLVERLIBS_GUROBI_LIB_PATH = getenv("LAZYLPSOLVERLIBS_GUROBI_LIB_PATH");
    if (LAZYLPSOLVERLIBS_GUROBI_LIB_PATH != NULL) {
        __gurobi_module = g_module_open(LAZYLPSOLVERLIBS_GUROBI_LIB_PATH, G_MODULE_BIND_LAZY);
    }

    /* if this failed, try to load libraries without version number */
    if (!__gurobi_module) __gurobi_module = g_module_open_all("gurobi", G_MODULE_BIND_LAZY);

    /* then try some versioned library names known to work (most recent first)*/
    if (!__gurobi_module) __gurobi_module = g_module_open_all("gurobi461", G_MODULE_BIND_LAZY);
    if (!__gurobi_module) __gurobi_module = g_module_open_all("gurobi452", G_MODULE_BIND_LAZY);
    if (!__gurobi_module) __gurobi_module = g_module_open_all("gurobi402", G_MODULE_BIND_LAZY);
    if (!__gurobi_module) __gurobi_module = g_module_open_all("gurobi303", G_MODULE_BIND_LAZY);

    /* if everything failed, give up */
    if (!__gurobi_module) return SYMBOL_LOAD_FAIL;

    res = SYMBOL_LOAD_SUCCESS;

    if (!g_module_symbol(__gurobi_module, "GRBaddconstr", (gpointer *) &__symbolic_GRBaddconstr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddconstrs", (gpointer *) &__symbolic_GRBaddconstrs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddrangeconstr", (gpointer *) &__symbolic_GRBaddrangeconstr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddrangeconstrs", (gpointer *) &__symbolic_GRBaddrangeconstrs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddsos", (gpointer *) &__symbolic_GRBaddsos)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddvar", (gpointer *) &__symbolic_GRBaddvar)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBaddvars", (gpointer *) &__symbolic_GRBaddvars)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcbcut", (gpointer *) &__symbolic_GRBcbcut)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcbget", (gpointer *) &__symbolic_GRBcbget)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcbsolution", (gpointer *) &__symbolic_GRBcbsolution)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcheckmodel", (gpointer *) &__symbolic_GRBcheckmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBchgcoeffs", (gpointer *) &__symbolic_GRBchgcoeffs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcomputeIIS", (gpointer *) &__symbolic_GRBcomputeIIS)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBconverttofixed", (gpointer *) &__symbolic_GRBconverttofixed)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBcopymodel", (gpointer *) &__symbolic_GRBcopymodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBdelconstrs", (gpointer *) &__symbolic_GRBdelconstrs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBdelsos", (gpointer *) &__symbolic_GRBdelsos)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBdelvars", (gpointer *) &__symbolic_GRBdelvars)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBfeasibility", (gpointer *) &__symbolic_GRBfeasibility)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBfixedmodel", (gpointer *) &__symbolic_GRBfixedmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBfreeenv", (gpointer *) &__symbolic_GRBfreeenv)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBfreemodel", (gpointer *) &__symbolic_GRBfreemodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetattrinfo", (gpointer *) &__symbolic_GRBgetattrinfo)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcallbackfunc", (gpointer *) &__symbolic_GRBgetcallbackfunc)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcbwhatinfo", (gpointer *) &__symbolic_GRBgetcbwhatinfo)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcharattrarray", (gpointer *) &__symbolic_GRBgetcharattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcharattrelement", (gpointer *) &__symbolic_GRBgetcharattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcharattrlist", (gpointer *) &__symbolic_GRBgetcharattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetcoeff", (gpointer *) &__symbolic_GRBgetcoeff)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetconstrs", (gpointer *) &__symbolic_GRBgetconstrs)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblattr", (gpointer *) &__symbolic_GRBgetdblattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblattrarray", (gpointer *) &__symbolic_GRBgetdblattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblattrelement", (gpointer *) &__symbolic_GRBgetdblattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblattrlist", (gpointer *) &__symbolic_GRBgetdblattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblparam", (gpointer *) &__symbolic_GRBgetdblparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetdblparaminfo", (gpointer *) &__symbolic_GRBgetdblparaminfo)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetenv", (gpointer *) &__symbolic_GRBgetenv)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgeterrormsg", (gpointer *) &__symbolic_GRBgeterrormsg)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintattr", (gpointer *) &__symbolic_GRBgetintattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintattrarray", (gpointer *) &__symbolic_GRBgetintattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintattrelement", (gpointer *) &__symbolic_GRBgetintattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintattrlist", (gpointer *) &__symbolic_GRBgetintattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintparam", (gpointer *) &__symbolic_GRBgetintparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetintparaminfo", (gpointer *) &__symbolic_GRBgetintparaminfo)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetlogfile", (gpointer *) &__symbolic_GRBgetlogfile)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetmerrormsg", (gpointer *) &__symbolic_GRBgetmerrormsg)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetnumparams", (gpointer *) &__symbolic_GRBgetnumparams)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetparamname", (gpointer *) &__symbolic_GRBgetparamname)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetparamtype", (gpointer *) &__symbolic_GRBgetparamtype)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetsos", (gpointer *) &__symbolic_GRBgetsos)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrattr", (gpointer *) &__symbolic_GRBgetstrattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrattrarray", (gpointer *) &__symbolic_GRBgetstrattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrattrelement", (gpointer *) &__symbolic_GRBgetstrattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrattrlist", (gpointer *) &__symbolic_GRBgetstrattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrparam", (gpointer *) &__symbolic_GRBgetstrparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetstrparaminfo", (gpointer *) &__symbolic_GRBgetstrparaminfo)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBgetvars", (gpointer *) &__symbolic_GRBgetvars)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBiismodel", (gpointer *) &__symbolic_GRBiismodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBloadenv", (gpointer *) &__symbolic_GRBloadenv)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBloadmodel", (gpointer *) &__symbolic_GRBloadmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBmsg", (gpointer *) &__symbolic_GRBmsg)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBnewmodel", (gpointer *) &__symbolic_GRBnewmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBoptimize", (gpointer *) &__symbolic_GRBoptimize)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBplatform", (gpointer *) &__symbolic_GRBplatform)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBpresolvemodel", (gpointer *) &__symbolic_GRBpresolvemodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBread", (gpointer *) &__symbolic_GRBread)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBreadmodel", (gpointer *) &__symbolic_GRBreadmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBreadparams", (gpointer *) &__symbolic_GRBreadparams)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBrelaxmodel", (gpointer *) &__symbolic_GRBrelaxmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBresetmodel", (gpointer *) &__symbolic_GRBresetmodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBresetparams", (gpointer *) &__symbolic_GRBresetparams)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetcallbackfunc", (gpointer *) &__symbolic_GRBsetcallbackfunc)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetcharattrarray", (gpointer *) &__symbolic_GRBsetcharattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetcharattrelement", (gpointer *) &__symbolic_GRBsetcharattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetcharattrlist", (gpointer *) &__symbolic_GRBsetcharattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetdblattr", (gpointer *) &__symbolic_GRBsetdblattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetdblattrarray", (gpointer *) &__symbolic_GRBsetdblattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetdblattrelement", (gpointer *) &__symbolic_GRBsetdblattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetdblattrlist", (gpointer *) &__symbolic_GRBsetdblattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetdblparam", (gpointer *) &__symbolic_GRBsetdblparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetintattr", (gpointer *) &__symbolic_GRBsetintattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetintattrarray", (gpointer *) &__symbolic_GRBsetintattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetintattrelement", (gpointer *) &__symbolic_GRBsetintattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetintattrlist", (gpointer *) &__symbolic_GRBsetintattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetintparam", (gpointer *) &__symbolic_GRBsetintparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetlogfile", (gpointer *) &__symbolic_GRBsetlogfile)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetsignal", (gpointer *) &__symbolic_GRBsetsignal)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetstrattr", (gpointer *) &__symbolic_GRBsetstrattr)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetstrattrarray", (gpointer *) &__symbolic_GRBsetstrattrarray)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetstrattrelement", (gpointer *) &__symbolic_GRBsetstrattrelement)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetstrattrlist", (gpointer *) &__symbolic_GRBsetstrattrlist)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBsetstrparam", (gpointer *) &__symbolic_GRBsetstrparam)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBstrongbranch", (gpointer *) &__symbolic_GRBstrongbranch)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBterminate", (gpointer *) &__symbolic_GRBterminate)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBupdatemodel", (gpointer *) &__symbolic_GRBupdatemodel)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBversion", (gpointer *) &__symbolic_GRBversion)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBwrite", (gpointer *) &__symbolic_GRBwrite)) res = SYMBOL_MISSING;
    if (!g_module_symbol(__gurobi_module, "GRBwriteparams", (gpointer *) &__symbolic_GRBwriteparams)) res = SYMBOL_MISSING;

    return res;
}

void print_gurobi_missing_symbols() {

    if (!__symbolic_GRBaddconstr) printf("GRBaddconstr\n");
    if (!__symbolic_GRBaddconstrs) printf("GRBaddconstrs\n");
    if (!__symbolic_GRBaddrangeconstr) printf("GRBaddrangeconstr\n");
    if (!__symbolic_GRBaddrangeconstrs) printf("GRBaddrangeconstrs\n");
    if (!__symbolic_GRBaddsos) printf("GRBaddsos\n");
    if (!__symbolic_GRBaddvar) printf("GRBaddvar\n");
    if (!__symbolic_GRBaddvars) printf("GRBaddvars\n");
    if (!__symbolic_GRBcbcut) printf("GRBcbcut\n");
    if (!__symbolic_GRBcbget) printf("GRBcbget\n");
    if (!__symbolic_GRBcbsolution) printf("GRBcbsolution\n");
    if (!__symbolic_GRBcheckmodel) printf("GRBcheckmodel\n");
    if (!__symbolic_GRBchgcoeffs) printf("GRBchgcoeffs\n");
    if (!__symbolic_GRBcomputeIIS) printf("GRBcomputeIIS\n");
    if (!__symbolic_GRBconverttofixed) printf("GRBconverttofixed\n");
    if (!__symbolic_GRBcopymodel) printf("GRBcopymodel\n");
    if (!__symbolic_GRBdelconstrs) printf("GRBdelconstrs\n");
    if (!__symbolic_GRBdelsos) printf("GRBdelsos\n");
    if (!__symbolic_GRBdelvars) printf("GRBdelvars\n");
    if (!__symbolic_GRBfeasibility) printf("GRBfeasibility\n");
    if (!__symbolic_GRBfixedmodel) printf("GRBfixedmodel\n");
    if (!__symbolic_GRBfreeenv) printf("GRBfreeenv\n");
    if (!__symbolic_GRBfreemodel) printf("GRBfreemodel\n");
    if (!__symbolic_GRBgetattrinfo) printf("GRBgetattrinfo\n");
    if (!__symbolic_GRBgetcallbackfunc) printf("GRBgetcallbackfunc\n");
    if (!__symbolic_GRBgetcbwhatinfo) printf("GRBgetcbwhatinfo\n");
    if (!__symbolic_GRBgetcharattrarray) printf("GRBgetcharattrarray\n");
    if (!__symbolic_GRBgetcharattrelement) printf("GRBgetcharattrelement\n");
    if (!__symbolic_GRBgetcharattrlist) printf("GRBgetcharattrlist\n");
    if (!__symbolic_GRBgetcoeff) printf("GRBgetcoeff\n");
    if (!__symbolic_GRBgetconstrs) printf("GRBgetconstrs\n");
    if (!__symbolic_GRBgetdblattr) printf("GRBgetdblattr\n");
    if (!__symbolic_GRBgetdblattrarray) printf("GRBgetdblattrarray\n");
    if (!__symbolic_GRBgetdblattrelement) printf("GRBgetdblattrelement\n");
    if (!__symbolic_GRBgetdblattrlist) printf("GRBgetdblattrlist\n");
    if (!__symbolic_GRBgetdblparam) printf("GRBgetdblparam\n");
    if (!__symbolic_GRBgetdblparaminfo) printf("GRBgetdblparaminfo\n");
    if (!__symbolic_GRBgetenv) printf("GRBgetenv\n");
    if (!__symbolic_GRBgeterrormsg) printf("GRBgeterrormsg\n");
    if (!__symbolic_GRBgetintattr) printf("GRBgetintattr\n");
    if (!__symbolic_GRBgetintattrarray) printf("GRBgetintattrarray\n");
    if (!__symbolic_GRBgetintattrelement) printf("GRBgetintattrelement\n");
    if (!__symbolic_GRBgetintattrlist) printf("GRBgetintattrlist\n");
    if (!__symbolic_GRBgetintparam) printf("GRBgetintparam\n");
    if (!__symbolic_GRBgetintparaminfo) printf("GRBgetintparaminfo\n");
    if (!__symbolic_GRBgetlogfile) printf("GRBgetlogfile\n");
    if (!__symbolic_GRBgetmerrormsg) printf("GRBgetmerrormsg\n");
    if (!__symbolic_GRBgetnumparams) printf("GRBgetnumparams\n");
    if (!__symbolic_GRBgetparamname) printf("GRBgetparamname\n");
    if (!__symbolic_GRBgetparamtype) printf("GRBgetparamtype\n");
    if (!__symbolic_GRBgetsos) printf("GRBgetsos\n");
    if (!__symbolic_GRBgetstrattr) printf("GRBgetstrattr\n");
    if (!__symbolic_GRBgetstrattrarray) printf("GRBgetstrattrarray\n");
    if (!__symbolic_GRBgetstrattrelement) printf("GRBgetstrattrelement\n");
    if (!__symbolic_GRBgetstrattrlist) printf("GRBgetstrattrlist\n");
    if (!__symbolic_GRBgetstrparam) printf("GRBgetstrparam\n");
    if (!__symbolic_GRBgetstrparaminfo) printf("GRBgetstrparaminfo\n");
    if (!__symbolic_GRBgetvars) printf("GRBgetvars\n");
    if (!__symbolic_GRBiismodel) printf("GRBiismodel\n");
    if (!__symbolic_GRBloadenv) printf("GRBloadenv\n");
    if (!__symbolic_GRBloadmodel) printf("GRBloadmodel\n");
    if (!__symbolic_GRBmsg) printf("GRBmsg\n");
    if (!__symbolic_GRBnewmodel) printf("GRBnewmodel\n");
    if (!__symbolic_GRBoptimize) printf("GRBoptimize\n");
    if (!__symbolic_GRBplatform) printf("GRBplatform\n");
    if (!__symbolic_GRBpresolvemodel) printf("GRBpresolvemodel\n");
    if (!__symbolic_GRBread) printf("GRBread\n");
    if (!__symbolic_GRBreadmodel) printf("GRBreadmodel\n");
    if (!__symbolic_GRBreadparams) printf("GRBreadparams\n");
    if (!__symbolic_GRBrelaxmodel) printf("GRBrelaxmodel\n");
    if (!__symbolic_GRBresetmodel) printf("GRBresetmodel\n");
    if (!__symbolic_GRBresetparams) printf("GRBresetparams\n");
    if (!__symbolic_GRBsetcallbackfunc) printf("GRBsetcallbackfunc\n");
    if (!__symbolic_GRBsetcharattrarray) printf("GRBsetcharattrarray\n");
    if (!__symbolic_GRBsetcharattrelement) printf("GRBsetcharattrelement\n");
    if (!__symbolic_GRBsetcharattrlist) printf("GRBsetcharattrlist\n");
    if (!__symbolic_GRBsetdblattr) printf("GRBsetdblattr\n");
    if (!__symbolic_GRBsetdblattrarray) printf("GRBsetdblattrarray\n");
    if (!__symbolic_GRBsetdblattrelement) printf("GRBsetdblattrelement\n");
    if (!__symbolic_GRBsetdblattrlist) printf("GRBsetdblattrlist\n");
    if (!__symbolic_GRBsetdblparam) printf("GRBsetdblparam\n");
    if (!__symbolic_GRBsetintattr) printf("GRBsetintattr\n");
    if (!__symbolic_GRBsetintattrarray) printf("GRBsetintattrarray\n");
    if (!__symbolic_GRBsetintattrelement) printf("GRBsetintattrelement\n");
    if (!__symbolic_GRBsetintattrlist) printf("GRBsetintattrlist\n");
    if (!__symbolic_GRBsetintparam) printf("GRBsetintparam\n");
    if (!__symbolic_GRBsetlogfile) printf("GRBsetlogfile\n");
    if (!__symbolic_GRBsetsignal) printf("GRBsetsignal\n");
    if (!__symbolic_GRBsetstrattr) printf("GRBsetstrattr\n");
    if (!__symbolic_GRBsetstrattrarray) printf("GRBsetstrattrarray\n");
    if (!__symbolic_GRBsetstrattrelement) printf("GRBsetstrattrelement\n");
    if (!__symbolic_GRBsetstrattrlist) printf("GRBsetstrattrlist\n");
    if (!__symbolic_GRBsetstrparam) printf("GRBsetstrparam\n");
    if (!__symbolic_GRBstrongbranch) printf("GRBstrongbranch\n");
    if (!__symbolic_GRBterminate) printf("GRBterminate\n");
    if (!__symbolic_GRBupdatemodel) printf("GRBupdatemodel\n");
    if (!__symbolic_GRBversion) printf("GRBversion\n");
    if (!__symbolic_GRBwrite) printf("GRBwrite\n");
    if (!__symbolic_GRBwriteparams) printf("GRBwriteparams\n");

}

int unload_gurobi_symbols() {
    /* unload library */
    if (!g_module_close (__gurobi_module)) return SYMBOL_UNLOAD_FAIL;

    return SYMBOL_UNLOAD_SUCCESS;
}

